basePath: /api/
definitions:
  advisor.Advice:
    properties:
      code:
        type: integer
      content:
        type: string
      status:
        type: string
      title:
        type: string
    type: object
  api.SQLCheckResult:
    properties:
      adviceList:
        description: A list of SQL check advice.
        items:
          $ref: '#/definitions/advisor.Advice'
        type: array
      result:
        description: Result is the SQL check result.
        type: string
    type: object
  echo.HTTPError:
    properties:
      message: {}
    type: object
host: localhost:8080
info:
  contact:
    email: support@bytebase.com
    name: API Support
    url: https://github.com/bytebase/bytebase/
  description: The OpenAPI for bytebase.
  license:
    name: MIT
    url: https://github.com/bytebase/bytebase/blob/main/LICENSE
  termsOfService: https://www.bytebase.com/terms
  title: Bytebase OpenAPI
  version: "1.0"
paths:
  /sql/advise:
    get:
      consumes:
      - '*/*'
      description: Parse and check the SQL statement by your schema review policy.
      parameters:
      - description: The environment name
        in: query
        name: env
        required: true
        type: string
      - description: The SQL statement
        in: query
        name: statement
        required: true
        type: string
      - description: The database type
        enum:
        - MySQL
        - PostgreSQL
        - TiDB
        in: query
        name: database
        required: true
        type: string
      - default: utf8mb4
        description: The database charset. Default 'utf8mb4'
        in: query
        name: charset
        type: string
      - default: utf8mb4_general_ci
        description: The database collation. Default 'utf8mb4_general_ci'
        in: query
        name: collation
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SQLCheckResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Check the SQL statement.
      tags:
      - Schema Review
schemes:
- http
swagger: "2.0"
