basePath: /v1/
definitions:
  advisor.Advice:
    properties:
      code:
        description: Code is the SQL check error code.
        type: integer
      content:
        type: string
      status:
        description: Status is the SQL check result. Could be "SUCCESS", "WARN", "ERROR"
        type: string
      title:
        type: string
    type: object
  echo.HTTPError:
    properties:
      message: {}
    type: object
host: localhost:8080
info:
  contact:
    email: support@bytebase.com
    name: API Support
    url: https://github.com/bytebase/bytebase/
  description: The OpenAPI for bytebase.
  license:
    name: MIT
    url: https://github.com/bytebase/bytebase/blob/main/LICENSE
  termsOfService: https://www.bytebase.com/terms
  title: Bytebase OpenAPI
  version: "1.0"
paths:
  /sql/advise:
    post:
      consumes:
        - "*/*"
      description: Parse and check the SQL statement according to the SQL review policy.
      parameters:
        - description: The environment name. Case sensitive.
          in: body
          name: environmentName
          required: true
          schema:
            type: string
        - description: The SQL statement.
          in: body
          name: statement
          required: true
          schema:
            type: string
        - description:
            The database type. Required if the port, host and database name
            is not specified.
          enum:
            - MYSQL
            - POSTGRES
            - TIDB
            - OCEANBASE
            - SNOWFLAKE
            - MSSQL
          in: body
          name: databaseType
          schema:
            type: string
        - description: The instance host.
          in: body
          name: host
          schema:
            type: string
        - description: The instance port.
          in: body
          name: port
          schema:
            type: string
        - description: The database name in the instance.
          in: body
          name: databaseName
          schema:
            type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: "#/definitions/advisor.Advice"
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/echo.HTTPError"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/echo.HTTPError"
      summary: Check the SQL statement.
      tags:
        - SQL review
schemes:
  - http
swagger: "2.0"
