updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gomod"
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    commit-message:
      prefix: "chore"
    directory: "/frontend"
    schedule:
      interval: "monthly"

version: 2
