updates:
  - package-ecosystem: "gomod"
    commit-message:
      prefix: "Go Modules"
    directory: "/" 
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"
    
version: 2
