updates:
  - package-ecosystem: "gomod"
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"
  - package-ecosystem: "npm"
    commit-message:
      prefix: "chore"
    directory: "/frontend"
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"

version: 2
