tasks:
  - name: Init Frontend
    before: cd ./frontend
    init: pnpm i
    command: pnpm dev
  - name: Init Backend
    init: curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s
    command: rm -fv .air/pgdata/postmaster.pid && ./bin/air -c scripts/.air.toml

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8080
    onOpen: ignore
