linters:
  enable:
    - errcheck
    - goimports
    - revive
    - govet
    - staticcheck
    - misspell

# golangci-lint run --exclude="Rollback,logger.Sync,pgInstance.Stop"
issues:
  exclude:
    - Rollback
    - logger.Sync
    - pgInstance.Stop

run:
  timeout: 5m
