linters:
  enable:
    - errcheck
    - goimports
    - golint
    - govet
    - staticcheck
    - misspell

# golangci-lint run --exclude="Rollback,logger.Sync"
issues:
  exclude:
    - Rollback
    - logger.Sync

run:
  timeout: 5m
