projects:
    bytebase:
        repo: .
        commands:
            - name: backend
              cmd: pwd && CGO_ENABLED=1 go build -gcflags="all=-N -l" -ldflags="-extldflags='-ld_classic'" -p=16 -o ./bytebase-build/bytebase ./backend/bin/server/main.go && ./bytebase-build/bytebase --port 8080 --data .
              dir: .
            - name: frontend
              cmd: pwd && pnpm i && pnpm dev
              dir: ./frontend
