import { DEFAULT_LIGHT_EDITOR_THEME, type SQLEditorTheme } from "../types";

export const light: SQLEditorTheme = {
  id: "light",
  name: "Default Light",
  monacoBase: DEFAULT_LIGHT_EDITOR_THEME,
  tokens: {
    "--color-control": "#52525b",
    "--color-control-hover": "#18181b",
    "--color-control-light": "#71717a",
    "--color-control-light-hover": "#52525b",
    "--color-control-bg": "#f3f4f6",
    "--color-control-bg-hover": "#e5e7eb",
    "--color-control-placeholder": "#a1a1aa",
    "--color-control-border": "#d1d5db",
    "--color-accent": "#4f46e5",
    "--color-accent-hover": "#3730a3",
    "--color-accent-disabled": "#a5b4fc",
    "--color-accent-text": "#ffffff",
    "--color-main": "#18181b",
    "--color-main-hover": "#3f3f46",
    "--color-main-text": "#ffffff",
    "--color-background": "#ffffff",
    "--color-block-border": "#e5e7eb",
    "--color-link-hover": "#e5e7eb",
    "--color-info": "#2563eb",
    "--color-info-hover": "#1d4ed8",
    "--color-warning": "#f59e0b",
    "--color-warning-hover": "#b45309",
    "--color-error": "#dc2626",
    "--color-error-hover": "#b91c1c",
    "--color-success": "#16a34a",
    "--color-success-hover": "#15803d",
    "--color-matrix-green": "#00cc00",
    "--color-matrix-green-hover": "#88ff88",
    "--color-dark-bg": "#1e1e1e",
  },
};
