import { DEFAULT_DARK_EDITOR_THEME, type SQLEditorTheme } from "../types";

export const dark: SQLEditorTheme = {
  id: "dark",
  name: "Default Dark",
  monacoBase: DEFAULT_DARK_EDITOR_THEME,
  tokens: {
    "--color-control": "#e5e7eb",
    "--color-control-hover": "#f3f4f6",
    "--color-control-light": "#d1d5db",
    "--color-control-light-hover": "#e5e7eb",
    "--color-control-bg": "#374151",
    "--color-control-bg-hover": "#4b5563",
    "--color-control-placeholder": "#9ca3af",
    "--color-control-border": "#52525b",
    "--color-accent": "#6366f1",
    "--color-accent-hover": "#818cf8",
    "--color-accent-disabled": "#4338ca",
    "--color-accent-text": "#ffffff",
    "--color-main": "#f4f4f5",
    "--color-main-hover": "#d4d4d8",
    "--color-main-text": "#18181b",
    "--color-background": "#1e1e1e",
    "--color-block-border": "#3f3f46",
    "--color-link-hover": "#3f3f46",
    "--color-info": "#60a5fa",
    "--color-info-hover": "#93c5fd",
    "--color-warning": "#fbbf24",
    "--color-warning-hover": "#fde047",
    "--color-error": "#f87171",
    "--color-error-hover": "#fca5a5",
    "--color-success": "#4ade80",
    "--color-success-hover": "#86efac",
    "--color-matrix-green": "#00cc00",
    "--color-matrix-green-hover": "#88ff88",
    "--color-dark-bg": "#1e1e1e",
  },
};
