name: SQL-Review
description: "Parse and check the SQL statement according to the schema review rules"
inputs:
  override:
    description: "SQL check configuration override file path."
    required: false
    default: ""
  database:
    description: 'The database type, should be one of "MYSQL", "POSTGRES" or "TIDB".'
    required: true
  template:
    description: 'The SQL check template id, required if the override is not specified. Should be one of "bb.sql-review.prod", "bb.sql-review.dev".'
    required: false
runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v23.2
      with:
        files: |
          **/*.sql
    - name: SQL Review
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "Start check statement in file $file"
          ./.github/actions/sql-review/sql-review.sh $file ${{ inputs.database }} ${{ inputs.override }} ${{ inputs.template }}
        done
      shell: bash
branding:
  icon: "database"
  color: "gray-dark"
