{{- $host := .Values.bytebase.option.host -}}
{{- $port := .Values.bytebase.option.port -}}
{{- $pg := .Values.bytebase.option.pg -}}
{{- $data := .Values.bytebase.option.data -}}
{{- $version := .Values.bytebase.version -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bytebase
  namespace: {{ template "bytebase.namespace" . }}
  labels:
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app: bytebase
  template:
    metadata:
      labels:
        app: bytebase
    spec:
      containers:
        - name: bytebase
          image: bytebase/bytebase:{{ $version }}
          args:
            [
              "--data",
              {{ $data | quote }},
              "--host",
              {{ $host | quote }},
              "--port",
              {{ $port | quote }},
            ]
          ports:
            - containerPort: {{ $port }}
          volumeMounts:
            - name: data
              mountPath: {{ $data }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ $port }}
            initialDelaySeconds: 300
            periodSeconds: 300
            timeoutSeconds: 60
      volumes:
        - name: data
          emptyDir: {}
