{{- if false -}}
---
# For customizing the secret provider, please refer to the provider documentation,
# such as Azure Key Vault, Hashicorp Vault.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-bytebase-spc
  namespace: {{ template "bytebase.namespace" . }}
  labels:
    {{- include "bytebase.labels" . | nindent 4}}
spec:
  # Currently, we only support azure as secret provider.
  provider: azure
  secretObjects:
  - data:
    # data field to populate
    - key: pgurl
      # name of the mounted content to sync. this could be the object name or the object alias
      objectName: "ObjectName"
    secretName: "bytebase-secret"
    type: Opaque
  # Provider-specific parameters.
  # https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/usage/.
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "KeyVaultName"
    objects: |
      array:
        - |
          objectName: "ObjectName"
          objectType: secret
          objectVersion: ""
    tenantID: "xxxxxxxx-yyyy-zzzz-aaaa-bbbbbbbbbbbb"
{{- end -}}
