{{- $port := .Values.bytebase.option.port -}}
apiVersion: v1
kind: Service
metadata:
  name: bytebase-entrypoint
  namespace: {{ template "bytebase.namespace" . }}
  labels:
    {{- include "bytebase.labels" . | nindent 4}}
spec:
  type: ClusterIP
  selector:
    app: bytebase
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ $port }}
