# bytebase
{{- $version := .Values.bytebase.version -}}
{{- $registryMirrorHost := .Values.bytebase.registryMirrorHost -}}

# bytebase.option
{{- $port := .Values.bytebase.option.port -}}
{{- $data := .Values.bytebase.option.data -}}
{{- $external_url := index .Values.bytebase.option "external-url" -}}
{{- $disable_sample := index .Values.bytebase.option "disable-sample" -}}

# bytebase.option.externalPg
{{- $externalPgURL := .Values.bytebase.option.externalPg.url -}}
{{- $externalPgExistingPgURLSecret := .Values.bytebase.option.externalPg.existingPgURLSecret -}}
{{- $externalPgexistingPgURLSecretKey := .Values.bytebase.option.externalPg.existingPgURLSecretKey -}}
{{- $externalPgHost := .Values.bytebase.option.externalPg.pgHost -}}
{{- $externalPgPort := .Values.bytebase.option.externalPg.pgPort -}}
{{- $externalPgUsername := .Values.bytebase.option.externalPg.pgUsername -}}
{{- $externalPgPassword := .Values.bytebase.option.externalPg.pgPassword -}}
{{- $externalPgDatabase := .Values.bytebase.option.externalPg.pgDatabase -}}
{{- $externalPgExistingPgPasswordSecret := .Values.bytebase.option.externalPg.existingPgPasswordSecret -}}
{{- $externalPgExistingPgPasswordSecretKey := .Values.bytebase.option.externalPg.existingPgPasswordSecretKey -}}

# bytbease.persistence
{{- $persistenceEnable := .Values.bytebase.persistence.enabled -}}
{{- $persistenceExistingClaim := .Values.bytebase.persistence.existingClaim -}}
{{- $persistenceStorage := .Values.bytebase.persistence.storage -}}
{{- $persistenceStorageClass := .Values.bytebase.persistence.storageClass}}


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bytebase
  namespace: {{ template "bytebase.namespace" . }}
  labels:
    {{- include "bytebase.labels" . | nindent 4}}
spec:
  selector:
    matchLabels:
      app: bytebase
  serviceName: "bytebase"
  replicas: 1
  template:
    metadata:
      labels:
        app: bytebase
    spec:
      containers:
        - name: bytebase
          {{ if $registryMirrorHost }}
          # If user specifies a registry mirror host, we should use that instead of the default.
          image: {{ trimSuffix "/" $registryMirrorHost }}/bytebase/bytebase:{{ $version }}
          {{ else }}
          image: bytebase/bytebase:{{ $version }}
          {{ end }}
          imagePullPolicy: Always
          env:
          - name: PG_URL
            {{ if $externalPgExistingPgURLSecret }}
            # If user specifies an existing secret, we should read the external pg connection string in that secret.
            valueFrom:
              secretKeyRef:
                name: {{ $externalPgExistingPgURLSecret }}
                key: {{ $externalPgexistingPgURLSecretKey }}
            {{ else }}
            value: {{ $externalPgURL }}
            {{ end }}
          args:
            [
              "--data",
              {{ $data | quote }},
              "--port",
              {{ $port | quote }},
              "--external-url",
              # helm parser cannot handle the dash in the value, so we need to quote it, so we use $external_url instead of $external-url.
              {{ $external_url | quote }},
              {{ if $disable_sample }}
              "--disable-sample",
              {{ end }}
            ]
          ports:
            - containerPort: {{ $port }}
              name: web
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ $port }}
            initialDelaySeconds: 300
            periodSeconds: 300
            timeoutSeconds: 60
          volumeMounts:
            - mountPath: {{ $data }}
              {{ if $persistenceExistingClaim }}
              # If user specifies an existing PVC, use that instead of "bytebase-volume".
              name: {{ $persistenceExistingClaim | quote }}
              {{ else }}
              # Either user disable persistence or enable persistence but not specify an existing PVC, use "bytebase-volume" as the volume name. It means
              # that we will request to create a PVC with the specified storage class with name "bytebase-volume".
              name: bytebase-volume
              {{ end }}
      volumes:
        {{ if $persistenceEnable }}
        {{ if $persistenceExistingClaim }}
        # If user specifies an existing PVC, use that instead of "bytebase-volume".
        - name: {{ $persistenceExistingClaim| quote }}
          persistentVolumeClaim:
            claimName: {{ $persistenceExistingClaim | quote }}
        {{ else }}
        # If user enable persistence, but not specify an existing PVC, create a PVC with the specified storage class with name "bytebase-volume".
        - name: bytebase-volume
          persistentVolumeClaim:
            claimName: bytebase-volume
        {{ end }}
        {{ else }}
        # If user disable persistence, use an emptyDir volume.
        - name: bytebase-volume
          emptyDir: {}
        {{ end }}

---
{{ if $persistenceEnable }}
{{ if not $persistenceExistingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bytebase-volume
  namespace: {{ template "bytebase.namespace" . }}
  labels:
    {{- include "bytebase.labels" . | nindent 4}}
spec:
  storageClassName: {{ $persistenceStorageClass | quote }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ $persistenceStorage }}
{{ end }}
{{ end }}

