{{- $data := .Values.bytebase.option.data -}}
{{- $port := .Values.bytebase.option.port -}}
{{- $version := .Values.bytebase.version}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bytebase
  namespace: {{ template "bytebase.namespace" . }}
  labels:
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app: bytebase
  serviceName: "bytebase"
  replicas: 1
  template:
    metadata:
      labels:
        app: bytebase
    spec:
      containers:
        - name: bytebase
          image: "bytebase/bytebase:{{ $version }}"
          ports:
            - containerPort: {{ $port }}
              name: web
          volumeMounts:
            - mountPath: {{ $data }}
              name: bytebase
          readinessProbe:
            httpGet:
              path: /api/actuator/info
              port: web
            initialDelaySeconds: 2
            periodSeconds: 2
  volumeClaimTemplates:
    - metadata:
        name: bytebase
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ .Values.bytebase.storage }}"
