{{- $external_url := index .Values.bytebase.option "external-url" -}}
{{- $port := .Values.bytebase.option.port -}}
{{- $pg := .Values.bytebase.option.pg -}}
{{- $data := .Values.bytebase.option.data -}}
{{- $version := .Values.bytebase.version -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bytebase
  namespace: {{ template "bytebase.namespace" . }}
  labels:
    app.kubernetes.io/managed-by: helm
    app: bytebase
spec:
  selector:
    matchLabels:
      app: bytebase
  serviceName: "bytebase"
  replicas: 1
  template:
    metadata:
      labels:
        app: bytebase
    spec:
      containers:
        - name: bytebase
          image: "bytebase/bytebase:{{ $version }}"
          imagePullPolicy: Always
          args:
            [
              "--data",
              {{ $data | quote }},
              "--port",
              {{ $port | quote }},
              "--external-url",
              # helm parser cannot handle the dash in the value, so we need to quote it, so we use $external_url instead of $external-url.
              {{ $external_url | quote }},
              "--pg",
              {{ $pg | quote}},
            ]
          ports:
            - containerPort: {{ $port }}
              name: web
          readinessProbe:
            httpGet:
              path: /v1/actuator/info
              port: web
            initialDelaySeconds: 2
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ $port }}
            initialDelaySeconds: 300
            periodSeconds: 300
            timeoutSeconds: 60
          volumeMounts:
            - mountPath: {{ $data }}
              {{ if .Values.bytebase.persistence.existingClaim }}
              # If user specifies an existing PVC, use that instead of "bytebase-volume".
              name: {{ .Values.bytebase.persistence.existingClaim | quote }}
              {{ else }}
              # Either user disable persistence or enable persistence but not specify an existing PVC, use "bytebase-volume" as the volume name. It means
              # that we will request to create a PVC with the specified storage class with name "bytebase-volume".
              name: bytebase-volume
              {{ end }}
      volumes:
        {{ if .Values.bytebase.persistence.enabled }}
        {{ if .Values.bytebase.persistence.existingClaim }}
        # If user specifies an existing PVC, use that instead of "bytebase-volume".
        - name: {{ .Values.bytebase.persistence.existingClaim | quote }}
          persistentVolumeClaim:
            claimName: {{ .Values.bytebase.persistence.existingClaim | quote }}
        {{ else }}
        # If user enable persistence, but not specify an existing PVC, create a PVC with the specified storage class with name "bytebase-volume".
        - name: bytebase-volume
          persistentVolumeClaim:
            claimName: bytebase-volume
        {{ end }}
        {{ else }}
        # If user disable persistence, use an emptyDir volume.
        - name: bytebase-volume
          emptyDir: {}
        {{ end }}

---
{{ if .Values.bytebase.persistence.enabled }}
{{ if not .Values.bytebase.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bytebase-volume
  namespace: {{ template "bytebase.namespace" . }}
  labels:
    app.kubernetes.io/managed-by: helm
    app: bytebase
spec:
  storageClassName: {{ .Values.bytebase.persistence.storageClass | quote }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bytebase.persistence.storage }}
{{ end }}
{{ end }}

