// Code generated by protoc-gen-equal-go. DO NOT EDIT.
// source: v1/sheet_service.proto

package v1

func (x *CreateSheetRequest) Equal(y *CreateSheetRequest) bool {
	if x == y {
		return true
	}
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if x.Parent != y.Parent {
		return false
	}
	if !x.Sheet.Equal(y.Sheet) {
		return false
	}
	return true
}

func (x *BatchCreateSheetsRequest) Equal(y *BatchCreateSheetsRequest) bool {
	if x == y {
		return true
	}
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if x.Parent != y.Parent {
		return false
	}
	if len(x.Requests) != len(y.Requests) {
		return false
	}
	for i := 0; i < len(x.Requests); i++ {
		if !x.Requests[i].Equal(y.Requests[i]) {
			return false
		}
	}
	return true
}

func (x *BatchCreateSheetsResponse) Equal(y *BatchCreateSheetsResponse) bool {
	if x == y {
		return true
	}
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if len(x.Sheets) != len(y.Sheets) {
		return false
	}
	for i := 0; i < len(x.Sheets); i++ {
		if !x.Sheets[i].Equal(y.Sheets[i]) {
			return false
		}
	}
	return true
}

func (x *GetSheetRequest) Equal(y *GetSheetRequest) bool {
	if x == y {
		return true
	}
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if x.Name != y.Name {
		return false
	}
	if x.Raw != y.Raw {
		return false
	}
	return true
}

func (x *Sheet) Equal(y *Sheet) bool {
	if x == y {
		return true
	}
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if x.Name != y.Name {
		return false
	}
	if string(x.Content) != string(y.Content) {
		return false
	}
	if x.ContentSize != y.ContentSize {
		return false
	}
	return true
}
