// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/user_service.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the user to retrieve.
	// Format: users/{email}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_v1_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BatchGetUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user names to retrieve.
	// Format: users/{email}
	Names         []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUsersRequest) Reset() {
	*x = BatchGetUsersRequest{}
	mi := &file_v1_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUsersRequest) ProtoMessage() {}

func (x *BatchGetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUsersRequest.ProtoReflect.Descriptor instead.
func (*BatchGetUsersRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *BatchGetUsersRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type BatchGetUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The users from the specified request.
	Users         []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUsersResponse) Reset() {
	*x = BatchGetUsersResponse{}
	mi := &file_v1_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUsersResponse) ProtoMessage() {}

func (x *BatchGetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUsersResponse.ProtoReflect.Descriptor instead.
func (*BatchGetUsersResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type ListUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of users to return. The service may return fewer than
	// this value.
	// If unspecified, at most 10 users will be returned.
	// The maximum value is 1000; values above 1000 will be coerced to 1000.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous `ListUsers` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListUsers` must match
	// the call that provided the page token.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Show deleted users if specified.
	ShowDeleted bool `protobuf:"varint,3,opt,name=show_deleted,json=showDeleted,proto3" json:"show_deleted,omitempty"`
	// Filter is used to filter users returned in the list.
	// The syntax and semantics of CEL are documented at https://github.com/google/cel-spec
	//
	// Supported filter:
	// - name: the user name, support "==" and ".contains()" operator.
	// - email: the user email, support "==" and ".contains()" operator.
	// - state: check State enum for values, support "==" operator.
	// - project: the project full name in "projects/{id}" format, support "==" operator.
	//
	// For example:
	// name == "ed"
	// name.contains("ed")
	// email == "ed@bytebase.com"
	// email.contains("ed")
	// state == "DELETED"
	// project == "projects/sample-project"
	// You can combine filter conditions like:
	// name.contains("ed") && project == "projects/sample-project"
	// (name == "ed" || email == "ed@bytebase.com") && project == "projects/sample-project"
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_v1_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListUsersRequest) GetShowDeleted() bool {
	if x != nil {
		return x.ShowDeleted
	}
	return false
}

func (x *ListUsersRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The users from the specified request.
	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_v1_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user to create.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_v1_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user to update.
	//
	// The user's `name` field is used to identify the user to update.
	// Format: users/{email}
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// The list of fields to update.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// If set to true, and the user is not found, a new user will be created.
	// In this situation, `update_mask` is ignored.
	AllowMissing  bool `protobuf:"varint,6,opt,name=allow_missing,json=allowMissing,proto3" json:"allow_missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_v1_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateUserRequest) GetAllowMissing() bool {
	if x != nil {
		return x.AllowMissing
	}
	return false
}

type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the user to delete.
	// Format: users/{email}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_v1_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UndeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the deleted user.
	// Format: users/{email}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeleteUserRequest) Reset() {
	*x = UndeleteUserRequest{}
	mi := &file_v1_user_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteUserRequest) ProtoMessage() {}

func (x *UndeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteUserRequest.ProtoReflect.Descriptor instead.
func (*UndeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{8}
}

func (x *UndeleteUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the user whose email to update.
	// Format: users/{email}
	// Note: This is the current (old) email address. The new email is specified in the 'email' field.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The new email address.
	Email         string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailRequest) Reset() {
	*x = UpdateEmailRequest{}
	mi := &file_v1_user_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailRequest) ProtoMessage() {}

func (x *UpdateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateEmailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ChangePasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format: users/{email}. Must be the caller's own name.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NewPassword   string `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_v1_user_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{10}
}

func (x *ChangePasswordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type StartMFAEnrollmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format: users/{email}. Must be the caller's own name.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMFAEnrollmentRequest) Reset() {
	*x = StartMFAEnrollmentRequest{}
	mi := &file_v1_user_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMFAEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMFAEnrollmentRequest) ProtoMessage() {}

func (x *StartMFAEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMFAEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*StartMFAEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{11}
}

func (x *StartMFAEnrollmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartMFAEnrollmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The pending TOTP secret. The only response that carries it — it is never
	// readable from the User resource.
	OtpSecret string `protobuf:"bytes,1,opt,name=otp_secret,json=otpSecret,proto3" json:"otp_secret,omitempty"`
	// The pending recovery codes, shown once for the caller to save.
	RecoveryCodes []string `protobuf:"bytes,2,rep,name=recovery_codes,json=recoveryCodes,proto3" json:"recovery_codes,omitempty"`
	// When this enrollment stops being confirmable.
	ExpireTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMFAEnrollmentResponse) Reset() {
	*x = StartMFAEnrollmentResponse{}
	mi := &file_v1_user_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMFAEnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMFAEnrollmentResponse) ProtoMessage() {}

func (x *StartMFAEnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMFAEnrollmentResponse.ProtoReflect.Descriptor instead.
func (*StartMFAEnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{12}
}

func (x *StartMFAEnrollmentResponse) GetOtpSecret() string {
	if x != nil {
		return x.OtpSecret
	}
	return ""
}

func (x *StartMFAEnrollmentResponse) GetRecoveryCodes() []string {
	if x != nil {
		return x.RecoveryCodes
	}
	return nil
}

func (x *StartMFAEnrollmentResponse) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

type EnableMFARequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format: users/{email}. Must be the caller's own name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A code from the authenticator the pending secret was just added to.
	OtpCode       string `protobuf:"bytes,2,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableMFARequest) Reset() {
	*x = EnableMFARequest{}
	mi := &file_v1_user_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableMFARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableMFARequest) ProtoMessage() {}

func (x *EnableMFARequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableMFARequest.ProtoReflect.Descriptor instead.
func (*EnableMFARequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{13}
}

func (x *EnableMFARequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnableMFARequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

type DisableMFARequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format: users/{email}. The caller's own, or another user's with
	// bb.users.update.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableMFARequest) Reset() {
	*x = DisableMFARequest{}
	mi := &file_v1_user_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableMFARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableMFARequest) ProtoMessage() {}

func (x *DisableMFARequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableMFARequest.ProtoReflect.Descriptor instead.
func (*DisableMFARequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{14}
}

func (x *DisableMFARequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegenerateRecoveryCodesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format: users/{email}. Must be the caller's own name.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateRecoveryCodesRequest) Reset() {
	*x = RegenerateRecoveryCodesRequest{}
	mi := &file_v1_user_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateRecoveryCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateRecoveryCodesRequest) ProtoMessage() {}

func (x *RegenerateRecoveryCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateRecoveryCodesRequest.ProtoReflect.Descriptor instead.
func (*RegenerateRecoveryCodesRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{15}
}

func (x *RegenerateRecoveryCodesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegenerateRecoveryCodesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The pending recovery codes, shown once for the caller to save.
	RecoveryCodes []string `protobuf:"bytes,1,rep,name=recovery_codes,json=recoveryCodes,proto3" json:"recovery_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateRecoveryCodesResponse) Reset() {
	*x = RegenerateRecoveryCodesResponse{}
	mi := &file_v1_user_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateRecoveryCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateRecoveryCodesResponse) ProtoMessage() {}

func (x *RegenerateRecoveryCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateRecoveryCodesResponse.ProtoReflect.Descriptor instead.
func (*RegenerateRecoveryCodesResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{16}
}

func (x *RegenerateRecoveryCodesResponse) GetRecoveryCodes() []string {
	if x != nil {
		return x.RecoveryCodes
	}
	return nil
}

type ConfirmRecoveryCodesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format: users/{email}. Must be the caller's own name.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRecoveryCodesRequest) Reset() {
	*x = ConfirmRecoveryCodesRequest{}
	mi := &file_v1_user_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRecoveryCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRecoveryCodesRequest) ProtoMessage() {}

func (x *ConfirmRecoveryCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRecoveryCodesRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRecoveryCodesRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{17}
}

func (x *ConfirmRecoveryCodesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the user.
	// Format: users/{email}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The lifecycle state of the user account.
	State State `protobuf:"varint,2,opt,name=state,proto3,enum=bytebase.v1.State" json:"state,omitempty"`
	// The email address of the user, used for login and notifications.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// The display title or full name of the user.
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// The password for authentication. Only used during user creation or password updates.
	Password string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	// Whether the user has a live MFA factor. Set by ConfirmRecoveryCodes and
	// DisableMFA, never by an update.
	MfaEnabled bool `protobuf:"varint,8,opt,name=mfa_enabled,json=mfaEnabled,proto3" json:"mfa_enabled,omitempty"`
	// Should be a valid E.164 compliant phone number.
	// Could be empty.
	Phone string `protobuf:"bytes,12,opt,name=phone,proto3" json:"phone,omitempty"`
	// User profile metadata.
	Profile *User_Profile `protobuf:"bytes,13,opt,name=profile,proto3" json:"profile,omitempty"`
	// The groups for the user.
	// Format: groups/{email}
	Groups []string `protobuf:"bytes,14,rep,name=groups,proto3" json:"groups,omitempty"`
	// The current workspace.
	// Format: workspaces/{id}
	Workspace     string `protobuf:"bytes,16,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_user_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{18}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetMfaEnabled() bool {
	if x != nil {
		return x.MfaEnabled
	}
	return false
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetProfile() *User_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *User) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *User) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type User_Profile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The last time the user successfully logged in.
	LastLoginTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`
	// The last time the user changed their password.
	LastChangePasswordTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_change_password_time,json=lastChangePasswordTime,proto3" json:"last_change_password_time,omitempty"`
	// source means where the user comes from. For now we support Entra ID SCIM sync, so the source could be Entra ID.
	Source        string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User_Profile) Reset() {
	*x = User_Profile{}
	mi := &file_v1_user_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Profile) ProtoMessage() {}

func (x *User_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Profile.ProtoReflect.Descriptor instead.
func (*User_Profile) Descriptor() ([]byte, []int) {
	return file_v1_user_service_proto_rawDescGZIP(), []int{18, 0}
}

func (x *User_Profile) GetLastLoginTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginTime
	}
	return nil
}

func (x *User_Profile) GetLastChangePasswordTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastChangePasswordTime
	}
	return nil
}

func (x *User_Profile) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_v1_user_service_proto protoreflect.FileDescriptor

const file_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"\x15v1/user_service.proto\x12\vbytebase.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13v1/annotation.proto\x1a\x0fv1/common.proto\"?\n" +
	"\x0eGetUserRequest\x12-\n" +
	"\x04name\x18\x01 \x01(\tB\x19\xe0A\x02\xfaA\x13\n" +
	"\x11bytebase.com/UserR\x04name\"G\n" +
	"\x14BatchGetUsersRequest\x12/\n" +
	"\x05names\x18\x01 \x03(\tB\x19\xe0A\x02\xfaA\x13\n" +
	"\x11bytebase.com/UserR\x05names\"@\n" +
	"\x15BatchGetUsersResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.bytebase.v1.UserR\x05users\"\x89\x01\n" +
	"\x10ListUsersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12!\n" +
	"\fshow_deleted\x18\x03 \x01(\bR\vshowDeleted\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"d\n" +
	"\x11ListUsersResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.bytebase.v1.UserR\x05users\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"?\n" +
	"\x11CreateUserRequest\x12*\n" +
	"\x04user\x18\x01 \x01(\v2\x11.bytebase.v1.UserB\x03\xe0A\x02R\x04user\"\xf4\x01\n" +
	"\x11UpdateUserRequest\x12*\n" +
	"\x04user\x18\x01 \x01(\v2\x11.bytebase.v1.UserB\x03\xe0A\x02R\x04user\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12#\n" +
	"\rallow_missing\x18\x06 \x01(\bR\fallowMissingJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\botp_codeR\x1aregenerate_temp_mfa_secretR\x19regenerate_recovery_codes\"B\n" +
	"\x11DeleteUserRequest\x12-\n" +
	"\x04name\x18\x01 \x01(\tB\x19\xe0A\x02\xfaA\x13\n" +
	"\x11bytebase.com/UserR\x04name\"D\n" +
	"\x13UndeleteUserRequest\x12-\n" +
	"\x04name\x18\x01 \x01(\tB\x19\xe0A\x02\xfaA\x13\n" +
	"\x11bytebase.com/UserR\x04name\"f\n" +
	"\x12UpdateEmailRequest\x12-\n" +
	"\x04name\x18\x01 \x01(\tB\x19\xe0A\x02\xfaA\x13\n" +
	"\x11bytebase.com/UserR\x04name\x12!\n" +
	"\x05email\x18\x02 \x01(\tB\v\xe0A\x02\xbaH\x05r\x03\x18\xfe\x01R\x05email\"\x81\x01\n" +
	"\x15ChangePasswordRequest\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\xe0A\x02\xfaA\x13\n" +
	"\x11bytebase.com/User\xbaH\x05r\x03\x18\x84\x02R\x04name\x121\n" +
	"\fnew_password\x18\x02 \x01(\tB\x0e\xe0A\x02\xbaH\x04r\x02(H\xd0\xea0\x01R\vnewPassword\"R\n" +
	"\x19StartMFAEnrollmentRequest\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\xe0A\x02\xfaA\x13\n" +
	"\x11bytebase.com/User\xbaH\x05r\x03\x18\x84\x02R\x04name\"\xab\x01\n" +
	"\x1aStartMFAEnrollmentResponse\x12#\n" +
	"\n" +
	"otp_secret\x18\x01 \x01(\tB\x04\xd0\xea0\x01R\totpSecret\x12+\n" +
	"\x0erecovery_codes\x18\x02 \x03(\tB\x04\xd0\xea0\x01R\rrecoveryCodes\x12;\n" +
	"\vexpire_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireTime\"t\n" +
	"\x10EnableMFARequest\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\xe0A\x02\xfaA\x13\n" +
	"\x11bytebase.com/User\xbaH\x05r\x03\x18\x84\x02R\x04name\x12)\n" +
	"\botp_code\x18\x02 \x01(\tB\x0e\xe0A\x02\xbaH\x04r\x02\x18@\xd0\xea0\x01R\aotpCode\"J\n" +
	"\x11DisableMFARequest\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\xe0A\x02\xfaA\x13\n" +
	"\x11bytebase.com/User\xbaH\x05r\x03\x18\x84\x02R\x04name\"W\n" +
	"\x1eRegenerateRecoveryCodesRequest\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\xe0A\x02\xfaA\x13\n" +
	"\x11bytebase.com/User\xbaH\x05r\x03\x18\x84\x02R\x04name\"N\n" +
	"\x1fRegenerateRecoveryCodesResponse\x12+\n" +
	"\x0erecovery_codes\x18\x01 \x03(\tB\x04\xd0\xea0\x01R\rrecoveryCodes\"T\n" +
	"\x1bConfirmRecoveryCodesRequest\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\xe0A\x02\xfaA\x13\n" +
	"\x11bytebase.com/User\xbaH\x05r\x03\x18\x84\x02R\x04name\"\xc4\x05\n" +
	"\x04User\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12(\n" +
	"\x05state\x18\x02 \x01(\x0e2\x12.bytebase.v1.StateR\x05state\x12\x1e\n" +
	"\x05email\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xfe\x01R\x05email\x12\x1e\n" +
	"\x05title\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\xc8\x01R\x05title\x12*\n" +
	"\bpassword\x18\x06 \x01(\tB\x0e\xe0A\x04\xbaH\x04r\x02(H\xd0\xea0\x01R\bpassword\x12$\n" +
	"\vmfa_enabled\x18\b \x01(\bB\x03\xe0A\x03R\n" +
	"mfaEnabled\x12\x1a\n" +
	"\x05phone\x18\f \x01(\tB\x04\xd0\xea0\x02R\x05phone\x129\n" +
	"\aprofile\x18\r \x01(\v2\x19.bytebase.v1.User.ProfileB\x04\xd0\xea0\x02R\aprofile\x12\x1f\n" +
	"\x06groups\x18\x0e \x03(\tB\a\xe0A\x03\xd0\xea0\x02R\x06groups\x12!\n" +
	"\tworkspace\x18\x10 \x01(\tB\x03\xe0A\x03R\tworkspace\x1a\xbc\x01\n" +
	"\aProfile\x12B\n" +
	"\x0flast_login_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\rlastLoginTime\x12U\n" +
	"\x19last_change_password_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x16lastChangePasswordTime\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source:%\xeaA\"\n" +
	"\x11bytebase.com/User\x12\rusers/{email}J\x04\b\x05\x10\x06J\x04\b\a\x10\bJ\x04\b\x0f\x10\x10J\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fR\x0ftemp_otp_secretR\x13temp_recovery_codesR\x1ctemp_otp_secret_created_time2\xe7\x10\n" +
	"\vUserService\x12x\n" +
	"\aGetUser\x12\x1b.bytebase.v1.GetUserRequest\x1a\x11.bytebase.v1.User\"=\xdaA\x04name\x8a\xea0\fbb.users.get\x90\xea0\x01\xa0\xea0\x04\xa8\xea0\t\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/{name=users/*}\x12\x8e\x01\n" +
	"\rBatchGetUsers\x12!.bytebase.v1.BatchGetUsersRequest\x1a\".bytebase.v1.BatchGetUsersResponse\"6\x8a\xea0\fbb.users.get\x90\xea0\x01\xa0\xea0\x04\xa8\xea0\t\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/users:batchGet\x12]\n" +
	"\x0eGetCurrentUser\x12\x16.google.protobuf.Empty\x1a\x11.bytebase.v1.User\" \x80\xea0\x01\x90\xea0\x02\xa0\xea0\x01\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/users/me\x12\x83\x01\n" +
	"\tListUsers\x12\x1d.bytebase.v1.ListUsersRequest\x1a\x1e.bytebase.v1.ListUsersResponse\"7\xdaA\x06parent\x8a\xea0\rbb.users.list\x90\xea0\x01\xa0\xea0\x04\xa8\xea0\t\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12\x82\x01\n" +
	"\n" +
	"CreateUser\x12\x1e.bytebase.v1.CreateUserRequest\x1a\x11.bytebase.v1.User\"A\xdaA\x04user\x8a\xea0\x0fbb.users.create\x90\xea0\x01\x98\xea0\x01\xa0\xea0\x03\xa8\xea0\x06\x82\xd3\xe4\x93\x02\x11:\x04user\"\t/v1/users\x12\x89\x01\n" +
	"\n" +
	"UpdateUser\x12\x1e.bytebase.v1.UpdateUserRequest\x1a\x11.bytebase.v1.User\"H\xdaA\x10user,update_mask\x90\xea0\x02\x98\xea0\x01\xa0\xea0\x03\xa8\xea0\x03\x82\xd3\xe4\x93\x02\x1f:\x04user2\x17/v1/{user.name=users/*}\x12w\n" +
	"\n" +
	"DeleteUser\x12\x1e.bytebase.v1.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"1\xdaA\x04name\x90\xea0\x02\x98\xea0\x01\xa0\xea0\x04\xa8\xea0\t\x82\xd3\xe4\x93\x02\x14*\x12/v1/{name=users/*}\x12{\n" +
	"\fUndeleteUser\x12 .bytebase.v1.UndeleteUserRequest\x1a\x11.bytebase.v1.User\"6\x90\xea0\x02\x98\xea0\x01\xa0\xea0\x04\xa8\xea0\t\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/{name=users/*}:undelete\x12\xa1\x01\n" +
	"\vUpdateEmail\x12\x1f.bytebase.v1.UpdateEmailRequest\x1a\x11.bytebase.v1.User\"^\xdaA\n" +
	"name,email\x8a\xea0\x14bb.users.updateEmail\x90\xea0\x01\x98\xea0\x01\xa0\xea0\x03\xa8\xea0\x06\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/{name=users/*}:updateEmail\x12\x99\x01\n" +
	"\x0eChangePassword\x12\".bytebase.v1.ChangePasswordRequest\x1a\x11.bytebase.v1.User\"P\xdaA\x11name,new_password\x90\xea0\x02\x98\xea0\x01\xa0\xea0\x03\xa8\xea0\x02\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/{name=users/*}:changePassword\x12\xae\x01\n" +
	"\x12StartMFAEnrollment\x12&.bytebase.v1.StartMFAEnrollmentRequest\x1a'.bytebase.v1.StartMFAEnrollmentResponse\"G\xdaA\x04name\x90\xea0\x02\x98\xea0\x01\xa0\xea0\x03\xa8\xea0\x01\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/{name=users/*}:startMFAEnrollment\x12\x86\x01\n" +
	"\tEnableMFA\x12\x1d.bytebase.v1.EnableMFARequest\x1a\x11.bytebase.v1.User\"G\xdaA\rname,otp_code\x90\xea0\x02\x98\xea0\x01\xa0\xea0\x03\xa8\xea0\x01\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/{name=users/*}:enableMFA\x12\x80\x01\n" +
	"\n" +
	"DisableMFA\x12\x1e.bytebase.v1.DisableMFARequest\x1a\x11.bytebase.v1.User\"?\xdaA\x04name\x90\xea0\x02\x98\xea0\x01\xa0\xea0\x03\xa8\xea0\x02\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/{name=users/*}:disableMFA\x12\xc2\x01\n" +
	"\x17RegenerateRecoveryCodes\x12+.bytebase.v1.RegenerateRecoveryCodesRequest\x1a,.bytebase.v1.RegenerateRecoveryCodesResponse\"L\xdaA\x04name\x90\xea0\x02\x98\xea0\x01\xa0\xea0\x03\xa8\xea0\x01\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/{name=users/*}:regenerateRecoveryCodes\x12\x9e\x01\n" +
	"\x14ConfirmRecoveryCodes\x12(.bytebase.v1.ConfirmRecoveryCodesRequest\x1a\x11.bytebase.v1.User\"I\xdaA\x04name\x90\xea0\x02\x98\xea0\x01\xa0\xea0\x03\xa8\xea0\x01\x82\xd3\xe4\x93\x02,:\x01*\"'/v1/{name=users/*}:confirmRecoveryCodesB\xa6\x01\n" +
	"\x0fcom.bytebase.v1B\x10UserServiceProtoP\x01Z4github.com/bytebase/bytebase/backend/generated-go/v1\xa2\x02\x03BXX\xaa\x02\vBytebase.V1\xca\x02\vBytebase\\V1\xe2\x02\x17Bytebase\\V1\\GPBMetadata\xea\x02\fBytebase::V1b\x06proto3"

var (
	file_v1_user_service_proto_rawDescOnce sync.Once
	file_v1_user_service_proto_rawDescData []byte
)

func file_v1_user_service_proto_rawDescGZIP() []byte {
	file_v1_user_service_proto_rawDescOnce.Do(func() {
		file_v1_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_service_proto_rawDesc), len(file_v1_user_service_proto_rawDesc)))
	})
	return file_v1_user_service_proto_rawDescData
}

var file_v1_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_v1_user_service_proto_goTypes = []any{
	(*GetUserRequest)(nil),                  // 0: bytebase.v1.GetUserRequest
	(*BatchGetUsersRequest)(nil),            // 1: bytebase.v1.BatchGetUsersRequest
	(*BatchGetUsersResponse)(nil),           // 2: bytebase.v1.BatchGetUsersResponse
	(*ListUsersRequest)(nil),                // 3: bytebase.v1.ListUsersRequest
	(*ListUsersResponse)(nil),               // 4: bytebase.v1.ListUsersResponse
	(*CreateUserRequest)(nil),               // 5: bytebase.v1.CreateUserRequest
	(*UpdateUserRequest)(nil),               // 6: bytebase.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),               // 7: bytebase.v1.DeleteUserRequest
	(*UndeleteUserRequest)(nil),             // 8: bytebase.v1.UndeleteUserRequest
	(*UpdateEmailRequest)(nil),              // 9: bytebase.v1.UpdateEmailRequest
	(*ChangePasswordRequest)(nil),           // 10: bytebase.v1.ChangePasswordRequest
	(*StartMFAEnrollmentRequest)(nil),       // 11: bytebase.v1.StartMFAEnrollmentRequest
	(*StartMFAEnrollmentResponse)(nil),      // 12: bytebase.v1.StartMFAEnrollmentResponse
	(*EnableMFARequest)(nil),                // 13: bytebase.v1.EnableMFARequest
	(*DisableMFARequest)(nil),               // 14: bytebase.v1.DisableMFARequest
	(*RegenerateRecoveryCodesRequest)(nil),  // 15: bytebase.v1.RegenerateRecoveryCodesRequest
	(*RegenerateRecoveryCodesResponse)(nil), // 16: bytebase.v1.RegenerateRecoveryCodesResponse
	(*ConfirmRecoveryCodesRequest)(nil),     // 17: bytebase.v1.ConfirmRecoveryCodesRequest
	(*User)(nil),                            // 18: bytebase.v1.User
	(*User_Profile)(nil),                    // 19: bytebase.v1.User.Profile
	(*fieldmaskpb.FieldMask)(nil),           // 20: google.protobuf.FieldMask
	(*timestamppb.Timestamp)(nil),           // 21: google.protobuf.Timestamp
	(State)(0),                              // 22: bytebase.v1.State
	(*emptypb.Empty)(nil),                   // 23: google.protobuf.Empty
}
var file_v1_user_service_proto_depIdxs = []int32{
	18, // 0: bytebase.v1.BatchGetUsersResponse.users:type_name -> bytebase.v1.User
	18, // 1: bytebase.v1.ListUsersResponse.users:type_name -> bytebase.v1.User
	18, // 2: bytebase.v1.CreateUserRequest.user:type_name -> bytebase.v1.User
	18, // 3: bytebase.v1.UpdateUserRequest.user:type_name -> bytebase.v1.User
	20, // 4: bytebase.v1.UpdateUserRequest.update_mask:type_name -> google.protobuf.FieldMask
	21, // 5: bytebase.v1.StartMFAEnrollmentResponse.expire_time:type_name -> google.protobuf.Timestamp
	22, // 6: bytebase.v1.User.state:type_name -> bytebase.v1.State
	19, // 7: bytebase.v1.User.profile:type_name -> bytebase.v1.User.Profile
	21, // 8: bytebase.v1.User.Profile.last_login_time:type_name -> google.protobuf.Timestamp
	21, // 9: bytebase.v1.User.Profile.last_change_password_time:type_name -> google.protobuf.Timestamp
	0,  // 10: bytebase.v1.UserService.GetUser:input_type -> bytebase.v1.GetUserRequest
	1,  // 11: bytebase.v1.UserService.BatchGetUsers:input_type -> bytebase.v1.BatchGetUsersRequest
	23, // 12: bytebase.v1.UserService.GetCurrentUser:input_type -> google.protobuf.Empty
	3,  // 13: bytebase.v1.UserService.ListUsers:input_type -> bytebase.v1.ListUsersRequest
	5,  // 14: bytebase.v1.UserService.CreateUser:input_type -> bytebase.v1.CreateUserRequest
	6,  // 15: bytebase.v1.UserService.UpdateUser:input_type -> bytebase.v1.UpdateUserRequest
	7,  // 16: bytebase.v1.UserService.DeleteUser:input_type -> bytebase.v1.DeleteUserRequest
	8,  // 17: bytebase.v1.UserService.UndeleteUser:input_type -> bytebase.v1.UndeleteUserRequest
	9,  // 18: bytebase.v1.UserService.UpdateEmail:input_type -> bytebase.v1.UpdateEmailRequest
	10, // 19: bytebase.v1.UserService.ChangePassword:input_type -> bytebase.v1.ChangePasswordRequest
	11, // 20: bytebase.v1.UserService.StartMFAEnrollment:input_type -> bytebase.v1.StartMFAEnrollmentRequest
	13, // 21: bytebase.v1.UserService.EnableMFA:input_type -> bytebase.v1.EnableMFARequest
	14, // 22: bytebase.v1.UserService.DisableMFA:input_type -> bytebase.v1.DisableMFARequest
	15, // 23: bytebase.v1.UserService.RegenerateRecoveryCodes:input_type -> bytebase.v1.RegenerateRecoveryCodesRequest
	17, // 24: bytebase.v1.UserService.ConfirmRecoveryCodes:input_type -> bytebase.v1.ConfirmRecoveryCodesRequest
	18, // 25: bytebase.v1.UserService.GetUser:output_type -> bytebase.v1.User
	2,  // 26: bytebase.v1.UserService.BatchGetUsers:output_type -> bytebase.v1.BatchGetUsersResponse
	18, // 27: bytebase.v1.UserService.GetCurrentUser:output_type -> bytebase.v1.User
	4,  // 28: bytebase.v1.UserService.ListUsers:output_type -> bytebase.v1.ListUsersResponse
	18, // 29: bytebase.v1.UserService.CreateUser:output_type -> bytebase.v1.User
	18, // 30: bytebase.v1.UserService.UpdateUser:output_type -> bytebase.v1.User
	23, // 31: bytebase.v1.UserService.DeleteUser:output_type -> google.protobuf.Empty
	18, // 32: bytebase.v1.UserService.UndeleteUser:output_type -> bytebase.v1.User
	18, // 33: bytebase.v1.UserService.UpdateEmail:output_type -> bytebase.v1.User
	18, // 34: bytebase.v1.UserService.ChangePassword:output_type -> bytebase.v1.User
	12, // 35: bytebase.v1.UserService.StartMFAEnrollment:output_type -> bytebase.v1.StartMFAEnrollmentResponse
	18, // 36: bytebase.v1.UserService.EnableMFA:output_type -> bytebase.v1.User
	18, // 37: bytebase.v1.UserService.DisableMFA:output_type -> bytebase.v1.User
	16, // 38: bytebase.v1.UserService.RegenerateRecoveryCodes:output_type -> bytebase.v1.RegenerateRecoveryCodesResponse
	18, // 39: bytebase.v1.UserService.ConfirmRecoveryCodes:output_type -> bytebase.v1.User
	25, // [25:40] is the sub-list for method output_type
	10, // [10:25] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_user_service_proto_init() }
func file_v1_user_service_proto_init() {
	if File_v1_user_service_proto != nil {
		return
	}
	file_v1_annotation_proto_init()
	file_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_service_proto_rawDesc), len(file_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_service_proto_goTypes,
		DependencyIndexes: file_v1_user_service_proto_depIdxs,
		MessageInfos:      file_v1_user_service_proto_msgTypes,
	}.Build()
	File_v1_user_service_proto = out.File
	file_v1_user_service_proto_goTypes = nil
	file_v1_user_service_proto_depIdxs = nil
}
