// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: v1/worksheet_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Worksheet_Visibility int32

const (
	Worksheet_VISIBILITY_UNSPECIFIED Worksheet_Visibility = 0
	// Read access in project scope, worksheet OWNER/DBA and project OWNER can read/write, other project members can read.
	Worksheet_PROJECT_READ Worksheet_Visibility = 1
	// Write access in project scope, worksheet OWNER/DBA and all members in the project can write the worksheet.
	Worksheet_PROJECT_WRITE Worksheet_Visibility = 2
	// Private, only worksheet OWNER can read/write.
	Worksheet_PRIVATE Worksheet_Visibility = 3
)

// Enum value maps for Worksheet_Visibility.
var (
	Worksheet_Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "PROJECT_READ",
		2: "PROJECT_WRITE",
		3: "PRIVATE",
	}
	Worksheet_Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"PROJECT_READ":           1,
		"PROJECT_WRITE":          2,
		"PRIVATE":                3,
	}
)

func (x Worksheet_Visibility) Enum() *Worksheet_Visibility {
	p := new(Worksheet_Visibility)
	*p = x
	return p
}

func (x Worksheet_Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Worksheet_Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_worksheet_service_proto_enumTypes[0].Descriptor()
}

func (Worksheet_Visibility) Type() protoreflect.EnumType {
	return &file_v1_worksheet_service_proto_enumTypes[0]
}

func (x Worksheet_Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Worksheet_Visibility.Descriptor instead.
func (Worksheet_Visibility) EnumDescriptor() ([]byte, []int) {
	return file_v1_worksheet_service_proto_rawDescGZIP(), []int{8, 0}
}

type CreateWorksheetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The worksheet to create.
	Worksheet     *Worksheet `protobuf:"bytes,1,opt,name=worksheet,proto3" json:"worksheet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorksheetRequest) Reset() {
	*x = CreateWorksheetRequest{}
	mi := &file_v1_worksheet_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorksheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorksheetRequest) ProtoMessage() {}

func (x *CreateWorksheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_worksheet_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorksheetRequest.ProtoReflect.Descriptor instead.
func (*CreateWorksheetRequest) Descriptor() ([]byte, []int) {
	return file_v1_worksheet_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorksheetRequest) GetWorksheet() *Worksheet {
	if x != nil {
		return x.Worksheet
	}
	return nil
}

type GetWorksheetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the worksheet to retrieve.
	// Format: worksheets/{worksheet}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorksheetRequest) Reset() {
	*x = GetWorksheetRequest{}
	mi := &file_v1_worksheet_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorksheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorksheetRequest) ProtoMessage() {}

func (x *GetWorksheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_worksheet_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorksheetRequest.ProtoReflect.Descriptor instead.
func (*GetWorksheetRequest) Descriptor() ([]byte, []int) {
	return file_v1_worksheet_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetWorksheetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateWorksheetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The worksheet to update.
	//
	// The worksheet's `name` field is used to identify the worksheet to update.
	// Format: worksheets/{worksheet}
	Worksheet *Worksheet `protobuf:"bytes,1,opt,name=worksheet,proto3" json:"worksheet,omitempty"`
	// The list of fields to be updated.
	// Fields are specified relative to the worksheet.
	// (e.g. `title`, `statement`; *not* `worksheet.title` or `worksheet.statement`)
	// Only support update the following fields for now:
	// - `title`
	// - `statement`
	// - `starred`
	// - `visibility`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorksheetRequest) Reset() {
	*x = UpdateWorksheetRequest{}
	mi := &file_v1_worksheet_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorksheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorksheetRequest) ProtoMessage() {}

func (x *UpdateWorksheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_worksheet_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorksheetRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorksheetRequest) Descriptor() ([]byte, []int) {
	return file_v1_worksheet_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateWorksheetRequest) GetWorksheet() *Worksheet {
	if x != nil {
		return x.Worksheet
	}
	return nil
}

func (x *UpdateWorksheetRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateWorksheetOrganizerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organizer to update.
	//
	// The organizer's `worksheet` field is used to identify the worksheet.
	// Format: worksheets/{worksheet}
	Organizer *WorksheetOrganizer `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`
	// The list of fields to be updated.
	// Fields are specified relative to the worksheet organizer.
	// Only support update the following fields for now:
	// - `starred`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorksheetOrganizerRequest) Reset() {
	*x = UpdateWorksheetOrganizerRequest{}
	mi := &file_v1_worksheet_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorksheetOrganizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorksheetOrganizerRequest) ProtoMessage() {}

func (x *UpdateWorksheetOrganizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_worksheet_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorksheetOrganizerRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorksheetOrganizerRequest) Descriptor() ([]byte, []int) {
	return file_v1_worksheet_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWorksheetOrganizerRequest) GetOrganizer() *WorksheetOrganizer {
	if x != nil {
		return x.Organizer
	}
	return nil
}

func (x *UpdateWorksheetOrganizerRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type WorksheetOrganizer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the worksheet.
	// Format: worksheets/{worksheet}
	Worksheet string `protobuf:"bytes,1,opt,name=worksheet,proto3" json:"worksheet,omitempty"`
	// starred means if the worksheet is starred.
	Starred       bool `protobuf:"varint,2,opt,name=starred,proto3" json:"starred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorksheetOrganizer) Reset() {
	*x = WorksheetOrganizer{}
	mi := &file_v1_worksheet_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorksheetOrganizer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorksheetOrganizer) ProtoMessage() {}

func (x *WorksheetOrganizer) ProtoReflect() protoreflect.Message {
	mi := &file_v1_worksheet_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorksheetOrganizer.ProtoReflect.Descriptor instead.
func (*WorksheetOrganizer) Descriptor() ([]byte, []int) {
	return file_v1_worksheet_service_proto_rawDescGZIP(), []int{4}
}

func (x *WorksheetOrganizer) GetWorksheet() string {
	if x != nil {
		return x.Worksheet
	}
	return ""
}

func (x *WorksheetOrganizer) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

type DeleteWorksheetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the worksheet to delete.
	// Format: worksheets/{worksheet}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorksheetRequest) Reset() {
	*x = DeleteWorksheetRequest{}
	mi := &file_v1_worksheet_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorksheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorksheetRequest) ProtoMessage() {}

func (x *DeleteWorksheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_worksheet_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorksheetRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorksheetRequest) Descriptor() ([]byte, []int) {
	return file_v1_worksheet_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWorksheetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchWorksheetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// To filter the search result.
	// The syntax and semantics of CEL are documented at https://github.com/google/cel-spec
	//
	// Supported filter:
	// - creator: the worksheet creator in "users/{email}" format, support "==" and "!=" operator.
	// - starred: should be "true" or "false", filter starred/unstarred sheets, support "==" operator.
	// - visibility: check Visibility enum in the Worksheet message for values, support "==" and "in [xx]" operator.
	//
	// For example:
	// creator == "users/{email}"
	// creator != "users/{email}"
	// starred == true
	// starred == false
	// visibility in ["PRIVATE", "PROJECT_READ", "PROJECT_WRITE"]
	// visibility == "PRIVATE"
	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// Not used.
	// The maximum number of worksheets to return. The service may return fewer than
	// this value.
	// If unspecified, at most 10 worksheets will be returned.
	// The maximum value is 1000; values above 1000 will be coerced to 1000.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Not used.
	// A page token, received from a previous `SearchWorksheets` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `SearchWorksheets` must match
	// the call that provided the page token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchWorksheetsRequest) Reset() {
	*x = SearchWorksheetsRequest{}
	mi := &file_v1_worksheet_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchWorksheetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchWorksheetsRequest) ProtoMessage() {}

func (x *SearchWorksheetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_worksheet_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchWorksheetsRequest.ProtoReflect.Descriptor instead.
func (*SearchWorksheetsRequest) Descriptor() ([]byte, []int) {
	return file_v1_worksheet_service_proto_rawDescGZIP(), []int{6}
}

func (x *SearchWorksheetsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *SearchWorksheetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchWorksheetsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type SearchWorksheetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The worksheets that matched the search criteria.
	Worksheets []*Worksheet `protobuf:"bytes,1,rep,name=worksheets,proto3" json:"worksheets,omitempty"`
	// Not used. A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchWorksheetsResponse) Reset() {
	*x = SearchWorksheetsResponse{}
	mi := &file_v1_worksheet_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchWorksheetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchWorksheetsResponse) ProtoMessage() {}

func (x *SearchWorksheetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_worksheet_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchWorksheetsResponse.ProtoReflect.Descriptor instead.
func (*SearchWorksheetsResponse) Descriptor() ([]byte, []int) {
	return file_v1_worksheet_service_proto_rawDescGZIP(), []int{7}
}

func (x *SearchWorksheetsResponse) GetWorksheets() []*Worksheet {
	if x != nil {
		return x.Worksheets
	}
	return nil
}

func (x *SearchWorksheetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Worksheet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the worksheet resource, generated by the server.
	// Canonical parent is project.
	// Format: worksheets/{worksheet}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The project resource name.
	// Format: projects/{project}
	Project string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	// The database resource name.
	// Format: instances/{instance}/databases/{database}
	// If the database parent doesn't exist, the database field is empty.
	Database string `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	// The title of the worksheet.
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// The creator of the Worksheet.
	// Format: users/{email}
	Creator string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	// The create time of the worksheet.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last update time of the worksheet.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// The content of the worksheet.
	// By default, it will be cut off in SearchWorksheet() method. If it doesn't match the `content_size`, you can
	// use GetWorksheet() request to retrieve the full content.
	Content []byte `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	// content_size is the full size of the content, may not match the size of the `content` field.
	ContentSize int64                `protobuf:"varint,9,opt,name=content_size,json=contentSize,proto3" json:"content_size,omitempty"`
	Visibility  Worksheet_Visibility `protobuf:"varint,10,opt,name=visibility,proto3,enum=bytebase.v1.Worksheet_Visibility" json:"visibility,omitempty"`
	// starred indicates whether the worksheet is starred by the current authenticated user.
	Starred       bool `protobuf:"varint,11,opt,name=starred,proto3" json:"starred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worksheet) Reset() {
	*x = Worksheet{}
	mi := &file_v1_worksheet_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worksheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worksheet) ProtoMessage() {}

func (x *Worksheet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_worksheet_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worksheet.ProtoReflect.Descriptor instead.
func (*Worksheet) Descriptor() ([]byte, []int) {
	return file_v1_worksheet_service_proto_rawDescGZIP(), []int{8}
}

func (x *Worksheet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Worksheet) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Worksheet) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Worksheet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Worksheet) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Worksheet) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Worksheet) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Worksheet) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Worksheet) GetContentSize() int64 {
	if x != nil {
		return x.ContentSize
	}
	return 0
}

func (x *Worksheet) GetVisibility() Worksheet_Visibility {
	if x != nil {
		return x.Visibility
	}
	return Worksheet_VISIBILITY_UNSPECIFIED
}

func (x *Worksheet) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

var File_v1_worksheet_service_proto protoreflect.FileDescriptor

const file_v1_worksheet_service_proto_rawDesc = "" +
	"\n" +
	"\x1av1/worksheet_service.proto\x12\vbytebase.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13v1/annotation.proto\"S\n" +
	"\x16CreateWorksheetRequest\x129\n" +
	"\tworksheet\x18\x01 \x01(\v2\x16.bytebase.v1.WorksheetB\x03\xe0A\x02R\tworksheet\".\n" +
	"\x13GetWorksheetRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"\x90\x01\n" +
	"\x16UpdateWorksheetRequest\x129\n" +
	"\tworksheet\x18\x01 \x01(\v2\x16.bytebase.v1.WorksheetB\x03\xe0A\x02R\tworksheet\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\xa2\x01\n" +
	"\x1fUpdateWorksheetOrganizerRequest\x12B\n" +
	"\torganizer\x18\x01 \x01(\v2\x1f.bytebase.v1.WorksheetOrganizerB\x03\xe0A\x02R\torganizer\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"Q\n" +
	"\x12WorksheetOrganizer\x12!\n" +
	"\tworksheet\x18\x01 \x01(\tB\x03\xe0A\x02R\tworksheet\x12\x18\n" +
	"\astarred\x18\x02 \x01(\bR\astarred\"1\n" +
	"\x16DeleteWorksheetRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"m\n" +
	"\x17SearchWorksheetsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"z\n" +
	"\x18SearchWorksheetsResponse\x126\n" +
	"\n" +
	"worksheets\x18\x01 \x03(\v2\x16.bytebase.v1.WorksheetR\n" +
	"worksheets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xaa\x04\n" +
	"\tWorksheet\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xe0A\x02\xe0A\x05R\x04name\x12\x1d\n" +
	"\aproject\x18\x02 \x01(\tB\x03\xe0A\x02R\aproject\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x19\n" +
	"\x05title\x18\x04 \x01(\tB\x03\xe0A\x02R\x05title\x12\x1d\n" +
	"\acreator\x18\x05 \x01(\tB\x03\xe0A\x03R\acreator\x12@\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x12\x1d\n" +
	"\acontent\x18\b \x01(\fB\x03\xe0A\x02R\acontent\x12&\n" +
	"\fcontent_size\x18\t \x01(\x03B\x03\xe0A\x03R\vcontentSize\x12F\n" +
	"\n" +
	"visibility\x18\n" +
	" \x01(\x0e2!.bytebase.v1.Worksheet.VisibilityB\x03\xe0A\x02R\n" +
	"visibility\x12\x1d\n" +
	"\astarred\x18\v \x01(\bB\x03\xe0A\x03R\astarred\"Z\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROJECT_READ\x10\x01\x12\x11\n" +
	"\rPROJECT_WRITE\x10\x02\x12\v\n" +
	"\aPRIVATE\x10\x032\x87\a\n" +
	"\x10WorksheetService\x12\x88\x01\n" +
	"\x0fCreateWorksheet\x12#.bytebase.v1.CreateWorksheetRequest\x1a\x16.bytebase.v1.Worksheet\"8\xdaA\x10parent,worksheet\x90\xea0\x02\x82\xd3\xe4\x93\x02\x1b:\tworksheet\"\x0e/v1/worksheets\x12t\n" +
	"\fGetWorksheet\x12 .bytebase.v1.GetWorksheetRequest\x1a\x16.bytebase.v1.Worksheet\"*\xdaA\x04name\x90\xea0\x02\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/{name=worksheets/*}\x12\x85\x01\n" +
	"\x10SearchWorksheets\x12$.bytebase.v1.SearchWorksheetsRequest\x1a%.bytebase.v1.SearchWorksheetsResponse\"$\x90\xea0\x02\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/worksheets:search\x12\xa0\x01\n" +
	"\x0fUpdateWorksheet\x12#.bytebase.v1.UpdateWorksheetRequest\x1a\x16.bytebase.v1.Worksheet\"P\xdaA\x15worksheet,update_mask\x90\xea0\x02\x82\xd3\xe4\x93\x02.:\tworksheet2!/v1/{worksheet.name=worksheets/*}\x12\xca\x01\n" +
	"\x18UpdateWorksheetOrganizer\x12,.bytebase.v1.UpdateWorksheetOrganizerRequest\x1a\x1f.bytebase.v1.WorksheetOrganizer\"_\xdaA\x15organizer,update_mask\x90\xea0\x02\x82\xd3\xe4\x93\x02=:\torganizer20/v1/{organizer.worksheet=worksheets/*}/organizer\x12z\n" +
	"\x0fDeleteWorksheet\x12#.bytebase.v1.DeleteWorksheetRequest\x1a\x16.google.protobuf.Empty\"*\xdaA\x04name\x90\xea0\x02\x82\xd3\xe4\x93\x02\x19*\x17/v1/{name=worksheets/*}B6Z4github.com/bytebase/bytebase/backend/generated-go/v1b\x06proto3"

var (
	file_v1_worksheet_service_proto_rawDescOnce sync.Once
	file_v1_worksheet_service_proto_rawDescData []byte
)

func file_v1_worksheet_service_proto_rawDescGZIP() []byte {
	file_v1_worksheet_service_proto_rawDescOnce.Do(func() {
		file_v1_worksheet_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_worksheet_service_proto_rawDesc), len(file_v1_worksheet_service_proto_rawDesc)))
	})
	return file_v1_worksheet_service_proto_rawDescData
}

var file_v1_worksheet_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_worksheet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_worksheet_service_proto_goTypes = []any{
	(Worksheet_Visibility)(0),               // 0: bytebase.v1.Worksheet.Visibility
	(*CreateWorksheetRequest)(nil),          // 1: bytebase.v1.CreateWorksheetRequest
	(*GetWorksheetRequest)(nil),             // 2: bytebase.v1.GetWorksheetRequest
	(*UpdateWorksheetRequest)(nil),          // 3: bytebase.v1.UpdateWorksheetRequest
	(*UpdateWorksheetOrganizerRequest)(nil), // 4: bytebase.v1.UpdateWorksheetOrganizerRequest
	(*WorksheetOrganizer)(nil),              // 5: bytebase.v1.WorksheetOrganizer
	(*DeleteWorksheetRequest)(nil),          // 6: bytebase.v1.DeleteWorksheetRequest
	(*SearchWorksheetsRequest)(nil),         // 7: bytebase.v1.SearchWorksheetsRequest
	(*SearchWorksheetsResponse)(nil),        // 8: bytebase.v1.SearchWorksheetsResponse
	(*Worksheet)(nil),                       // 9: bytebase.v1.Worksheet
	(*fieldmaskpb.FieldMask)(nil),           // 10: google.protobuf.FieldMask
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 12: google.protobuf.Empty
}
var file_v1_worksheet_service_proto_depIdxs = []int32{
	9,  // 0: bytebase.v1.CreateWorksheetRequest.worksheet:type_name -> bytebase.v1.Worksheet
	9,  // 1: bytebase.v1.UpdateWorksheetRequest.worksheet:type_name -> bytebase.v1.Worksheet
	10, // 2: bytebase.v1.UpdateWorksheetRequest.update_mask:type_name -> google.protobuf.FieldMask
	5,  // 3: bytebase.v1.UpdateWorksheetOrganizerRequest.organizer:type_name -> bytebase.v1.WorksheetOrganizer
	10, // 4: bytebase.v1.UpdateWorksheetOrganizerRequest.update_mask:type_name -> google.protobuf.FieldMask
	9,  // 5: bytebase.v1.SearchWorksheetsResponse.worksheets:type_name -> bytebase.v1.Worksheet
	11, // 6: bytebase.v1.Worksheet.create_time:type_name -> google.protobuf.Timestamp
	11, // 7: bytebase.v1.Worksheet.update_time:type_name -> google.protobuf.Timestamp
	0,  // 8: bytebase.v1.Worksheet.visibility:type_name -> bytebase.v1.Worksheet.Visibility
	1,  // 9: bytebase.v1.WorksheetService.CreateWorksheet:input_type -> bytebase.v1.CreateWorksheetRequest
	2,  // 10: bytebase.v1.WorksheetService.GetWorksheet:input_type -> bytebase.v1.GetWorksheetRequest
	7,  // 11: bytebase.v1.WorksheetService.SearchWorksheets:input_type -> bytebase.v1.SearchWorksheetsRequest
	3,  // 12: bytebase.v1.WorksheetService.UpdateWorksheet:input_type -> bytebase.v1.UpdateWorksheetRequest
	4,  // 13: bytebase.v1.WorksheetService.UpdateWorksheetOrganizer:input_type -> bytebase.v1.UpdateWorksheetOrganizerRequest
	6,  // 14: bytebase.v1.WorksheetService.DeleteWorksheet:input_type -> bytebase.v1.DeleteWorksheetRequest
	9,  // 15: bytebase.v1.WorksheetService.CreateWorksheet:output_type -> bytebase.v1.Worksheet
	9,  // 16: bytebase.v1.WorksheetService.GetWorksheet:output_type -> bytebase.v1.Worksheet
	8,  // 17: bytebase.v1.WorksheetService.SearchWorksheets:output_type -> bytebase.v1.SearchWorksheetsResponse
	9,  // 18: bytebase.v1.WorksheetService.UpdateWorksheet:output_type -> bytebase.v1.Worksheet
	5,  // 19: bytebase.v1.WorksheetService.UpdateWorksheetOrganizer:output_type -> bytebase.v1.WorksheetOrganizer
	12, // 20: bytebase.v1.WorksheetService.DeleteWorksheet:output_type -> google.protobuf.Empty
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_v1_worksheet_service_proto_init() }
func file_v1_worksheet_service_proto_init() {
	if File_v1_worksheet_service_proto != nil {
		return
	}
	file_v1_annotation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_worksheet_service_proto_rawDesc), len(file_v1_worksheet_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_worksheet_service_proto_goTypes,
		DependencyIndexes: file_v1_worksheet_service_proto_depIdxs,
		EnumInfos:         file_v1_worksheet_service_proto_enumTypes,
		MessageInfos:      file_v1_worksheet_service_proto_msgTypes,
	}.Build()
	File_v1_worksheet_service_proto = out.File
	file_v1_worksheet_service_proto_goTypes = nil
	file_v1_worksheet_service_proto_depIdxs = nil
}
