# Default values for bytebase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bytebase:
  option:
    host: 0.0.0.0
    port: 8080
    # You should set this to the URL where users visits Bytebase.
    # See https://www.bytebase.com/docs/get-started/install/external-url
    # external-url: https://bytebase.example.com
    pg: postgresql://user:secret@host:port/dbname
    data: /var/opt/bytebase
  version: 1.3.2
  storage: 2Gi
