// @generated by protoc-gen-es v2.12.0
// @generated from file v1/ai_service.proto (package bytebase.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../google/api/annotations_pb";
import { file_v1_annotation } from "./annotation_pb";

/**
 * Describes the file v1/ai_service.proto.
 */
export const file_v1_ai_service = /*@__PURE__*/
  fileDesc("ChN2MS9haV9zZXJ2aWNlLnByb3RvEgtieXRlYmFzZS52MSK8AQoNQUlDaGF0TWVzc2FnZRIsCgRyb2xlGAEgASgOMh4uYnl0ZWJhc2UudjEuQUlDaGF0TWVzc2FnZVJvbGUSFAoHY29udGVudBgCIAEoCUgAiAEBEi8KCnRvb2xfY2FsbHMYAyADKAsyGy5ieXRlYmFzZS52MS5BSUNoYXRUb29sQ2FsbBIZCgx0b29sX2NhbGxfaWQYBCABKAlIAYgBAUIKCghfY29udGVudEIPCg1fdG9vbF9jYWxsX2lkIlQKFEFJQ2hhdFRvb2xEZWZpbml0aW9uEgwKBG5hbWUYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkSGQoRcGFyYW1ldGVyc19zY2hlbWEYAyABKAkiYQoOQUlDaGF0VG9vbENhbGwSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIRCglhcmd1bWVudHMYAyABKAkSFQoIbWV0YWRhdGEYBCABKAlIAIgBAUILCglfbWV0YWRhdGEiegoNQUlDaGF0UmVxdWVzdBIsCghtZXNzYWdlcxgBIAMoCzIaLmJ5dGViYXNlLnYxLkFJQ2hhdE1lc3NhZ2USOwoQdG9vbF9kZWZpbml0aW9ucxgCIAMoCzIhLmJ5dGViYXNlLnYxLkFJQ2hhdFRvb2xEZWZpbml0aW9uIiMKC0FJQ2hhdFVzYWdlEhQKDHRvdGFsX3Rva2VucxgBIAEoBSKbAQoOQUlDaGF0UmVzcG9uc2USFAoHY29udGVudBgBIAEoCUgAiAEBEi8KCnRvb2xfY2FsbHMYAiADKAsyGy5ieXRlYmFzZS52MS5BSUNoYXRUb29sQ2FsbBIsCgV1c2FnZRgDIAEoCzIYLmJ5dGViYXNlLnYxLkFJQ2hhdFVzYWdlSAGIAQFCCgoIX2NvbnRlbnRCCAoGX3VzYWdlKrwBChFBSUNoYXRNZXNzYWdlUm9sZRIkCiBBSV9DSEFUX01FU1NBR0VfUk9MRV9VTlNQRUNJRklFRBAAEh8KG0FJX0NIQVRfTUVTU0FHRV9ST0xFX1NZU1RFTRABEh0KGUFJX0NIQVRfTUVTU0FHRV9ST0xFX1VTRVIQAhIiCh5BSV9DSEFUX01FU1NBR0VfUk9MRV9BU1NJU1RBTlQQAxIdChlBSV9DSEFUX01FU1NBR0VfUk9MRV9UT09MEAQyaAoJQUlTZXJ2aWNlElsKBENoYXQSGi5ieXRlYmFzZS52MS5BSUNoYXRSZXF1ZXN0GhsuYnl0ZWJhc2UudjEuQUlDaGF0UmVzcG9uc2UiGpDqMAKC0+STAhA6ASoiCy92MS9haS9jaGF0QqQBCg9jb20uYnl0ZWJhc2UudjFCDkFpU2VydmljZVByb3RvUAFaNGdpdGh1Yi5jb20vYnl0ZWJhc2UvYnl0ZWJhc2UvYmFja2VuZC9nZW5lcmF0ZWQtZ28vdjGiAgNCWFiqAgtCeXRlYmFzZS5WMcoCC0J5dGViYXNlXFYx4gIXQnl0ZWJhc2VcVjFcR1BCTWV0YWRhdGHqAgxCeXRlYmFzZTo6VjFiBnByb3RvMw", [file_google_api_annotations, file_v1_annotation]);

/**
 * Describes the message bytebase.v1.AIChatMessage.
 * Use `create(AIChatMessageSchema)` to create a new message.
 */
export const AIChatMessageSchema = /*@__PURE__*/
  messageDesc(file_v1_ai_service, 0);

/**
 * Describes the message bytebase.v1.AIChatToolDefinition.
 * Use `create(AIChatToolDefinitionSchema)` to create a new message.
 */
export const AIChatToolDefinitionSchema = /*@__PURE__*/
  messageDesc(file_v1_ai_service, 1);

/**
 * Describes the message bytebase.v1.AIChatToolCall.
 * Use `create(AIChatToolCallSchema)` to create a new message.
 */
export const AIChatToolCallSchema = /*@__PURE__*/
  messageDesc(file_v1_ai_service, 2);

/**
 * Describes the message bytebase.v1.AIChatRequest.
 * Use `create(AIChatRequestSchema)` to create a new message.
 */
export const AIChatRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_ai_service, 3);

/**
 * Describes the message bytebase.v1.AIChatUsage.
 * Use `create(AIChatUsageSchema)` to create a new message.
 */
export const AIChatUsageSchema = /*@__PURE__*/
  messageDesc(file_v1_ai_service, 4);

/**
 * Describes the message bytebase.v1.AIChatResponse.
 * Use `create(AIChatResponseSchema)` to create a new message.
 */
export const AIChatResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_ai_service, 5);

/**
 * Describes the enum bytebase.v1.AIChatMessageRole.
 */
export const AIChatMessageRoleSchema = /*@__PURE__*/
  enumDesc(file_v1_ai_service, 0);

/**
 * Role of a chat message.
 *
 * @generated from enum bytebase.v1.AIChatMessageRole
 */
export const AIChatMessageRole = /*@__PURE__*/
  tsEnum(AIChatMessageRoleSchema);

/**
 * AIService provides AI chat capabilities for the page agent.
 *
 * @generated from service bytebase.v1.AIService
 */
export const AIService = /*@__PURE__*/
  serviceDesc(file_v1_ai_service, 0);

