// @generated by protoc-gen-es v2.5.2
// @generated from file v1/common.proto (package bytebase.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/common.proto.
 */
export declare const file_v1_common: GenFile;

/**
 * Position in a text expressed as one-based line and one-based column.
 * We use 1-based numbering to match the majority of industry standards:
 * - Monaco Editor uses 1-based (https://microsoft.github.io/monaco-editor/typedoc/interfaces/IPosition.html)
 * - GitHub Actions uses 1-based (https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message)
 * - Most text editors display 1-based positions to users
 * Note: LSP uses 0-based (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#position),
 * but we follow the canonical user-facing standards.
 *
 * Handling unknown positions:
 * - If the entire position is unknown, leave this field as nil/undefined
 * - If only line is known, set line and leave column as 0 (e.g., line=5, column=0)
 * - If only column is known (rare), set column and leave line as 0
 * Frontends should check for nil/undefined/zero values and handle them appropriately.
 *
 * @generated from message bytebase.v1.Position
 */
export declare type Position = Message<"bytebase.v1.Position"> & {
  /**
   * Line position in a text (one-based).
   * First line of the text is line 1.
   * A value of 0 indicates the line information is unknown.
   *
   * @generated from field: int32 line = 1;
   */
  line: number;

  /**
   * Column position in a text (one-based).
   * Column is measured in Unicode code points (characters/runes), not bytes or grapheme clusters.
   * First character of the line is column 1.
   * A value of 0 indicates the column information is unknown.
   *
   * Examples:
   * - "SELECT * FROM t" - column 8 is '*'
   * - "SELECT 你好 FROM t" - column 8 is '你' (even though it's at byte offset 7)
   * - "SELECT 😀 FROM t" - column 8 is '😀' (even though it's 4 bytes in UTF-8)
   *
   * @generated from field: int32 column = 2;
   */
  column: number;
};

/**
 * Describes the message bytebase.v1.Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export declare const PositionSchema: GenMessage<Position>;

/**
 * Range represents a span within a text or sequence.
 * Whether the indices are byte offsets or character indices depends on the context.
 * Check the documentation of the field using Range for specific semantics.
 *
 * @generated from message bytebase.v1.Range
 */
export declare type Range = Message<"bytebase.v1.Range"> & {
  /**
   * Start index (inclusive).
   *
   * @generated from field: int32 start = 1;
   */
  start: number;

  /**
   * End index (exclusive).
   *
   * @generated from field: int32 end = 2;
   */
  end: number;
};

/**
 * Describes the message bytebase.v1.Range.
 * Use `create(RangeSchema)` to create a new message.
 */
export declare const RangeSchema: GenMessage<Range>;

/**
 * PermissionDeniedDetail provides structured information about permission failures.
 * Used as error detail when returning CodePermissionDenied errors.
 *
 * @generated from message bytebase.v1.PermissionDeniedDetail
 */
export declare type PermissionDeniedDetail = Message<"bytebase.v1.PermissionDeniedDetail"> & {
  /**
   * The API method that was called.
   *
   * @generated from field: string method = 1;
   */
  method: string;

  /**
   * The permissions required but not granted to the user.
   *
   * @generated from field: repeated string required_permissions = 2;
   */
  requiredPermissions: string[];

  /**
   * The resources the user was trying to access.
   *
   * @generated from field: repeated string resources = 3;
   */
  resources: string[];
};

/**
 * Describes the message bytebase.v1.PermissionDeniedDetail.
 * Use `create(PermissionDeniedDetailSchema)` to create a new message.
 */
export declare const PermissionDeniedDetailSchema: GenMessage<PermissionDeniedDetail>;

/**
 * Resource lifecycle state.
 *
 * @generated from enum bytebase.v1.State
 */
export enum State {
  /**
   * @generated from enum value: STATE_UNSPECIFIED = 0;
   */
  STATE_UNSPECIFIED = 0,

  /**
   * Resource is active and operational.
   *
   * @generated from enum value: ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * Resource is soft-deleted but may be recoverable.
   *
   * @generated from enum value: DELETED = 2;
   */
  DELETED = 2,
}

/**
 * Describes the enum bytebase.v1.State.
 */
export declare const StateSchema: GenEnum<State>;

/**
 * Database engine type.
 *
 * @generated from enum bytebase.v1.Engine
 */
export enum Engine {
  /**
   * Unspecified database engine.
   *
   * @generated from enum value: ENGINE_UNSPECIFIED = 0;
   */
  ENGINE_UNSPECIFIED = 0,

  /**
   * ClickHouse columnar database.
   *
   * @generated from enum value: CLICKHOUSE = 1;
   */
  CLICKHOUSE = 1,

  /**
   * MySQL relational database.
   *
   * @generated from enum value: MYSQL = 2;
   */
  MYSQL = 2,

  /**
   * PostgreSQL relational database.
   *
   * @generated from enum value: POSTGRES = 3;
   */
  POSTGRES = 3,

  /**
   * Snowflake cloud data warehouse.
   *
   * @generated from enum value: SNOWFLAKE = 4;
   */
  SNOWFLAKE = 4,

  /**
   * SQLite embedded database.
   *
   * @generated from enum value: SQLITE = 5;
   */
  SQLITE = 5,

  /**
   * TiDB distributed SQL database.
   *
   * @generated from enum value: TIDB = 6;
   */
  TIDB = 6,

  /**
   * MongoDB document database.
   *
   * @generated from enum value: MONGODB = 7;
   */
  MONGODB = 7,

  /**
   * Redis key-value store.
   *
   * @generated from enum value: REDIS = 8;
   */
  REDIS = 8,

  /**
   * Oracle relational database.
   *
   * @generated from enum value: ORACLE = 9;
   */
  ORACLE = 9,

  /**
   * Google Cloud Spanner distributed database.
   *
   * @generated from enum value: SPANNER = 10;
   */
  SPANNER = 10,

  /**
   * Microsoft SQL Server relational database.
   *
   * @generated from enum value: MSSQL = 11;
   */
  MSSQL = 11,

  /**
   * Amazon Redshift data warehouse.
   *
   * @generated from enum value: REDSHIFT = 12;
   */
  REDSHIFT = 12,

  /**
   * MariaDB relational database.
   *
   * @generated from enum value: MARIADB = 13;
   */
  MARIADB = 13,

  /**
   * OceanBase distributed database.
   *
   * @generated from enum value: OCEANBASE = 14;
   */
  OCEANBASE = 14,

  /**
   * StarRocks analytics database.
   *
   * @generated from enum value: STARROCKS = 15;
   */
  STARROCKS = 15,

  /**
   * Apache Doris analytics database.
   *
   * @generated from enum value: DORIS = 16;
   */
  DORIS = 16,

  /**
   * Apache Hive data warehouse.
   *
   * @generated from enum value: HIVE = 17;
   */
  HIVE = 17,

  /**
   * Elasticsearch search engine.
   *
   * @generated from enum value: ELASTICSEARCH = 18;
   */
  ELASTICSEARCH = 18,

  /**
   * Google BigQuery data warehouse.
   *
   * @generated from enum value: BIGQUERY = 19;
   */
  BIGQUERY = 19,

  /**
   * Amazon DynamoDB NoSQL database.
   *
   * @generated from enum value: DYNAMODB = 20;
   */
  DYNAMODB = 20,

  /**
   * Databricks lakehouse platform.
   *
   * @generated from enum value: DATABRICKS = 21;
   */
  DATABRICKS = 21,

  /**
   * CockroachDB distributed SQL database.
   *
   * @generated from enum value: COCKROACHDB = 22;
   */
  COCKROACHDB = 22,

  /**
   * Azure Cosmos DB multi-model database.
   *
   * @generated from enum value: COSMOSDB = 23;
   */
  COSMOSDB = 23,

  /**
   * Trino distributed SQL query engine.
   *
   * @generated from enum value: TRINO = 24;
   */
  TRINO = 24,

  /**
   * Apache Cassandra NoSQL database.
   *
   * @generated from enum value: CASSANDRA = 25;
   */
  CASSANDRA = 25,

  /**
   * Milvus vector database.
   *
   * @generated from enum value: MILVUS = 26;
   */
  MILVUS = 26,
}

/**
 * Describes the enum bytebase.v1.Engine.
 */
export declare const EngineSchema: GenEnum<Engine>;

/**
 * Version control system type.
 *
 * @generated from enum bytebase.v1.VCSType
 */
export enum VCSType {
  /**
   * Unspecified VCS type.
   *
   * @generated from enum value: VCS_TYPE_UNSPECIFIED = 0;
   */
  VCS_TYPE_UNSPECIFIED = 0,

  /**
   * GitHub version control platform.
   *
   * @generated from enum value: GITHUB = 1;
   */
  GITHUB = 1,

  /**
   * GitLab version control platform.
   *
   * @generated from enum value: GITLAB = 2;
   */
  GITLAB = 2,

  /**
   * Bitbucket version control platform.
   *
   * @generated from enum value: BITBUCKET = 3;
   */
  BITBUCKET = 3,

  /**
   * Azure DevOps version control platform.
   *
   * @generated from enum value: AZURE_DEVOPS = 4;
   */
  AZURE_DEVOPS = 4,
}

/**
 * Describes the enum bytebase.v1.VCSType.
 */
export declare const VCSTypeSchema: GenEnum<VCSType>;

/**
 * Data export format.
 *
 * @generated from enum bytebase.v1.ExportFormat
 */
export enum ExportFormat {
  /**
   * Unspecified export format.
   *
   * @generated from enum value: FORMAT_UNSPECIFIED = 0;
   */
  FORMAT_UNSPECIFIED = 0,

  /**
   * Comma-separated values format.
   *
   * @generated from enum value: CSV = 1;
   */
  CSV = 1,

  /**
   * JavaScript Object Notation format.
   *
   * @generated from enum value: JSON = 2;
   */
  JSON = 2,

  /**
   * SQL statements format.
   *
   * @generated from enum value: SQL = 3;
   */
  SQL = 3,

  /**
   * Microsoft Excel spreadsheet format.
   *
   * @generated from enum value: XLSX = 4;
   */
  XLSX = 4,
}

/**
 * Describes the enum bytebase.v1.ExportFormat.
 */
export declare const ExportFormatSchema: GenEnum<ExportFormat>;

/**
 * RiskLevel is the risk level.
 *
 * @generated from enum bytebase.v1.RiskLevel
 */
export enum RiskLevel {
  /**
   * Unspecified risk level.
   *
   * @generated from enum value: RISK_LEVEL_UNSPECIFIED = 0;
   */
  RISK_LEVEL_UNSPECIFIED = 0,

  /**
   * Low risk operation.
   *
   * @generated from enum value: LOW = 1;
   */
  LOW = 1,

  /**
   * Moderate risk operation.
   *
   * @generated from enum value: MODERATE = 2;
   */
  MODERATE = 2,

  /**
   * High risk operation.
   *
   * @generated from enum value: HIGH = 3;
   */
  HIGH = 3,
}

/**
 * Describes the enum bytebase.v1.RiskLevel.
 */
export declare const RiskLevelSchema: GenEnum<RiskLevel>;

/**
 * Webhook integration type.
 *
 * @generated from enum bytebase.v1.WebhookType
 */
export enum WebhookType {
  /**
   * Unspecified type.
   *
   * @generated from enum value: WEBHOOK_TYPE_UNSPECIFIED = 0;
   */
  WEBHOOK_TYPE_UNSPECIFIED = 0,

  /**
   * Slack integration.
   *
   * @generated from enum value: SLACK = 1;
   */
  SLACK = 1,

  /**
   * Discord integration.
   *
   * @generated from enum value: DISCORD = 2;
   */
  DISCORD = 2,

  /**
   * Microsoft Teams integration.
   *
   * @generated from enum value: TEAMS = 3;
   */
  TEAMS = 3,

  /**
   * DingTalk integration.
   *
   * @generated from enum value: DINGTALK = 4;
   */
  DINGTALK = 4,

  /**
   * Feishu integration.
   *
   * @generated from enum value: FEISHU = 5;
   */
  FEISHU = 5,

  /**
   * WeCom (WeChat Work) integration.
   *
   * @generated from enum value: WECOM = 6;
   */
  WECOM = 6,

  /**
   * Lark integration.
   *
   * @generated from enum value: LARK = 7;
   */
  LARK = 7,
}

/**
 * Describes the enum bytebase.v1.WebhookType.
 */
export declare const WebhookTypeSchema: GenEnum<WebhookType>;

/**
 * StatementType represents the type of SQL statement.
 *
 * @generated from enum bytebase.v1.StatementType
 */
export enum StatementType {
  /**
   * @generated from enum value: STATEMENT_TYPE_UNSPECIFIED = 0;
   */
  STATEMENT_TYPE_UNSPECIFIED = 0,

  /**
   * DDL - CREATE statements
   *
   * @generated from enum value: CREATE_DATABASE = 1;
   */
  CREATE_DATABASE = 1,

  /**
   * @generated from enum value: CREATE_TABLE = 2;
   */
  CREATE_TABLE = 2,

  /**
   * @generated from enum value: CREATE_VIEW = 3;
   */
  CREATE_VIEW = 3,

  /**
   * @generated from enum value: CREATE_INDEX = 4;
   */
  CREATE_INDEX = 4,

  /**
   * @generated from enum value: CREATE_SEQUENCE = 5;
   */
  CREATE_SEQUENCE = 5,

  /**
   * @generated from enum value: CREATE_SCHEMA = 6;
   */
  CREATE_SCHEMA = 6,

  /**
   * @generated from enum value: CREATE_FUNCTION = 7;
   */
  CREATE_FUNCTION = 7,

  /**
   * @generated from enum value: CREATE_TRIGGER = 8;
   */
  CREATE_TRIGGER = 8,

  /**
   * @generated from enum value: CREATE_PROCEDURE = 9;
   */
  CREATE_PROCEDURE = 9,

  /**
   * @generated from enum value: CREATE_EVENT = 10;
   */
  CREATE_EVENT = 10,

  /**
   * @generated from enum value: CREATE_EXTENSION = 11;
   */
  CREATE_EXTENSION = 11,

  /**
   * @generated from enum value: CREATE_TYPE = 12;
   */
  CREATE_TYPE = 12,

  /**
   * DDL - DROP statements
   *
   * @generated from enum value: DROP_DATABASE = 20;
   */
  DROP_DATABASE = 20,

  /**
   * @generated from enum value: DROP_TABLE = 21;
   */
  DROP_TABLE = 21,

  /**
   * @generated from enum value: DROP_VIEW = 22;
   */
  DROP_VIEW = 22,

  /**
   * @generated from enum value: DROP_INDEX = 23;
   */
  DROP_INDEX = 23,

  /**
   * @generated from enum value: DROP_SEQUENCE = 24;
   */
  DROP_SEQUENCE = 24,

  /**
   * @generated from enum value: DROP_SCHEMA = 25;
   */
  DROP_SCHEMA = 25,

  /**
   * @generated from enum value: DROP_FUNCTION = 26;
   */
  DROP_FUNCTION = 26,

  /**
   * @generated from enum value: DROP_TRIGGER = 27;
   */
  DROP_TRIGGER = 27,

  /**
   * @generated from enum value: DROP_PROCEDURE = 28;
   */
  DROP_PROCEDURE = 28,

  /**
   * @generated from enum value: DROP_EVENT = 29;
   */
  DROP_EVENT = 29,

  /**
   * @generated from enum value: DROP_EXTENSION = 30;
   */
  DROP_EXTENSION = 30,

  /**
   * @generated from enum value: DROP_TYPE = 31;
   */
  DROP_TYPE = 31,

  /**
   * DDL - ALTER statements
   *
   * @generated from enum value: ALTER_DATABASE = 40;
   */
  ALTER_DATABASE = 40,

  /**
   * @generated from enum value: ALTER_TABLE = 41;
   */
  ALTER_TABLE = 41,

  /**
   * @generated from enum value: ALTER_VIEW = 42;
   */
  ALTER_VIEW = 42,

  /**
   * @generated from enum value: ALTER_SEQUENCE = 43;
   */
  ALTER_SEQUENCE = 43,

  /**
   * @generated from enum value: ALTER_EVENT = 44;
   */
  ALTER_EVENT = 44,

  /**
   * @generated from enum value: ALTER_TYPE = 45;
   */
  ALTER_TYPE = 45,

  /**
   * @generated from enum value: ALTER_INDEX = 46;
   */
  ALTER_INDEX = 46,

  /**
   * DDL - Other
   *
   * @generated from enum value: TRUNCATE = 50;
   */
  TRUNCATE = 50,

  /**
   * @generated from enum value: RENAME = 51;
   */
  RENAME = 51,

  /**
   * @generated from enum value: RENAME_INDEX = 52;
   */
  RENAME_INDEX = 52,

  /**
   * @generated from enum value: RENAME_SCHEMA = 53;
   */
  RENAME_SCHEMA = 53,

  /**
   * @generated from enum value: RENAME_SEQUENCE = 54;
   */
  RENAME_SEQUENCE = 54,

  /**
   * @generated from enum value: COMMENT = 55;
   */
  COMMENT = 55,

  /**
   * DML statements
   *
   * @generated from enum value: INSERT = 60;
   */
  INSERT = 60,

  /**
   * @generated from enum value: UPDATE = 61;
   */
  UPDATE = 61,

  /**
   * @generated from enum value: DELETE = 62;
   */
  DELETE = 62,
}

/**
 * Describes the enum bytebase.v1.StatementType.
 */
export declare const StatementTypeSchema: GenEnum<StatementType>;
