// @generated by protoc-gen-es v2.12.0
// @generated from file v1/review_rule.proto (package bytebase.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/review_rule.proto.
 */
export declare const file_v1_review_rule: GenFile;

/**
 * ReviewRule holds the standard review rule set. The rules are fixed: every
 * project gets them without configuration, and the only setting is a switch
 * (see ReviewRulePolicy).
 *
 * A rule id names what the rule examines. An execution check is named for
 * what it checks; a rule about the SQL itself carries REQUIRE or DISALLOW so
 * the id says which way it cuts. DISALLOW on a P1 rule means the operation
 * needs a person's acceptance, not that it is forbidden.
 *
 * The enum is nested so its values stay flat: bytebase.v1 already has
 * top-level TRUNCATE and RENAME values.
 *
 * @generated from message bytebase.v1.ReviewRule
 */
export declare type ReviewRule = Message<"bytebase.v1.ReviewRule"> & {
};

/**
 * Describes the message bytebase.v1.ReviewRule.
 * Use `create(ReviewRuleSchema)` to create a new message.
 */
export declare const ReviewRuleSchema: GenMessage<ReviewRule>;

/**
 * @generated from enum bytebase.v1.ReviewRule.Type
 */
export enum ReviewRule_Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  TYPE_UNSPECIFIED = 0,

  /**
   * P0: the statements do not parse for the target engine.
   *
   * @generated from enum value: SYNTAX = 1;
   */
  SYNTAX = 1,

  /**
   * P0: applying the statements to the synced schema fails: a missing
   * table or column, a duplicate object, or an invalid reference.
   *
   * @generated from enum value: WALK_THROUGH = 2;
   */
  WALK_THROUGH = 2,

  /**
   * P0: the change requests online migration but is not eligible.
   *
   * @generated from enum value: ONLINE_MIGRATION = 3;
   */
  ONLINE_MIGRATION = 3,

  /**
   * P0: the change enables prior backup but the backup cannot be taken.
   *
   * @generated from enum value: PRIOR_BACKUP = 4;
   */
  PRIOR_BACKUP = 4,

  /**
   * P0: = NULL or <> NULL in a predicate, which is always false. Test for
   * NULL with IS NULL or IS NOT NULL.
   *
   * @generated from enum value: REQUIRE_IS_NULL = 5;
   */
  REQUIRE_IS_NULL = 5,

  /**
   * P1: UPDATE or DELETE without WHERE.
   *
   * @generated from enum value: REQUIRE_WHERE = 6;
   */
  REQUIRE_WHERE = 6,

  /**
   * P1: DROP TABLE, COLUMN, SCHEMA, or DATABASE.
   *
   * @generated from enum value: DISALLOW_DROP_OBJECT = 7;
   */
  DISALLOW_DROP_OBJECT = 7,

  /**
   * P1: TRUNCATE.
   *
   * @generated from enum value: DISALLOW_TRUNCATE = 8;
   */
  DISALLOW_TRUNCATE = 8,

  /**
   * P1: dropping a PRIMARY KEY, FOREIGN KEY, UNIQUE, or CHECK constraint.
   *
   * @generated from enum value: DISALLOW_DROP_CONSTRAINT = 9;
   */
  DISALLOW_DROP_CONSTRAINT = 9,

  /**
   * P1: renaming a table or column.
   *
   * @generated from enum value: DISALLOW_RENAME = 10;
   */
  DISALLOW_RENAME = 10,

  /**
   * P1: a table still has no primary key at the end of the change.
   *
   * @generated from enum value: REQUIRE_PRIMARY_KEY = 11;
   */
  REQUIRE_PRIMARY_KEY = 11,
}

/**
 * Describes the enum bytebase.v1.ReviewRule.Type.
 */
export declare const ReviewRule_TypeSchema: GenEnum<ReviewRule_Type>;

