// @generated by protoc-gen-es v2.5.2
// @generated from file v1/subscription_service.proto (package bytebase.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file v1/subscription_service.proto.
 */
export declare const file_v1_subscription_service: GenFile;

/**
 * @generated from message bytebase.v1.GetSubscriptionRequest
 */
export declare type GetSubscriptionRequest = Message<"bytebase.v1.GetSubscriptionRequest"> & {
};

/**
 * Describes the message bytebase.v1.GetSubscriptionRequest.
 * Use `create(GetSubscriptionRequestSchema)` to create a new message.
 */
export declare const GetSubscriptionRequestSchema: GenMessage<GetSubscriptionRequest>;

/**
 * @generated from message bytebase.v1.UpdateSubscriptionRequest
 */
export declare type UpdateSubscriptionRequest = Message<"bytebase.v1.UpdateSubscriptionRequest"> & {
  /**
   * @generated from field: string license = 1;
   */
  license: string;

  /**
   * If set to true, and the subscription is not found, a new subscription will be created.
   * In this situation, `update_mask` is ignored.
   *
   * @generated from field: bool allow_missing = 2;
   */
  allowMissing: boolean;
};

/**
 * Describes the message bytebase.v1.UpdateSubscriptionRequest.
 * Use `create(UpdateSubscriptionRequestSchema)` to create a new message.
 */
export declare const UpdateSubscriptionRequestSchema: GenMessage<UpdateSubscriptionRequest>;

/**
 * @generated from message bytebase.v1.CreatePurchaseRequest
 */
export declare type CreatePurchaseRequest = Message<"bytebase.v1.CreatePurchaseRequest"> & {
  /**
   * @generated from field: bytebase.v1.PlanType plan = 1;
   */
  plan: PlanType;

  /**
   * @generated from field: bytebase.v1.BillingInterval interval = 2;
   */
  interval: BillingInterval;

  /**
   * @generated from field: int32 seats = 3;
   */
  seats: number;
};

/**
 * Describes the message bytebase.v1.CreatePurchaseRequest.
 * Use `create(CreatePurchaseRequestSchema)` to create a new message.
 */
export declare const CreatePurchaseRequestSchema: GenMessage<CreatePurchaseRequest>;

/**
 * @generated from message bytebase.v1.CreatePurchaseResponse
 */
export declare type CreatePurchaseResponse = Message<"bytebase.v1.CreatePurchaseResponse"> & {
  /**
   * Stripe Checkout URL for the user to complete payment.
   *
   * @generated from field: string payment_url = 1;
   */
  paymentUrl: string;
};

/**
 * Describes the message bytebase.v1.CreatePurchaseResponse.
 * Use `create(CreatePurchaseResponseSchema)` to create a new message.
 */
export declare const CreatePurchaseResponseSchema: GenMessage<CreatePurchaseResponse>;

/**
 * @generated from message bytebase.v1.UpdatePurchaseRequest
 */
export declare type UpdatePurchaseRequest = Message<"bytebase.v1.UpdatePurchaseRequest"> & {
  /**
   * @generated from field: bytebase.v1.PlanType plan = 1;
   */
  plan: PlanType;

  /**
   * @generated from field: bytebase.v1.BillingInterval interval = 2;
   */
  interval: BillingInterval;

  /**
   * @generated from field: int32 seats = 3;
   */
  seats: number;

  /**
   * @generated from field: string etag = 4;
   */
  etag: string;
};

/**
 * Describes the message bytebase.v1.UpdatePurchaseRequest.
 * Use `create(UpdatePurchaseRequestSchema)` to create a new message.
 */
export declare const UpdatePurchaseRequestSchema: GenMessage<UpdatePurchaseRequest>;

/**
 * @generated from message bytebase.v1.UpdatePurchaseResponse
 */
export declare type UpdatePurchaseResponse = Message<"bytebase.v1.UpdatePurchaseResponse"> & {
  /**
   * If set, redirect to this Stripe Checkout URL.
   * If empty, the update was applied directly using the existing payment method.
   *
   * @generated from field: string payment_url = 1;
   */
  paymentUrl: string;
};

/**
 * Describes the message bytebase.v1.UpdatePurchaseResponse.
 * Use `create(UpdatePurchaseResponseSchema)` to create a new message.
 */
export declare const UpdatePurchaseResponseSchema: GenMessage<UpdatePurchaseResponse>;

/**
 * @generated from message bytebase.v1.CancelPurchaseRequest
 */
export declare type CancelPurchaseRequest = Message<"bytebase.v1.CancelPurchaseRequest"> & {
};

/**
 * Describes the message bytebase.v1.CancelPurchaseRequest.
 * Use `create(CancelPurchaseRequestSchema)` to create a new message.
 */
export declare const CancelPurchaseRequestSchema: GenMessage<CancelPurchaseRequest>;

/**
 * @generated from message bytebase.v1.CancelPurchaseResponse
 */
export declare type CancelPurchaseResponse = Message<"bytebase.v1.CancelPurchaseResponse"> & {
};

/**
 * Describes the message bytebase.v1.CancelPurchaseResponse.
 * Use `create(CancelPurchaseResponseSchema)` to create a new message.
 */
export declare const CancelPurchaseResponseSchema: GenMessage<CancelPurchaseResponse>;

/**
 * @generated from message bytebase.v1.GetPaymentInfoRequest
 */
export declare type GetPaymentInfoRequest = Message<"bytebase.v1.GetPaymentInfoRequest"> & {
};

/**
 * Describes the message bytebase.v1.GetPaymentInfoRequest.
 * Use `create(GetPaymentInfoRequestSchema)` to create a new message.
 */
export declare const GetPaymentInfoRequestSchema: GenMessage<GetPaymentInfoRequest>;

/**
 * @generated from message bytebase.v1.PaymentInfo
 */
export declare type PaymentInfo = Message<"bytebase.v1.PaymentInfo"> & {
  /**
   * @generated from field: string total_price = 1;
   */
  totalPrice: string;

  /**
   * @generated from field: string currency = 2;
   */
  currency: string;

  /**
   * @generated from field: string period_start = 3;
   */
  periodStart: string;

  /**
   * @generated from field: string period_end = 4;
   */
  periodEnd: string;

  /**
   * Stripe Billing Portal URL for invoice management.
   *
   * @generated from field: string invoice_url = 5;
   */
  invoiceUrl: string;
};

/**
 * Describes the message bytebase.v1.PaymentInfo.
 * Use `create(PaymentInfoSchema)` to create a new message.
 */
export declare const PaymentInfoSchema: GenMessage<PaymentInfo>;

/**
 * @generated from message bytebase.v1.PurchasePlan
 */
export declare type PurchasePlan = Message<"bytebase.v1.PurchasePlan"> & {
  /**
   * @generated from field: bytebase.v1.PlanType type = 1;
   */
  type: PlanType;

  /**
   * @generated from field: bool self_service_purchase = 2;
   */
  selfServicePurchase: boolean;

  /**
   * @generated from field: repeated bytebase.v1.PurchasePlanAdditional additionals = 3;
   */
  additionals: PurchasePlanAdditional[];

  /**
   * @generated from field: repeated bytebase.v1.PurchaseBillingMethod billing_methods = 4;
   */
  billingMethods: PurchaseBillingMethod[];
};

/**
 * Describes the message bytebase.v1.PurchasePlan.
 * Use `create(PurchasePlanSchema)` to create a new message.
 */
export declare const PurchasePlanSchema: GenMessage<PurchasePlan>;

/**
 * @generated from message bytebase.v1.PurchasePlanAdditional
 */
export declare type PurchasePlanAdditional = Message<"bytebase.v1.PurchasePlanAdditional"> & {
  /**
   * @generated from field: bytebase.v1.PurchasePlanAdditional.Type type = 1;
   */
  type: PurchasePlanAdditional_Type;

  /**
   * Price in USD cents per month.
   *
   * @generated from field: int32 unit_price = 2;
   */
  unitPrice: number;

  /**
   * @generated from field: int32 free_count = 3;
   */
  freeCount: number;

  /**
   * @generated from field: int32 minimum_count = 4;
   */
  minimumCount: number;

  /**
   * -1 means unlimited.
   *
   * @generated from field: int32 maximum_count = 5;
   */
  maximumCount: number;
};

/**
 * Describes the message bytebase.v1.PurchasePlanAdditional.
 * Use `create(PurchasePlanAdditionalSchema)` to create a new message.
 */
export declare const PurchasePlanAdditionalSchema: GenMessage<PurchasePlanAdditional>;

/**
 * @generated from enum bytebase.v1.PurchasePlanAdditional.Type
 */
export enum PurchasePlanAdditional_Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: USER = 1;
   */
  USER = 1,
}

/**
 * Describes the enum bytebase.v1.PurchasePlanAdditional.Type.
 */
export declare const PurchasePlanAdditional_TypeSchema: GenEnum<PurchasePlanAdditional_Type>;

/**
 * @generated from message bytebase.v1.PurchaseBillingMethod
 */
export declare type PurchaseBillingMethod = Message<"bytebase.v1.PurchaseBillingMethod"> & {
  /**
   * @generated from field: bytebase.v1.BillingInterval interval = 1;
   */
  interval: BillingInterval;

  /**
   * @generated from field: bytebase.v1.PurchaseDiscount discount = 2;
   */
  discount?: PurchaseDiscount;
};

/**
 * Describes the message bytebase.v1.PurchaseBillingMethod.
 * Use `create(PurchaseBillingMethodSchema)` to create a new message.
 */
export declare const PurchaseBillingMethodSchema: GenMessage<PurchaseBillingMethod>;

/**
 * @generated from message bytebase.v1.PurchaseDiscount
 */
export declare type PurchaseDiscount = Message<"bytebase.v1.PurchaseDiscount"> & {
  /**
   * @generated from field: string description = 1;
   */
  description: string;

  /**
   * @generated from field: string promotion_code = 2;
   */
  promotionCode: string;
};

/**
 * Describes the message bytebase.v1.PurchaseDiscount.
 * Use `create(PurchaseDiscountSchema)` to create a new message.
 */
export declare const PurchaseDiscountSchema: GenMessage<PurchaseDiscount>;

/**
 * @generated from message bytebase.v1.ListPurchasePlansRequest
 */
export declare type ListPurchasePlansRequest = Message<"bytebase.v1.ListPurchasePlansRequest"> & {
};

/**
 * Describes the message bytebase.v1.ListPurchasePlansRequest.
 * Use `create(ListPurchasePlansRequestSchema)` to create a new message.
 */
export declare const ListPurchasePlansRequestSchema: GenMessage<ListPurchasePlansRequest>;

/**
 * @generated from message bytebase.v1.ListPurchasePlansResponse
 */
export declare type ListPurchasePlansResponse = Message<"bytebase.v1.ListPurchasePlansResponse"> & {
  /**
   * @generated from field: repeated bytebase.v1.PurchasePlan plans = 1;
   */
  plans: PurchasePlan[];
};

/**
 * Describes the message bytebase.v1.ListPurchasePlansResponse.
 * Use `create(ListPurchasePlansResponseSchema)` to create a new message.
 */
export declare const ListPurchasePlansResponseSchema: GenMessage<ListPurchasePlansResponse>;

/**
 * @generated from message bytebase.v1.Subscription
 */
export declare type Subscription = Message<"bytebase.v1.Subscription"> & {
  /**
   * @generated from field: bytebase.v1.PlanType plan = 1;
   */
  plan: PlanType;

  /**
   * @generated from field: int32 seats = 2;
   */
  seats: number;

  /**
   * @generated from field: int32 instances = 3;
   */
  instances: number;

  /**
   * @generated from field: int32 active_instances = 4;
   */
  activeInstances: number;

  /**
   * @generated from field: google.protobuf.Timestamp expires_time = 5;
   */
  expiresTime?: Timestamp;

  /**
   * @generated from field: bool trialing = 6;
   */
  trialing: boolean;

  /**
   * @generated from field: string org_name = 7;
   */
  orgName: string;

  /**
   * Whether high availability (multiple replicas) is enabled.
   *
   * @generated from field: bool ha = 8;
   */
  ha: boolean;
};

/**
 * Describes the message bytebase.v1.Subscription.
 * Use `create(SubscriptionSchema)` to create a new message.
 */
export declare const SubscriptionSchema: GenMessage<Subscription>;

/**
 * PlanConfig represents the configuration for all plans loaded from plan.yaml
 *
 * @generated from message bytebase.v1.PlanConfig
 */
export declare type PlanConfig = Message<"bytebase.v1.PlanConfig"> & {
  /**
   * @generated from field: repeated bytebase.v1.PlanLimitConfig plans = 1;
   */
  plans: PlanLimitConfig[];

  /**
   * @generated from field: repeated bytebase.v1.PlanFeature instance_features = 2;
   */
  instanceFeatures: PlanFeature[];
};

/**
 * Describes the message bytebase.v1.PlanConfig.
 * Use `create(PlanConfigSchema)` to create a new message.
 */
export declare const PlanConfigSchema: GenMessage<PlanConfig>;

/**
 * PlanLimitConfig represents a single plan's configuration
 *
 * @generated from message bytebase.v1.PlanLimitConfig
 */
export declare type PlanLimitConfig = Message<"bytebase.v1.PlanLimitConfig"> & {
  /**
   * @generated from field: bytebase.v1.PlanType type = 1;
   */
  type: PlanType;

  /**
   * @generated from field: int32 maximum_instance_count = 2;
   */
  maximumInstanceCount: number;

  /**
   * @generated from field: int32 maximum_seat_count = 3;
   */
  maximumSeatCount: number;

  /**
   * @generated from field: repeated bytebase.v1.PlanFeature features = 4;
   */
  features: PlanFeature[];
};

/**
 * Describes the message bytebase.v1.PlanLimitConfig.
 * Use `create(PlanLimitConfigSchema)` to create a new message.
 */
export declare const PlanLimitConfigSchema: GenMessage<PlanLimitConfig>;

/**
 * @generated from enum bytebase.v1.BillingInterval
 */
export enum BillingInterval {
  /**
   * @generated from enum value: BILLING_INTERVAL_UNSPECIFIED = 0;
   */
  BILLING_INTERVAL_UNSPECIFIED = 0,

  /**
   * @generated from enum value: MONTH = 1;
   */
  MONTH = 1,

  /**
   * @generated from enum value: YEAR = 2;
   */
  YEAR = 2,
}

/**
 * Describes the enum bytebase.v1.BillingInterval.
 */
export declare const BillingIntervalSchema: GenEnum<BillingInterval>;

/**
 * @generated from enum bytebase.v1.PlanType
 */
export enum PlanType {
  /**
   * Unspecified plan type.
   *
   * @generated from enum value: PLAN_TYPE_UNSPECIFIED = 0;
   */
  PLAN_TYPE_UNSPECIFIED = 0,

  /**
   * Free plan with basic features and no cost.
   *
   * @generated from enum value: FREE = 1;
   */
  FREE = 1,

  /**
   * Team plan with collaboration features for small to medium teams.
   *
   * @generated from enum value: TEAM = 2;
   */
  TEAM = 2,

  /**
   * Enterprise plan with advanced features and dedicated support.
   *
   * @generated from enum value: ENTERPRISE = 3;
   */
  ENTERPRISE = 3,
}

/**
 * Describes the enum bytebase.v1.PlanType.
 */
export declare const PlanTypeSchema: GenEnum<PlanType>;

/**
 * PlanFeature represents the available features in Bytebase
 *
 * @generated from enum bytebase.v1.PlanFeature
 */
export enum PlanFeature {
  /**
   * @generated from enum value: FEATURE_UNSPECIFIED = 0;
   */
  FEATURE_UNSPECIFIED = 0,

  /**
   * Database Change Management
   *
   * @generated from enum value: FEATURE_DATABASE_CHANGE = 1;
   */
  FEATURE_DATABASE_CHANGE = 1,

  /**
   * @generated from enum value: FEATURE_GIT_BASED_SCHEMA_VERSION_CONTROL = 2;
   */
  FEATURE_GIT_BASED_SCHEMA_VERSION_CONTROL = 2,

  /**
   * @generated from enum value: FEATURE_DECLARATIVE_SCHEMA_MIGRATION = 3;
   */
  FEATURE_DECLARATIVE_SCHEMA_MIGRATION = 3,

  /**
   * @generated from enum value: FEATURE_COMPARE_AND_SYNC_SCHEMA = 4;
   */
  FEATURE_COMPARE_AND_SYNC_SCHEMA = 4,

  /**
   * @generated from enum value: FEATURE_ONLINE_SCHEMA_CHANGE = 5;
   */
  FEATURE_ONLINE_SCHEMA_CHANGE = 5,

  /**
   * @generated from enum value: FEATURE_PRE_DEPLOYMENT_SQL_REVIEW = 6;
   */
  FEATURE_PRE_DEPLOYMENT_SQL_REVIEW = 6,

  /**
   * @generated from enum value: FEATURE_AUTOMATIC_BACKUP_BEFORE_DATA_CHANGES = 7;
   */
  FEATURE_AUTOMATIC_BACKUP_BEFORE_DATA_CHANGES = 7,

  /**
   * @generated from enum value: FEATURE_ONE_CLICK_DATA_ROLLBACK = 8;
   */
  FEATURE_ONE_CLICK_DATA_ROLLBACK = 8,

  /**
   * @generated from enum value: FEATURE_MULTI_DATABASE_BATCH_CHANGES = 9;
   */
  FEATURE_MULTI_DATABASE_BATCH_CHANGES = 9,

  /**
   * @generated from enum value: FEATURE_PROGRESSIVE_ENVIRONMENT_DEPLOYMENT = 10;
   */
  FEATURE_PROGRESSIVE_ENVIRONMENT_DEPLOYMENT = 10,

  /**
   * @generated from enum value: FEATURE_SCHEDULED_ROLLOUT_TIME = 11;
   */
  FEATURE_SCHEDULED_ROLLOUT_TIME = 11,

  /**
   * @generated from enum value: FEATURE_DATABASE_CHANGELOG = 12;
   */
  FEATURE_DATABASE_CHANGELOG = 12,

  /**
   * @generated from enum value: FEATURE_SCHEMA_DRIFT_DETECTION = 13;
   */
  FEATURE_SCHEMA_DRIFT_DETECTION = 13,

  /**
   * @generated from enum value: FEATURE_ROLLOUT_POLICY = 14;
   */
  FEATURE_ROLLOUT_POLICY = 14,

  /**
   * SQL Editor & Development
   *
   * @generated from enum value: FEATURE_WEB_BASED_SQL_EDITOR = 15;
   */
  FEATURE_WEB_BASED_SQL_EDITOR = 15,

  /**
   * @generated from enum value: FEATURE_SQL_EDITOR_ADMIN_MODE = 16;
   */
  FEATURE_SQL_EDITOR_ADMIN_MODE = 16,

  /**
   * @generated from enum value: FEATURE_NATURAL_LANGUAGE_TO_SQL = 17;
   */
  FEATURE_NATURAL_LANGUAGE_TO_SQL = 17,

  /**
   * @generated from enum value: FEATURE_AI_QUERY_EXPLANATION = 18;
   */
  FEATURE_AI_QUERY_EXPLANATION = 18,

  /**
   * @generated from enum value: FEATURE_AI_QUERY_SUGGESTIONS = 19;
   */
  FEATURE_AI_QUERY_SUGGESTIONS = 19,

  /**
   * @generated from enum value: FEATURE_AUTO_COMPLETE = 20;
   */
  FEATURE_AUTO_COMPLETE = 20,

  /**
   * @generated from enum value: FEATURE_SCHEMA_DIAGRAM = 21;
   */
  FEATURE_SCHEMA_DIAGRAM = 21,

  /**
   * @generated from enum value: FEATURE_SCHEMA_EDITOR = 22;
   */
  FEATURE_SCHEMA_EDITOR = 22,

  /**
   * @generated from enum value: FEATURE_DATA_EXPORT = 23;
   */
  FEATURE_DATA_EXPORT = 23,

  /**
   * @generated from enum value: FEATURE_DATA_OFFLINE_EXPORT = 24;
   */
  FEATURE_DATA_OFFLINE_EXPORT = 24,

  /**
   * @generated from enum value: FEATURE_QUERY_HISTORY = 25;
   */
  FEATURE_QUERY_HISTORY = 25,

  /**
   * @generated from enum value: FEATURE_SAVED_AND_SHARED_SQL_SCRIPTS = 26;
   */
  FEATURE_SAVED_AND_SHARED_SQL_SCRIPTS = 26,

  /**
   * @generated from enum value: FEATURE_BATCH_QUERY = 27;
   */
  FEATURE_BATCH_QUERY = 27,

  /**
   * @generated from enum value: FEATURE_INSTANCE_READ_ONLY_CONNECTION = 28;
   */
  FEATURE_INSTANCE_READ_ONLY_CONNECTION = 28,

  /**
   * @generated from enum value: FEATURE_QUERY_POLICY = 29;
   */
  FEATURE_QUERY_POLICY = 29,

  /**
   * @generated from enum value: FEATURE_RESTRICT_COPYING_DATA = 30;
   */
  FEATURE_RESTRICT_COPYING_DATA = 30,

  /**
   * Security & Compliance
   *
   * @generated from enum value: FEATURE_IAM = 31;
   */
  FEATURE_IAM = 31,

  /**
   * @generated from enum value: FEATURE_INSTANCE_SSL_CONNECTION = 32;
   */
  FEATURE_INSTANCE_SSL_CONNECTION = 32,

  /**
   * @generated from enum value: FEATURE_INSTANCE_CONNECTION_OVER_SSH_TUNNEL = 33;
   */
  FEATURE_INSTANCE_CONNECTION_OVER_SSH_TUNNEL = 33,

  /**
   * @generated from enum value: FEATURE_INSTANCE_CONNECTION_IAM_AUTHENTICATION = 34;
   */
  FEATURE_INSTANCE_CONNECTION_IAM_AUTHENTICATION = 34,

  /**
   * @generated from enum value: FEATURE_GOOGLE_AND_GITHUB_SSO = 35;
   */
  FEATURE_GOOGLE_AND_GITHUB_SSO = 35,

  /**
   * @generated from enum value: FEATURE_USER_GROUPS = 36;
   */
  FEATURE_USER_GROUPS = 36,

  /**
   * @generated from enum value: FEATURE_DISALLOW_SELF_SERVICE_SIGNUP = 37;
   */
  FEATURE_DISALLOW_SELF_SERVICE_SIGNUP = 37,

  /**
   * @generated from enum value: FEATURE_CUSTOM_INSTANCE_SYNC_TIME = 38;
   */
  FEATURE_CUSTOM_INSTANCE_SYNC_TIME = 38,

  /**
   * @generated from enum value: FEATURE_CUSTOM_INSTANCE_CONNECTION_LIMIT = 39;
   */
  FEATURE_CUSTOM_INSTANCE_CONNECTION_LIMIT = 39,

  /**
   * @generated from enum value: FEATURE_RISK_ASSESSMENT = 40;
   */
  FEATURE_RISK_ASSESSMENT = 40,

  /**
   * @generated from enum value: FEATURE_APPROVAL_WORKFLOW = 41;
   */
  FEATURE_APPROVAL_WORKFLOW = 41,

  /**
   * @generated from enum value: FEATURE_AUDIT_LOG = 42;
   */
  FEATURE_AUDIT_LOG = 42,

  /**
   * @generated from enum value: FEATURE_ENTERPRISE_SSO = 43;
   */
  FEATURE_ENTERPRISE_SSO = 43,

  /**
   * @generated from enum value: FEATURE_TWO_FA = 44;
   */
  FEATURE_TWO_FA = 44,

  /**
   * @generated from enum value: FEATURE_PASSWORD_RESTRICTIONS = 45;
   */
  FEATURE_PASSWORD_RESTRICTIONS = 45,

  /**
   * @generated from enum value: FEATURE_DISALLOW_PASSWORD_SIGNIN = 46;
   */
  FEATURE_DISALLOW_PASSWORD_SIGNIN = 46,

  /**
   * @generated from enum value: FEATURE_CUSTOM_ROLES = 47;
   */
  FEATURE_CUSTOM_ROLES = 47,

  /**
   * @generated from enum value: FEATURE_REQUEST_ROLE_WORKFLOW = 48;
   */
  FEATURE_REQUEST_ROLE_WORKFLOW = 48,

  /**
   * @generated from enum value: FEATURE_JIT = 49;
   */
  FEATURE_JIT = 49,

  /**
   * @generated from enum value: FEATURE_DATA_MASKING = 50;
   */
  FEATURE_DATA_MASKING = 50,

  /**
   * @generated from enum value: FEATURE_DATA_CLASSIFICATION = 51;
   */
  FEATURE_DATA_CLASSIFICATION = 51,

  /**
   * @generated from enum value: FEATURE_SCIM = 52;
   */
  FEATURE_SCIM = 52,

  /**
   * @generated from enum value: FEATURE_DIRECTORY_SYNC = 53;
   */
  FEATURE_DIRECTORY_SYNC = 53,

  /**
   * @generated from enum value: FEATURE_TOKEN_DURATION_CONTROL = 54;
   */
  FEATURE_TOKEN_DURATION_CONTROL = 54,

  /**
   * @generated from enum value: FEATURE_EXTERNAL_SECRET_MANAGER = 55;
   */
  FEATURE_EXTERNAL_SECRET_MANAGER = 55,

  /**
   * @generated from enum value: FEATURE_USER_EMAIL_DOMAIN_RESTRICTION = 56;
   */
  FEATURE_USER_EMAIL_DOMAIN_RESTRICTION = 56,

  /**
   * Administration & Support
   *
   * @generated from enum value: FEATURE_PROJECT_MANAGEMENT = 57;
   */
  FEATURE_PROJECT_MANAGEMENT = 57,

  /**
   * @generated from enum value: FEATURE_ENVIRONMENT_MANAGEMENT = 58;
   */
  FEATURE_ENVIRONMENT_MANAGEMENT = 58,

  /**
   * @generated from enum value: FEATURE_IM_NOTIFICATIONS = 59;
   */
  FEATURE_IM_NOTIFICATIONS = 59,

  /**
   * @generated from enum value: FEATURE_TERRAFORM_PROVIDER = 60;
   */
  FEATURE_TERRAFORM_PROVIDER = 60,

  /**
   * @generated from enum value: FEATURE_DATABASE_GROUPS = 61;
   */
  FEATURE_DATABASE_GROUPS = 61,

  /**
   * @generated from enum value: FEATURE_ENVIRONMENT_TIERS = 62;
   */
  FEATURE_ENVIRONMENT_TIERS = 62,

  /**
   * @generated from enum value: FEATURE_DASHBOARD_ANNOUNCEMENT = 63;
   */
  FEATURE_DASHBOARD_ANNOUNCEMENT = 63,

  /**
   * @generated from enum value: FEATURE_API_INTEGRATION_GUIDANCE = 64;
   */
  FEATURE_API_INTEGRATION_GUIDANCE = 64,

  /**
   * @generated from enum value: FEATURE_CUSTOM_LOGO = 65;
   */
  FEATURE_CUSTOM_LOGO = 65,

  /**
   * @generated from enum value: FEATURE_WATERMARK = 66;
   */
  FEATURE_WATERMARK = 66,

  /**
   * @generated from enum value: FEATURE_ROADMAP_PRIORITIZATION = 67;
   */
  FEATURE_ROADMAP_PRIORITIZATION = 67,

  /**
   * @generated from enum value: FEATURE_CUSTOM_MSA = 68;
   */
  FEATURE_CUSTOM_MSA = 68,

  /**
   * @generated from enum value: FEATURE_COMMUNITY_SUPPORT = 69;
   */
  FEATURE_COMMUNITY_SUPPORT = 69,

  /**
   * @generated from enum value: FEATURE_EMAIL_SUPPORT = 70;
   */
  FEATURE_EMAIL_SUPPORT = 70,

  /**
   * @generated from enum value: FEATURE_DEDICATED_SUPPORT_WITH_SLA = 71;
   */
  FEATURE_DEDICATED_SUPPORT_WITH_SLA = 71,
}

/**
 * Describes the enum bytebase.v1.PlanFeature.
 */
export declare const PlanFeatureSchema: GenEnum<PlanFeature>;

/**
 * SubscriptionService manages enterprise subscriptions and licensing.
 *
 * @generated from service bytebase.v1.SubscriptionService
 */
export declare const SubscriptionService: GenService<{
  /**
   * GetSubscription returns the current subscription.
   * If there is no license, we will return a free plan subscription without expiration time.
   * If there is expired license, we will return a free plan subscription with the expiration time of the expired license.
   * Permissions required: None
   *
   * @generated from rpc bytebase.v1.SubscriptionService.GetSubscription
   */
  getSubscription: {
    methodKind: "unary";
    input: typeof GetSubscriptionRequestSchema;
    output: typeof SubscriptionSchema;
  },
  /**
   * Updates the enterprise license subscription (self-hosted only).
   * Permissions required: bb.settings.set
   *
   * @generated from rpc bytebase.v1.SubscriptionService.UpdateSubscription
   */
  updateSubscription: {
    methodKind: "unary";
    input: typeof UpdateSubscriptionRequestSchema;
    output: typeof SubscriptionSchema;
  },
  /**
   * CreatePurchase creates a new subscription purchase (SaaS only).
   * Returns a Stripe Checkout URL for the user to complete payment.
   *
   * @generated from rpc bytebase.v1.SubscriptionService.CreatePurchase
   */
  createPurchase: {
    methodKind: "unary";
    input: typeof CreatePurchaseRequestSchema;
    output: typeof CreatePurchaseResponseSchema;
  },
  /**
   * UpdatePurchase updates an existing subscription (SaaS only).
   * May return a Stripe Checkout URL if payment method change is needed.
   *
   * @generated from rpc bytebase.v1.SubscriptionService.UpdatePurchase
   */
  updatePurchase: {
    methodKind: "unary";
    input: typeof UpdatePurchaseRequestSchema;
    output: typeof UpdatePurchaseResponseSchema;
  },
  /**
   * CancelPurchase cancels an active subscription (SaaS only).
   *
   * @generated from rpc bytebase.v1.SubscriptionService.CancelPurchase
   */
  cancelPurchase: {
    methodKind: "unary";
    input: typeof CancelPurchaseRequestSchema;
    output: typeof CancelPurchaseResponseSchema;
  },
  /**
   * GetPaymentInfo returns payment details for the current subscription (SaaS only).
   *
   * @generated from rpc bytebase.v1.SubscriptionService.GetPaymentInfo
   */
  getPaymentInfo: {
    methodKind: "unary";
    input: typeof GetPaymentInfoRequestSchema;
    output: typeof PaymentInfoSchema;
  },
  /**
   * ListPurchasePlans returns available plans for self-service purchase.
   *
   * @generated from rpc bytebase.v1.SubscriptionService.ListPurchasePlans
   */
  listPurchasePlans: {
    methodKind: "unary";
    input: typeof ListPurchasePlansRequestSchema;
    output: typeof ListPurchasePlansResponseSchema;
  },
}>;

