// @generated by protoc-gen-es v2.5.2
// @generated from file v1/workload_identity_service.proto (package bytebase.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { State } from "./common_pb";
import type { EmptySchema, FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";
import type { WorkloadIdentityConfig } from "./user_service_pb";

/**
 * Describes the file v1/workload_identity_service.proto.
 */
export declare const file_v1_workload_identity_service: GenFile;

/**
 * WorkloadIdentity represents an external CI/CD workload identity.
 *
 * @generated from message bytebase.v1.WorkloadIdentity
 */
export declare type WorkloadIdentity = Message<"bytebase.v1.WorkloadIdentity"> & {
  /**
   * The name of the workload identity.
   * Format: workloadIdentities/{email}
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The state of the workload identity.
   *
   * @generated from field: bytebase.v1.State state = 2;
   */
  state: State;

  /**
   * The email of the workload identity.
   * For workspace-level: {name}@workload.bytebase.com
   * For project-level: {name}@{project-id}.workload.bytebase.com
   *
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * The display title of the workload identity.
   *
   * @generated from field: string title = 4;
   */
  title: string;

  /**
   * The timestamp when the workload identity was created.
   *
   * @generated from field: google.protobuf.Timestamp create_time = 5;
   */
  createTime?: Timestamp;

  /**
   * The workload identity configuration for OIDC token validation.
   *
   * @generated from field: bytebase.v1.WorkloadIdentityConfig workload_identity_config = 6;
   */
  workloadIdentityConfig?: WorkloadIdentityConfig;
};

/**
 * Describes the message bytebase.v1.WorkloadIdentity.
 * Use `create(WorkloadIdentitySchema)` to create a new message.
 */
export declare const WorkloadIdentitySchema: GenMessage<WorkloadIdentity>;

/**
 * Request message for creating a workload identity.
 *
 * @generated from message bytebase.v1.CreateWorkloadIdentityRequest
 */
export declare type CreateWorkloadIdentityRequest = Message<"bytebase.v1.CreateWorkloadIdentityRequest"> & {
  /**
   * The parent resource where this workload identity will be created.
   * Format: projects/{project} for project-level, empty for workspace-level.
   *
   * @generated from field: string parent = 1;
   */
  parent: string;

  /**
   * The ID to use for the workload identity, which will become the final component
   * of the workload identity's email in the format: {workload_identity_id}@workload.bytebase.com
   * or {workload_identity_id}@{project-id}.workload.bytebase.com
   *
   * @generated from field: string workload_identity_id = 2;
   */
  workloadIdentityId: string;

  /**
   * The workload identity to create.
   *
   * @generated from field: bytebase.v1.WorkloadIdentity workload_identity = 3;
   */
  workloadIdentity?: WorkloadIdentity;
};

/**
 * Describes the message bytebase.v1.CreateWorkloadIdentityRequest.
 * Use `create(CreateWorkloadIdentityRequestSchema)` to create a new message.
 */
export declare const CreateWorkloadIdentityRequestSchema: GenMessage<CreateWorkloadIdentityRequest>;

/**
 * Request message for getting a workload identity.
 *
 * @generated from message bytebase.v1.GetWorkloadIdentityRequest
 */
export declare type GetWorkloadIdentityRequest = Message<"bytebase.v1.GetWorkloadIdentityRequest"> & {
  /**
   * The name of the workload identity to retrieve.
   * Format: workloadIdentities/{email}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message bytebase.v1.GetWorkloadIdentityRequest.
 * Use `create(GetWorkloadIdentityRequestSchema)` to create a new message.
 */
export declare const GetWorkloadIdentityRequestSchema: GenMessage<GetWorkloadIdentityRequest>;

/**
 * Request message for batch getting workload identities.
 *
 * @generated from message bytebase.v1.BatchGetWorkloadIdentitiesRequest
 */
export declare type BatchGetWorkloadIdentitiesRequest = Message<"bytebase.v1.BatchGetWorkloadIdentitiesRequest"> & {
  /**
   * The workload identity names to retrieve.
   * Format: workloadIdentities/{email}
   *
   * @generated from field: repeated string names = 1;
   */
  names: string[];
};

/**
 * Describes the message bytebase.v1.BatchGetWorkloadIdentitiesRequest.
 * Use `create(BatchGetWorkloadIdentitiesRequestSchema)` to create a new message.
 */
export declare const BatchGetWorkloadIdentitiesRequestSchema: GenMessage<BatchGetWorkloadIdentitiesRequest>;

/**
 * Response message for batch getting workload identities.
 *
 * @generated from message bytebase.v1.BatchGetWorkloadIdentitiesResponse
 */
export declare type BatchGetWorkloadIdentitiesResponse = Message<"bytebase.v1.BatchGetWorkloadIdentitiesResponse"> & {
  /**
   * The workload identities from the specified request.
   *
   * @generated from field: repeated bytebase.v1.WorkloadIdentity workload_identities = 1;
   */
  workloadIdentities: WorkloadIdentity[];
};

/**
 * Describes the message bytebase.v1.BatchGetWorkloadIdentitiesResponse.
 * Use `create(BatchGetWorkloadIdentitiesResponseSchema)` to create a new message.
 */
export declare const BatchGetWorkloadIdentitiesResponseSchema: GenMessage<BatchGetWorkloadIdentitiesResponse>;

/**
 * Request message for listing workload identities.
 *
 * @generated from message bytebase.v1.ListWorkloadIdentitiesRequest
 */
export declare type ListWorkloadIdentitiesRequest = Message<"bytebase.v1.ListWorkloadIdentitiesRequest"> & {
  /**
   * The parent resource.
   * Format: projects/{project} for project-level, empty for workspace-level.
   *
   * @generated from field: string parent = 1;
   */
  parent: string;

  /**
   * The maximum number of workload identities to return. The service may return fewer than
   * this value.
   * If unspecified, at most 10 workload identities will be returned.
   * The maximum value is 1000; values above 1000 will be coerced to 1000.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * A page token, received from a previous `ListWorkloadIdentities` call.
   * Provide this to retrieve the subsequent page.
   *
   * When paginating, all other parameters provided to `ListWorkloadIdentities` must match
   * the call that provided the page token.
   *
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * Show deleted workload identities if specified.
   *
   * @generated from field: bool show_deleted = 4;
   */
  showDeleted: boolean;
};

/**
 * Describes the message bytebase.v1.ListWorkloadIdentitiesRequest.
 * Use `create(ListWorkloadIdentitiesRequestSchema)` to create a new message.
 */
export declare const ListWorkloadIdentitiesRequestSchema: GenMessage<ListWorkloadIdentitiesRequest>;

/**
 * Response message for listing workload identities.
 *
 * @generated from message bytebase.v1.ListWorkloadIdentitiesResponse
 */
export declare type ListWorkloadIdentitiesResponse = Message<"bytebase.v1.ListWorkloadIdentitiesResponse"> & {
  /**
   * The workload identities from the specified request.
   *
   * @generated from field: repeated bytebase.v1.WorkloadIdentity workload_identities = 1;
   */
  workloadIdentities: WorkloadIdentity[];

  /**
   * A token, which can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message bytebase.v1.ListWorkloadIdentitiesResponse.
 * Use `create(ListWorkloadIdentitiesResponseSchema)` to create a new message.
 */
export declare const ListWorkloadIdentitiesResponseSchema: GenMessage<ListWorkloadIdentitiesResponse>;

/**
 * Request message for updating a workload identity.
 *
 * @generated from message bytebase.v1.UpdateWorkloadIdentityRequest
 */
export declare type UpdateWorkloadIdentityRequest = Message<"bytebase.v1.UpdateWorkloadIdentityRequest"> & {
  /**
   * The workload identity to update.
   *
   * The workload identity's `name` field is used to identify the workload identity to update.
   * Format: workloadIdentities/{email}
   *
   * @generated from field: bytebase.v1.WorkloadIdentity workload_identity = 1;
   */
  workloadIdentity?: WorkloadIdentity;

  /**
   * The list of fields to update.
   * Supported fields: title, workload_identity_config
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message bytebase.v1.UpdateWorkloadIdentityRequest.
 * Use `create(UpdateWorkloadIdentityRequestSchema)` to create a new message.
 */
export declare const UpdateWorkloadIdentityRequestSchema: GenMessage<UpdateWorkloadIdentityRequest>;

/**
 * Request message for deleting a workload identity.
 *
 * @generated from message bytebase.v1.DeleteWorkloadIdentityRequest
 */
export declare type DeleteWorkloadIdentityRequest = Message<"bytebase.v1.DeleteWorkloadIdentityRequest"> & {
  /**
   * The name of the workload identity to delete.
   * Format: workloadIdentities/{email}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message bytebase.v1.DeleteWorkloadIdentityRequest.
 * Use `create(DeleteWorkloadIdentityRequestSchema)` to create a new message.
 */
export declare const DeleteWorkloadIdentityRequestSchema: GenMessage<DeleteWorkloadIdentityRequest>;

/**
 * Request message for restoring a deleted workload identity.
 *
 * @generated from message bytebase.v1.UndeleteWorkloadIdentityRequest
 */
export declare type UndeleteWorkloadIdentityRequest = Message<"bytebase.v1.UndeleteWorkloadIdentityRequest"> & {
  /**
   * The name of the deleted workload identity.
   * Format: workloadIdentities/{email}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message bytebase.v1.UndeleteWorkloadIdentityRequest.
 * Use `create(UndeleteWorkloadIdentityRequestSchema)` to create a new message.
 */
export declare const UndeleteWorkloadIdentityRequestSchema: GenMessage<UndeleteWorkloadIdentityRequest>;

/**
 * WorkloadIdentityService manages workload identities for external CI/CD integrations.
 *
 * @generated from service bytebase.v1.WorkloadIdentityService
 */
export declare const WorkloadIdentityService: GenService<{
  /**
   * Creates a new workload identity.
   * For workspace-level: parent is empty, permission bb.workloadIdentities.create on workspace.
   * For project-level: parent is projects/{project}, permission bb.workloadIdentities.create on project.
   *
   * @generated from rpc bytebase.v1.WorkloadIdentityService.CreateWorkloadIdentity
   */
  createWorkloadIdentity: {
    methodKind: "unary";
    input: typeof CreateWorkloadIdentityRequestSchema;
    output: typeof WorkloadIdentitySchema;
  },
  /**
   * Gets a workload identity by name.
   * Permissions required: bb.workloadIdentities.get
   *
   * @generated from rpc bytebase.v1.WorkloadIdentityService.GetWorkloadIdentity
   */
  getWorkloadIdentity: {
    methodKind: "unary";
    input: typeof GetWorkloadIdentityRequestSchema;
    output: typeof WorkloadIdentitySchema;
  },
  /**
   * Gets workload identities in batch.
   * Permissions required: bb.workloadIdentities.get
   *
   * @generated from rpc bytebase.v1.WorkloadIdentityService.BatchGetWorkloadIdentities
   */
  batchGetWorkloadIdentities: {
    methodKind: "unary";
    input: typeof BatchGetWorkloadIdentitiesRequestSchema;
    output: typeof BatchGetWorkloadIdentitiesResponseSchema;
  },
  /**
   * Lists workload identities.
   * For workspace-level: parent is empty, permission bb.workloadIdentities.list on workspace.
   * For project-level: parent is projects/{project}, permission bb.workloadIdentities.list on project.
   *
   * @generated from rpc bytebase.v1.WorkloadIdentityService.ListWorkloadIdentities
   */
  listWorkloadIdentities: {
    methodKind: "unary";
    input: typeof ListWorkloadIdentitiesRequestSchema;
    output: typeof ListWorkloadIdentitiesResponseSchema;
  },
  /**
   * Updates a workload identity.
   * Permissions required: bb.workloadIdentities.update
   *
   * @generated from rpc bytebase.v1.WorkloadIdentityService.UpdateWorkloadIdentity
   */
  updateWorkloadIdentity: {
    methodKind: "unary";
    input: typeof UpdateWorkloadIdentityRequestSchema;
    output: typeof WorkloadIdentitySchema;
  },
  /**
   * Deletes a workload identity.
   * Permissions required: bb.workloadIdentities.delete
   *
   * @generated from rpc bytebase.v1.WorkloadIdentityService.DeleteWorkloadIdentity
   */
  deleteWorkloadIdentity: {
    methodKind: "unary";
    input: typeof DeleteWorkloadIdentityRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Restores a deleted workload identity.
   * Permissions required: bb.workloadIdentities.undelete
   *
   * @generated from rpc bytebase.v1.WorkloadIdentityService.UndeleteWorkloadIdentity
   */
  undeleteWorkloadIdentity: {
    methodKind: "unary";
    input: typeof UndeleteWorkloadIdentityRequestSchema;
    output: typeof WorkloadIdentitySchema;
  },
}>;

