ALTER TABLE idp DROP COLUMN IF EXISTS created_ts, DROP COLUMN IF EXISTS updated_ts;
ALTER TABLE setting DROP COLUMN IF EXISTS row_status, DROP COLUMN IF EXISTS creator_id, DROP COLUMN IF EXISTS created_ts, DROP COLUMN IF EXISTS updater_id, DROP COLUMN IF EXISTS updated_ts, DROP COLUMN IF EXISTS description;
ALTER TABLE role DROP COLUMN IF EXISTS row_status, DROP COLUMN IF EXISTS creator_id, DROP COLUMN IF EXISTS created_ts, DROP COLUMN IF EXISTS updater_id, DROP COLUMN IF EXISTS updated_ts;
ALTER TABLE environment DROP COLUMN IF EXISTS creator_id, DROP COLUMN IF EXISTS created_ts, DROP COLUMN IF EXISTS updater_id, DROP COLUMN IF EXISTS updated_ts;
ALTER TABLE policy DROP COLUMN IF EXISTS creator_id, DROP COLUMN IF EXISTS created_ts, DROP COLUMN IF EXISTS updater_id, DROP COLUMN IF EXISTS updated_ts;
ALTER TABLE policy ADD COLUMN IF NOT EXISTS updated_ts TIMESTAMPTZ NOT NULL DEFAULT now();
