name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        If you are reporting a new issue, make sure that we do not have any duplicates already open. You can ensure this by searching the issue list for this repository. If there is a duplicate, please close your issue and add a comment to the existing issue instead.
  - type: input
    attributes:
      label: Provide the Bytebase version you are using
      description: |
        You can find the version in the footer of the Bytebase UI.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        Briefly describe the problem you are having in a few paragraphs.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Provide the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        3. Click on '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        Describe what you expect to happen.
    validations:
      required: true
  - type: input
    attributes:
      label: Provide the database you are using
      description: |
        Provide the database type and version (e.g. MySQL 8.0) you are using if related to a database operation.
  - type: input
    attributes:
      label: Provide the version control system you are using
      description: |
        Provide the version control system type and version (e.g. GitLab CE 16.5.4) you are using if related to GitOps integration
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
