export enum GeneralErrorCode {
  OK = 0,
  INTERNAL = 1,
  NOT_AUTHORIZED = 2,
  INVALID = 3,
  NOT_FOUND = 4,
  CONFLICT = 5,
  NOT_IMPLEMENTED = 6,
}

export enum DBErrorCode {
  CONNECTION_ERROR = 101,
  SYNTAX_ERROR = 102,
  EXECUTION_ERROR = 103,
}

export enum MigrationErrorCode {
  MIGRATION_SCHEMA_MISSING = 201,
  MIGRATION_ALREADY_APPLIED = 202,
  MIGRATION_OUT_OF_ORDER = 203,
  MIGRATION_BASELINE_MISSING = 204,
}

export enum SQLReviewPolicyErrorCode {
  EMPTY_POLICY = 2,
  STATEMENT_SYNTAX_ERROR = 201,
  STATEMENT_NO_WHERE = 202,
  STATEMENT_NO_SELECT_ALL = 203,
  STATEMENT_LEADING_WILDCARD_LIKE = 204,
  STATEMENT_CREATE_TABLE_AS = 205,
  STATEMENT_DISALLOW_COMMIT = 206,
  STATEMENT_REDUNDANT_ALTER_TABLE = 207,
  STATEMENT_DML_DRY_RUN_FAILED = 208,
  STATEMENT_AFFECTED_ROW_EXCEEDS_LIMIT = 209,
  STATEMENT_ADD_COLUMN_WITH_DEFAULT = 210,
  STATEMENT_ADD_CHECK_WITH_VALIDATION = 211,
  STATEMENT_ADD_NOT_NULL = 212,
  STATEMENT_DISALLOW_CASCADE = 213,
  TABLE_NAMING_MISMATCH = 301,
  COLUMN_NAMING_MISMATCH = 302,
  INDEX_NAMING_MISMATCH = 303,
  UK_NAMING_MISMATCH = 304,
  FK_NAMING_MISMATCH = 305,
  PK_NAMING_MISMATCH = 306,
  NAMING_AUTO_INCREMENT_COLUMN_CONVENTION_MISMATCH = 307,
  NAMING_IS_KEYWORD_IDENTIFIER = 308,
  NAMING_CASE_MISMATCH = 309,
  NO_REQUIRED_COLUMN = 401,
  COLUMN_CANBE_NULL = 402,
  CHANGE_COLUMN_TYPE = 403,
  NOT_NULL_COLUMN_WITH_NO_DEFAULT = 404,
  COLUMN_NOT_EXISTS = 405,
  USE_CHANGE_COLUMN_STATEMENT = 406,
  CHANGE_COLUMN_ORDER = 407,
  NO_COLUMN_COMMENT = 408,
  COLUMN_COMMENT_TOO_LONG = 409,
  AUTO_INCREMENT_COLUMN_NOT_INTEGER = 410,
  DISABLED_COLUMN_TYPE = 411,
  COLUMN_EXISTS = 412,
  DROP_ALL_COLUMNS = 413,
  SET_COLUMN_CHARSET = 414,
  CHAR_LENGTH_EXCEEDS_LIMIT = 415,
  AUTO_INCREMENT_COLUMN_INITIAL_VALUE_NOT_MATCH = 416,
  AUTO_INCREMENT_COLUMN_SIGNED = 417,
  DEFAULT_CURRENT_TIME_COLUMN_COUNT_EXCEEDS_LIMIT = 418,
  ON_UPDATE_CURRENT_TIME_COLUMN_COUNT_EXCEEDS_LIMIT = 419,
  NO_DEFAULT = 420,
  COLUMN_IS_REFERENCED_BY_VIEW = 421,
  VARCHAR_LENGTH_EXCEEDS_LIMIT = 422,
  NOT_INNODB_ENGINE = 501,
  NO_PK_IN_TABLE = 601,
  FK_IN_TABLE = 602,
  TABLE_DROP_NAMING_CONVENTION = 603,
  TABLE_NOT_EXISTS = 604,
  NO_TABLE_COMMENT = 605,
  TABLE_COMMENT_TOO_LONG = 606,
  TABLE_EXISTS = 607,
  CREATE_TABLE_PARTITION = 608,
  TABLE_IS_REFERENCED_BY_VIEW = 609,
  CREATE_TABLE_TRIGGER = 610,
  DATABASE_NOT_EMPTY = 701,
  NOT_CURRENT_DATABASE = 702,
  DATABASE_IS_DELETED = 703,
  NOT_USE_INDEX = 801,
  INDEX_KEY_NUMBER_EXCEEDS_LIMIT = 802,
  INDEX_PK_TYPE = 803,
  INDEX_TYPE_NO_BLOB = 804,
  INDEX_EXISTS = 805,
  PRIMARY_KEY_EXISTS = 806,
  INDEX_EMPTY_KEYS = 807,
  PRIMARY_KEY_NOT_EXISTS = 808,
  INDEX_NOT_EXISTS = 809,
  INCORRECT_INDEX_NAME = 810,
  SPATIAL_INDEX_KEY_NULLABLE = 811,
  DUPLICATE_COLUMN_IN_INDEX = 812,
  INDEX_COUNT_EXCEEDS_LIMIT = 813,
  CREATE_INDEX_UNCONCURRENTLY = 814,
  DISABLED_CHARSET = 1001,
  INSERT_TOO_MANY_ROWS = 1101,
  UPDATE_USE_LIMIT = 1102,
  INSERT_USE_LIMIT = 1103,
  UPDATE_USE_ORDER_BY = 1104,
  DELETE_USE_ORDER_BY = 1105,
  DELETE_USE_LIMIT = 1106,
  INSERT_NOT_SPECIFY_COLUMN = 1107,
  INSERT_USE_ORDER_BY_RAND = 1108,
  DISABLED_COLLATION = 1201,
  COMMENT_TOO_LONG = 1301,
  CREATE_PROCEDURE = 1401,
}

export enum CompatibilityErrorCode {
  COMPATIBILITY_DROP_DATABASE = 101,
  COMPATIBILITY_RENAME_TABLE = 102,
  COMPATIBILITY_DROP_TABLE = 103,
  COMPATIBILITY_RENAME_COLUMN = 104,
  COMPATIBILITY_DROP_COLUMN = 105,
  COMPATIBILITY_ADD_PRIMARY_KEY = 106,
  COMPATIBILITY_ADD_UNIQUE_KEY = 107,
  COMPATIBILITY_ADD_FOREIGN_KEY = 108,
  COMPATIBILITY_ADD_CHECK = 109,
  COMPATIBILITY_ALTER_CHECK = 110,
  COMPATIBILITY_ALTER_COLUMN = 111,
}

export type ErrorCode =
  | GeneralErrorCode
  | DBErrorCode
  | MigrationErrorCode
  | CompatibilityErrorCode
  | SQLReviewPolicyErrorCode;

export type ErrorTag = "General" | "Compatibility";

export type ErrorMeta = {
  code: ErrorCode;
  hash: string;
};
