---
categoryList:
  - ENGINE
  - NAMING
  - STATEMENT
  - TABLE
  - SCHEMA
  - COLUMN
templateList:
  - id: mysql.prod
    ruleList:
      - type: engine.mysql.use-innodb
        category: ENGINE
        engine: MYSQL
        level: ERROR
        componentList: []
      - type: table.require-pk
        category: TABLE
        engine: COMMON
        level: ERROR
        componentList: []
      - type: table.no-foreign-key
        category: TABLE
        engine: COMMON
        level: ERROR
        componentList: []
      - type: statement.select.no-select-all
        category: STATEMENT
        engine: COMMON
        level: ERROR
        componentList: []
      - type: statement.where.require
        category: STATEMENT
        engine: COMMON
        level: ERROR
        componentList: []
      - type: statement.where.no-leading-wildcard-like
        category: STATEMENT
        engine: COMMON
        level: ERROR
        componentList: []
      - type: naming.table
        category: NAMING
        engine: COMMON
        componentList:
          - key: name_format
            payload:
              type: STRING
              default: "^[a-z]+(_[a-z]+)*$"
          - key: length_limit
            payload:
              type: NUMBER
              default: 64
        level: WARNING
      - type: naming.column
        category: NAMING
        engine: COMMON
        componentList:
          - key: name_format
            payload:
              type: STRING
              default: "^[a-z]+(_[a-z]+)*$"
          - key: length_limit
            payload:
              type: NUMBER
              default: 64
        level: WARNING
      - type: naming.index.uk
        category: NAMING
        engine: COMMON
        componentList:
          - key: name_format
            payload:
              type: TEMPLATE
              default: "^uk_{{table}}_{{column_list}}$"
              templateList:
                - table
                - column_list
          - key: length_limit
            payload:
              type: NUMBER
              default: 64
        level: WARNING
      - type: naming.index.idx
        category: NAMING
        engine: COMMON
        componentList:
          - key: name_format
            payload:
              type: TEMPLATE
              default: "^idx_{{table}}_{{column_list}}$"
              templateList:
                - table
                - column_list
          - key: length_limit
            payload:
              type: NUMBER
              default: 64
        level: WARNING
      - type: naming.index.fk
        category: NAMING
        engine: COMMON
        componentList:
          - key: name_format
            payload:
              type: TEMPLATE
              default: "^fk_{{referencing_table}}_{{referencing_column}}_{{referenced_table}}_{{referenced_column}}$"
              templateList:
                - referencing_table
                - referencing_column
                - referenced_table
                - referenced_column
          - key: length_limit
            payload:
              type: NUMBER
              default: 64
        level: WARNING
      - type: column.required
        category: COLUMN
        engine: COMMON
        componentList:
          - key: column_list
            payload:
              type: STRING_ARRAY
              default:
                - id
                - created_ts
                - updated_ts
                - creator_id
                - updater_id
        level: WARNING
      - type: column.no-null
        category: COLUMN
        engine: COMMON
        level: WARNING
        componentList: []
      - type: schema.backward-compatibility
        category: SCHEMA
        engine: MYSQL
        level: WARNING
        componentList: []
  - id: mysql.dev
    ruleList:
      - type: engine.mysql.use-innodb
        category: ENGINE
        engine: MYSQL
        level: ERROR
        componentList: []
      - type: table.require-pk
        category: TABLE
        engine: COMMON
        level: ERROR
        componentList: []
      - type: table.no-foreign-key
        category: TABLE
        engine: COMMON
        level: WARNING
        componentList: []
      - type: naming.table
        category: NAMING
        engine: COMMON
        componentList:
          - key: name_format
            payload:
              type: STRING
              default: "^[a-z]+(_[a-z]+)*$"
          - key: length_limit
            payload:
              type: NUMBER
              default: 64
        level: WARNING
      - type: naming.column
        category: NAMING
        engine: COMMON
        componentList:
          - key: name_format
            payload:
              type: STRING
              default: "^[a-z]+(_[a-z]+)*$"
          - key: length_limit
            payload:
              type: NUMBER
              default: 64
        level: WARNING
      - type: naming.index.uk
        category: NAMING
        engine: COMMON
        componentList:
          - key: name_format
            payload:
              type: TEMPLATE
              default: "^uk_{{table}}_{{column_list}}$"
              templateList:
                - table
                - column_list
          - key: length_limit
            payload:
              type: NUMBER
              default: 64
        level: WARNING
      - type: naming.index.idx
        category: NAMING
        engine: COMMON
        componentList:
          - key: name_format
            payload:
              type: TEMPLATE
              default: "^idx_{{table}}_{{column_list}}$"
              templateList:
                - table
                - column_list
          - key: length_limit
            payload:
              type: NUMBER
              default: 64
        level: WARNING
      - type: naming.index.fk
        category: NAMING
        engine: COMMON
        componentList:
          - key: name_format
            payload:
              type: TEMPLATE
              default: "^fk_{{referencing_table}}_{{referencing_column}}_{{referenced_table}}_{{referenced_column}}$"
              templateList:
                - referencing_table
                - referencing_column
                - referenced_table
                - referenced_column
          - key: length_limit
            payload:
              type: NUMBER
              default: 64
        level: WARNING
      - type: column.required
        category: COLUMN
        engine: COMMON
        componentList:
          - key: column_list
            payload:
              type: STRING_ARRAY
              default:
                - id
                - created_ts
                - updated_ts
                - creator_id
                - updater_id
        level: WARNING
      - type: column.no-null
        category: COLUMN
        engine: COMMON
        level: WARNING
        componentList: []
      - type: statement.select.no-select-all
        category: STATEMENT
        engine: COMMON
        level: WARNING
        componentList: []
      - type: statement.where.require
        category: STATEMENT
        engine: COMMON
        level: WARNING
        componentList: []
      - type: statement.where.no-leading-wildcard-like
        category: STATEMENT
        engine: COMMON
        level: WARNING
        componentList: []
      - type: schema.backward-compatibility
        category: SCHEMA
        engine: MYSQL
        level: WARNING
        componentList: []
