basePath: /v1/
definitions:
  advisor.Advice:
    properties:
      code:
        description: Code is the SQL check error code.
        type: integer
      content:
        type: string
      status:
        description: Status is the SQL check result. Could be "SUCCESS", "WARN", "ERROR"
        type: string
      title:
        type: string
    type: object
  echo.HTTPError:
    properties:
      message: {}
    type: object
host: localhost:8081
info:
  contact:
    email: support@bytebase.com
    name: API Support
    url: https://github.com/bytebase/bytebase/
  description: The OpenAPI for Bytebase SQL Service.
  license:
    name: MIT
    url: https://github.com/bytebase/bytebase/blob/main/LICENSE
  termsOfService: https://www.bytebase.com/terms
  title: Bytebase SQL Service
  version: "1.0"
paths:
  /sql/advise:
    get:
      consumes:
        - "*/*"
      description: Parse and check the SQL statement according to the SQL review
        rules.
      parameters:
        - description: The SQL statement.
          in: query
          name: statement
          required: true
          type: string
        - description: The database type.
          enum:
            - MYSQL
            - POSTGRES
            - TIDB
          in: query
          name: databaseType
          required: true
          type: string
        - description: The SQL check template id. Required if the config is not specified.
          enum:
            - bb.sql-review.prod
            - bb.sql-review.dev
          in: query
          name: template
          type: string
        - description:
            The SQL check config override string in YAML format. Check https://github.com/bytebase/bytebase/tree/main/plugin/advisor/config/sql-review.override.yaml
            for example. Required if the template is not specified.
          in: query
          name: override
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: "#/definitions/advisor.Advice"
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/echo.HTTPError"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/echo.HTTPError"
      summary: Check the SQL statement.
      tags:
        - SQL review
schemes:
  - http
swagger: "2.0"
