// SQL Editor mutation types
export const SET_SQL_EDITOR_STATE = "SET_SQL_EDITOR_STATE";
export const SET_CONNECTION_TREE = "SET_CONNECTION_TREE";
export const SET_CONNECTION_CONTEXT = "SET_CONNECTION_CONTEXT";
export const SET_SHOULD_SET_CONTENT = "SET_SHOULD_SET_CONTENT";
export const SET_IS_EXECUTING = "SET_IS_EXECUTING";
export const SET_QUERY_HISTORY_LIST = "SET_QUERY_HISTORY_LIST";
export const SET_IS_FETCHING_QUERY_HISTORY = "SET_IS_FETCHING_QUERY_HISTORY";
export const SET_SAVED_QUERY_LIST = "SET_SAVED_QUERY_LIST";
export const SET_IS_FETCHING_SAVED_QUERIES = "SET_IS_FETCHING_SAVED_QUERIES";

// Editor Selector mutation types
export const SET_TAB_STATE = "SET_TAB_STATE";
export const ADD_TAB = "ADD_TAB";
export const REMOVE_TAB = "REMOVE_TAB";
export const UPDATE_TAB = "UPDATE_TAB";
export const UPDATE_ACTIVE_TAB = "UPDATE_ACTIVE_TAB";
export const SET_ACTIVE_TAB_ID = "SET_ACTIVE_TAB_ID";
