// SQL Editor mutation types
export const SET_SQL_EDITOR_STATE = "SET_SQL_EDITOR_STATE";
export const SET_CONNECTION_TREE = "SET_CONNECTION_TREE";
export const SET_CONNECTION_CONTEXT = "SET_CONNECTION_CONTEXT";
export const SET_SHOULD_SET_CONTENT = "SET_SHOULD_SET_CONTENT";
export const SET_SHOULD_FORMAT_CONTENT = "SET_SHOULD_FORMAT_CONTENT";
export const SET_IS_EXECUTING = "SET_IS_EXECUTING";
export const SET_QUERY_HISTORY_LIST = "SET_QUERY_HISTORY_LIST";
export const SET_IS_FETCHING_QUERY_HISTORY = "SET_IS_FETCHING_QUERY_HISTORY";

// Editor Selector mutation types
export const SET_TAB_STATE = "SET_TAB_STATE";
export const ADD_TAB = "ADD_TAB";
export const REMOVE_TAB = "REMOVE_TAB";
export const UPDATE_TAB = "UPDATE_TAB";
export const UPDATE_CURRENT_TAB = "UPDATE_CURRENT_TAB";
export const SET_CURRENT_TAB_ID = "SET_CURRENT_TAB_ID";

// Sheet mutation types
export const SET_SHEET_STATE = "SET_SHEET_STATE";
export const SET_SHEET_LIST = "SET_SHEET_LIST";
export const SET_SHEET_BY_ID = "SET_SHEET_BY_ID";
export const DELETE_SHEET = "DELETE_SHEET";
