package store

import "github.com/bytebase/bytebase/backend/common/permission"

// Predefined role IDs.
const (
	WorkspaceAdminRole     = "workspaceAdmin"
	WorkspaceDBARole       = "workspaceDBA"
	WorkspaceMemberRole    = "workspaceMember"
	ProjectOwnerRole       = "projectOwner"
	ProjectDeveloperRole   = "projectDeveloper"
	SQLEditorUserRole      = "sqlEditorUser"
	ProjectReleaserRole    = "projectReleaser"
	GitOpsServiceAgentRole = "gitopsServiceAgent"
	ProjectViewerRole      = "projectViewer"
)

func permissionSet(perms ...permission.Permission) map[string]bool {
	m := make(map[string]bool, len(perms))
	for _, p := range perms {
		m[p] = true
	}
	return m
}

// PredefinedRoles contains all predefined roles.
var PredefinedRoles = []*RoleMessage{
	{
		ResourceID: WorkspaceAdminRole,
		Name:       "Workspace admin",
		Predefined: true,
		Permissions: permissionSet(
			permission.PermissionAuditLogsExport,
			permission.PermissionAuditLogsSearch,
			permission.PermissionChangelogsGet,
			permission.PermissionChangelogsList,
			permission.PermissionDatabaseCatalogsGet,
			permission.PermissionDatabaseCatalogsUpdate,
			permission.PermissionDatabaseGroupsCreate,
			permission.PermissionDatabaseGroupsDelete,
			permission.PermissionDatabaseGroupsGet,
			permission.PermissionDatabaseGroupsList,
			permission.PermissionDatabaseGroupsUpdate,
			permission.PermissionDatabasesCheck,
			permission.PermissionDatabasesGet,
			permission.PermissionDatabasesGetSchema,
			permission.PermissionDatabasesList,
			permission.PermissionDatabasesSync,
			permission.PermissionDatabasesUpdate,
			permission.PermissionIdentityProvidersCreate,
			permission.PermissionIdentityProvidersDelete,
			permission.PermissionIdentityProvidersGet,
			permission.PermissionIdentityProvidersUpdate,
			permission.PermissionInstancesCreate,
			permission.PermissionInstancesDelete,
			permission.PermissionInstancesGet,
			permission.PermissionInstancesList,
			permission.PermissionInstancesSync,
			permission.PermissionInstancesUndelete,
			permission.PermissionInstancesUpdate,
			permission.PermissionInstanceRolesGet,
			permission.PermissionInstanceRolesList,
			permission.PermissionIssueCommentsCreate,
			permission.PermissionIssueCommentsList,
			permission.PermissionIssueCommentsUpdate,
			permission.PermissionIssuesCreate,
			permission.PermissionIssuesGet,
			permission.PermissionIssuesList,
			permission.PermissionIssuesUpdate,
			permission.PermissionPlanCheckRunsGet,
			permission.PermissionPlanCheckRunsRun,
			permission.PermissionPlansCreate,
			permission.PermissionPlansGet,
			permission.PermissionPlansList,
			permission.PermissionPlansUpdate,
			permission.PermissionPoliciesCreate,
			permission.PermissionPoliciesDelete,
			permission.PermissionPoliciesGet,
			permission.PermissionPoliciesList,
			permission.PermissionPoliciesUpdate,
			permission.PermissionPoliciesCreateMaskingExemptionPolicy,
			permission.PermissionPoliciesUpdateMaskingExemptionPolicy,
			permission.PermissionPoliciesDeleteMaskingExemptionPolicy,
			permission.PermissionPoliciesGetMaskingExemptionPolicy,
			permission.PermissionPoliciesCreateMaskingRulePolicy,
			permission.PermissionPoliciesUpdateMaskingRulePolicy,
			permission.PermissionPoliciesDeleteMaskingRulePolicy,
			permission.PermissionPoliciesGetMaskingRulePolicy,
			permission.PermissionProjectsCreate,
			permission.PermissionProjectsDelete,
			permission.PermissionProjectsGet,
			permission.PermissionProjectsGetIAMPolicy,
			permission.PermissionProjectsList,
			permission.PermissionProjectsSetIAMPolicy,
			permission.PermissionProjectsUndelete,
			permission.PermissionProjectsUpdate,
			permission.PermissionReleasesCheck,
			permission.PermissionReleasesCreate,
			permission.PermissionReleasesDelete,
			permission.PermissionReleasesGet,
			permission.PermissionReleasesList,
			permission.PermissionReleasesUndelete,
			permission.PermissionReleasesUpdate,
			permission.PermissionReviewConfigsCreate,
			permission.PermissionReviewConfigsDelete,
			permission.PermissionReviewConfigsGet,
			permission.PermissionReviewConfigsList,
			permission.PermissionReviewConfigsUpdate,
			permission.PermissionRevisionsCreate,
			permission.PermissionRevisionsDelete,
			permission.PermissionRevisionsGet,
			permission.PermissionRevisionsList,
			permission.PermissionRolesCreate,
			permission.PermissionRolesDelete,
			permission.PermissionRolesList,
			permission.PermissionRolesGet,
			permission.PermissionRolesUpdate,
			permission.PermissionRolloutsCreate,
			permission.PermissionRolloutsGet,
			permission.PermissionRolloutsList,
			permission.PermissionSettingsGet,
			permission.PermissionEnvironmentSettingsGet,
			permission.PermissionWorkspaceProfileSettingsGet,
			permission.PermissionSettingsList,
			permission.PermissionSettingsSet,
			permission.PermissionEnvironmentSettingsSet,
			permission.PermissionWorkspaceProfileSettingsSet,
			permission.PermissionSheetsCreate,
			permission.PermissionSheetsGet,
			permission.PermissionSheetsUpdate,
			permission.PermissionTaskRunsCreate,
			permission.PermissionTaskRunsList,
			permission.PermissionGroupsCreate,
			permission.PermissionGroupsDelete,
			permission.PermissionGroupsGet,
			permission.PermissionGroupsList,
			permission.PermissionGroupsUpdate,
			permission.PermissionSQLAdmin,
			permission.PermissionSQLDdl,
			permission.PermissionSQLDml,
			permission.PermissionSQLExplain,
			permission.PermissionSQLInfo,
			permission.PermissionSQLSelect,
			permission.PermissionUsersCreate,
			permission.PermissionUsersDelete,
			permission.PermissionUsersGet,
			permission.PermissionUsersList,
			permission.PermissionUsersUndelete,
			permission.PermissionUsersUpdate,
			permission.PermissionUsersUpdateEmail,
			permission.PermissionWorksheetsGet,
			permission.PermissionWorksheetsManage,
			permission.PermissionWorkspacesGetIamPolicy,
			permission.PermissionWorkspacesSetIamPolicy,
		),
	},
	{
		ResourceID: WorkspaceDBARole,
		Name:       "Workspace DBA",
		Predefined: true,
		Permissions: permissionSet(
			permission.PermissionAuditLogsExport,
			permission.PermissionAuditLogsSearch,
			permission.PermissionChangelogsGet,
			permission.PermissionChangelogsList,
			permission.PermissionDatabaseCatalogsGet,
			permission.PermissionDatabaseCatalogsUpdate,
			permission.PermissionDatabaseGroupsCreate,
			permission.PermissionDatabaseGroupsDelete,
			permission.PermissionDatabaseGroupsGet,
			permission.PermissionDatabaseGroupsList,
			permission.PermissionDatabaseGroupsUpdate,
			permission.PermissionDatabasesCheck,
			permission.PermissionDatabasesGet,
			permission.PermissionDatabasesGetSchema,
			permission.PermissionDatabasesList,
			permission.PermissionDatabasesSync,
			permission.PermissionDatabasesUpdate,
			permission.PermissionInstancesCreate,
			permission.PermissionInstancesDelete,
			permission.PermissionInstancesGet,
			permission.PermissionInstancesList,
			permission.PermissionInstancesSync,
			permission.PermissionInstancesUndelete,
			permission.PermissionInstancesUpdate,
			permission.PermissionInstanceRolesGet,
			permission.PermissionInstanceRolesList,
			permission.PermissionIssueCommentsCreate,
			permission.PermissionIssueCommentsList,
			permission.PermissionIssueCommentsUpdate,
			permission.PermissionIssuesCreate,
			permission.PermissionIssuesGet,
			permission.PermissionIssuesList,
			permission.PermissionIssuesUpdate,
			permission.PermissionPlanCheckRunsGet,
			permission.PermissionPlanCheckRunsRun,
			permission.PermissionPlansCreate,
			permission.PermissionPlansGet,
			permission.PermissionPlansList,
			permission.PermissionPlansUpdate,
			permission.PermissionPoliciesCreate,
			permission.PermissionPoliciesDelete,
			permission.PermissionPoliciesGet,
			permission.PermissionPoliciesList,
			permission.PermissionPoliciesUpdate,
			permission.PermissionPoliciesCreateMaskingExemptionPolicy,
			permission.PermissionPoliciesUpdateMaskingExemptionPolicy,
			permission.PermissionPoliciesDeleteMaskingExemptionPolicy,
			permission.PermissionPoliciesGetMaskingExemptionPolicy,
			permission.PermissionPoliciesCreateMaskingRulePolicy,
			permission.PermissionPoliciesUpdateMaskingRulePolicy,
			permission.PermissionPoliciesDeleteMaskingRulePolicy,
			permission.PermissionPoliciesGetMaskingRulePolicy,
			permission.PermissionProjectsCreate,
			permission.PermissionProjectsDelete,
			permission.PermissionProjectsGet,
			permission.PermissionProjectsGetIAMPolicy,
			permission.PermissionProjectsList,
			permission.PermissionProjectsSetIAMPolicy,
			permission.PermissionProjectsUndelete,
			permission.PermissionProjectsUpdate,
			permission.PermissionReleasesCheck,
			permission.PermissionReleasesCreate,
			permission.PermissionReleasesDelete,
			permission.PermissionReleasesGet,
			permission.PermissionReleasesList,
			permission.PermissionReleasesUndelete,
			permission.PermissionReleasesUpdate,
			permission.PermissionReviewConfigsCreate,
			permission.PermissionReviewConfigsDelete,
			permission.PermissionReviewConfigsGet,
			permission.PermissionReviewConfigsList,
			permission.PermissionReviewConfigsUpdate,
			permission.PermissionRevisionsCreate,
			permission.PermissionRevisionsDelete,
			permission.PermissionRevisionsGet,
			permission.PermissionRevisionsList,
			permission.PermissionRolesCreate,
			permission.PermissionRolesDelete,
			permission.PermissionRolesList,
			permission.PermissionRolesGet,
			permission.PermissionRolesUpdate,
			permission.PermissionRolloutsCreate,
			permission.PermissionRolloutsGet,
			permission.PermissionRolloutsList,
			permission.PermissionSettingsGet,
			permission.PermissionEnvironmentSettingsGet,
			permission.PermissionWorkspaceProfileSettingsGet,
			permission.PermissionSettingsList,
			permission.PermissionSettingsSet,
			permission.PermissionEnvironmentSettingsSet,
			permission.PermissionWorkspaceProfileSettingsSet,
			permission.PermissionSheetsCreate,
			permission.PermissionSheetsGet,
			permission.PermissionSheetsUpdate,
			permission.PermissionSQLAdmin,
			permission.PermissionSQLDdl,
			permission.PermissionSQLDml,
			permission.PermissionSQLExplain,
			permission.PermissionSQLInfo,
			permission.PermissionSQLSelect,
			permission.PermissionUsersGet,
			permission.PermissionUsersList,
			permission.PermissionTaskRunsCreate,
			permission.PermissionTaskRunsList,
			permission.PermissionGroupsGet,
			permission.PermissionGroupsList,
			permission.PermissionWorksheetsGet,
			permission.PermissionWorksheetsManage,
			permission.PermissionWorkspacesGetIamPolicy,
		),
	},
	{
		ResourceID: WorkspaceMemberRole,
		Name:       "Workspace member",
		Predefined: true,
		Permissions: permissionSet(
			permission.PermissionInstanceRolesGet,
			permission.PermissionInstanceRolesList,
			permission.PermissionPoliciesGet,
			permission.PermissionReviewConfigsGet,
			permission.PermissionReviewConfigsList,
			permission.PermissionRolesList,
			permission.PermissionRolesGet,
			permission.PermissionEnvironmentSettingsGet,
			permission.PermissionWorkspaceProfileSettingsGet,
			permission.PermissionGroupsCreate,
			permission.PermissionGroupsGet,
			permission.PermissionGroupsList,
			permission.PermissionUsersGet,
			permission.PermissionUsersList,
			permission.PermissionWorkspacesGetIamPolicy,
		),
	},
	{
		ResourceID: ProjectOwnerRole,
		Name:       "Project owner",
		Predefined: true,
		Permissions: permissionSet(
			permission.PermissionAuditLogsExport,
			permission.PermissionAuditLogsSearch,
			permission.PermissionChangelogsGet,
			permission.PermissionChangelogsList,
			permission.PermissionDatabaseCatalogsGet,
			permission.PermissionDatabaseCatalogsUpdate,
			permission.PermissionDatabaseGroupsCreate,
			permission.PermissionDatabaseGroupsDelete,
			permission.PermissionDatabaseGroupsGet,
			permission.PermissionDatabaseGroupsList,
			permission.PermissionDatabaseGroupsUpdate,
			permission.PermissionDatabasesCheck,
			permission.PermissionDatabasesGet,
			permission.PermissionDatabasesGetSchema,
			permission.PermissionDatabasesList,
			permission.PermissionDatabasesSync,
			permission.PermissionDatabasesUpdate,
			permission.PermissionIssueCommentsCreate,
			permission.PermissionIssueCommentsList,
			permission.PermissionIssueCommentsUpdate,
			permission.PermissionIssuesCreate,
			permission.PermissionIssuesGet,
			permission.PermissionIssuesList,
			permission.PermissionIssuesUpdate,
			permission.PermissionPlanCheckRunsGet,
			permission.PermissionPlanCheckRunsRun,
			permission.PermissionPlansCreate,
			permission.PermissionPlansGet,
			permission.PermissionPlansList,
			permission.PermissionPlansUpdate,
			permission.PermissionPoliciesCreate,
			permission.PermissionPoliciesDelete,
			permission.PermissionPoliciesGet,
			permission.PermissionPoliciesList,
			permission.PermissionPoliciesUpdate,
			permission.PermissionPoliciesCreateMaskingExemptionPolicy,
			permission.PermissionPoliciesUpdateMaskingExemptionPolicy,
			permission.PermissionPoliciesDeleteMaskingExemptionPolicy,
			permission.PermissionPoliciesGetMaskingExemptionPolicy,
			permission.PermissionPoliciesCreateMaskingRulePolicy,
			permission.PermissionPoliciesUpdateMaskingRulePolicy,
			permission.PermissionPoliciesDeleteMaskingRulePolicy,
			permission.PermissionPoliciesGetMaskingRulePolicy,
			permission.PermissionProjectsGet,
			permission.PermissionProjectsGetIAMPolicy,
			permission.PermissionProjectsSetIAMPolicy,
			permission.PermissionProjectsUpdate,
			permission.PermissionReleasesCheck,
			permission.PermissionReleasesCreate,
			permission.PermissionReleasesDelete,
			permission.PermissionReleasesGet,
			permission.PermissionReleasesList,
			permission.PermissionReleasesUndelete,
			permission.PermissionReleasesUpdate,
			permission.PermissionRevisionsCreate,
			permission.PermissionRevisionsDelete,
			permission.PermissionRevisionsGet,
			permission.PermissionRevisionsList,
			permission.PermissionRolloutsCreate,
			permission.PermissionRolloutsGet,
			permission.PermissionRolloutsList,
			permission.PermissionSheetsCreate,
			permission.PermissionSheetsGet,
			permission.PermissionSheetsUpdate,
			permission.PermissionSQLDdl,
			permission.PermissionSQLDml,
			permission.PermissionSQLExplain,
			permission.PermissionSQLInfo,
			permission.PermissionSQLSelect,
			permission.PermissionUsersGet,
			permission.PermissionUsersList,
			permission.PermissionTaskRunsList,
			permission.PermissionWorksheetsGet,
		),
	},
	{
		ResourceID: ProjectDeveloperRole,
		Name:       "Project developer",
		Predefined: true,
		Permissions: permissionSet(
			permission.PermissionAuditLogsSearch,
			permission.PermissionChangelogsGet,
			permission.PermissionChangelogsList,
			permission.PermissionDatabaseCatalogsGet,
			permission.PermissionDatabaseGroupsGet,
			permission.PermissionDatabaseGroupsList,
			permission.PermissionDatabasesCheck,
			permission.PermissionDatabasesGet,
			permission.PermissionDatabasesGetSchema,
			permission.PermissionDatabasesList,
			permission.PermissionDatabasesSync,
			permission.PermissionIssueCommentsCreate,
			permission.PermissionIssueCommentsList,
			permission.PermissionIssueCommentsUpdate,
			permission.PermissionIssuesCreate,
			permission.PermissionIssuesGet,
			permission.PermissionIssuesList,
			permission.PermissionIssuesUpdate,
			permission.PermissionPlanCheckRunsGet,
			permission.PermissionPlanCheckRunsRun,
			permission.PermissionPlansCreate,
			permission.PermissionPlansGet,
			permission.PermissionPlansList,
			permission.PermissionProjectsGet,
			permission.PermissionProjectsGetIAMPolicy,
			permission.PermissionReleasesCheck,
			permission.PermissionReleasesGet,
			permission.PermissionReleasesList,
			permission.PermissionRevisionsGet,
			permission.PermissionRevisionsList,
			permission.PermissionRolloutsCreate,
			permission.PermissionRolloutsGet,
			permission.PermissionRolloutsList,
			permission.PermissionSheetsCreate,
			permission.PermissionSheetsGet,
			permission.PermissionSheetsUpdate,
			permission.PermissionTaskRunsList,
		),
	},
	{
		ResourceID: SQLEditorUserRole,
		Name:       "SQL Editor User",
		Predefined: true,
		Permissions: permissionSet(
			permission.PermissionDatabaseCatalogsGet,
			permission.PermissionDatabaseGroupsGet,
			permission.PermissionDatabaseGroupsList,
			permission.PermissionDatabasesCheck,
			permission.PermissionDatabasesGet,
			permission.PermissionDatabasesGetSchema,
			permission.PermissionDatabasesList,
			permission.PermissionDatabasesSync,
			permission.PermissionProjectsGet,
			permission.PermissionProjectsGetIAMPolicy,
			permission.PermissionSQLDdl,
			permission.PermissionSQLDml,
			permission.PermissionSQLExplain,
			permission.PermissionSQLInfo,
			permission.PermissionSQLSelect,
			permission.PermissionWorksheetsGet,
		),
	},
	{
		ResourceID: ProjectReleaserRole,
		Name:       "Project releaser",
		Predefined: true,
		Permissions: permissionSet(
			permission.PermissionDatabaseCatalogsGet,
			permission.PermissionChangelogsGet,
			permission.PermissionDatabaseGroupsGet,
			permission.PermissionDatabaseGroupsList,
			permission.PermissionDatabasesCheck,
			permission.PermissionDatabasesGet,
			permission.PermissionDatabasesGetSchema,
			permission.PermissionDatabasesList,
			permission.PermissionIssueCommentsCreate,
			permission.PermissionIssueCommentsList,
			permission.PermissionIssueCommentsUpdate,
			permission.PermissionIssuesGet,
			permission.PermissionIssuesList,
			permission.PermissionPlanCheckRunsGet,
			permission.PermissionPlanCheckRunsRun,
			permission.PermissionPlansGet,
			permission.PermissionPlansList,
			permission.PermissionProjectsGet,
			permission.PermissionProjectsGetIAMPolicy,
			permission.PermissionReleasesGet,
			permission.PermissionReleasesList,
			permission.PermissionRevisionsGet,
			permission.PermissionRevisionsList,
			permission.PermissionRolloutsCreate,
			permission.PermissionRolloutsGet,
			permission.PermissionRolloutsList,
			permission.PermissionSheetsGet,
			permission.PermissionTaskRunsCreate,
			permission.PermissionTaskRunsList,
		),
	},
	{
		ResourceID: GitOpsServiceAgentRole,
		Name:       "GitOps Service Agent",
		Predefined: true,
		Permissions: permissionSet(
			permission.PermissionPlansCreate,
			permission.PermissionPlansGet,
			permission.PermissionReleasesCheck,
			permission.PermissionReleasesCreate,
			permission.PermissionReleasesGet,
			permission.PermissionRolloutsCreate,
			permission.PermissionRolloutsGet,
			permission.PermissionRolloutsList,
			permission.PermissionTaskRunsCreate,
			permission.PermissionTaskRunsList,
		),
	},
	{
		ResourceID: ProjectViewerRole,
		Name:       "Project viewer",
		Predefined: true,
		Permissions: permissionSet(
			permission.PermissionDatabaseCatalogsGet,
			permission.PermissionDatabaseGroupsGet,
			permission.PermissionDatabaseGroupsList,
			permission.PermissionDatabasesGet,
			permission.PermissionDatabasesGetSchema,
			permission.PermissionDatabasesList,
			permission.PermissionIssueCommentsCreate,
			permission.PermissionIssueCommentsList,
			permission.PermissionIssueCommentsUpdate,
			permission.PermissionIssuesCreate,
			permission.PermissionProjectsGet,
			permission.PermissionProjectsGetIAMPolicy,
			permission.PermissionIssuesGet,
		),
	},
}

var predefinedRolesMap = func() map[string]*RoleMessage {
	m := make(map[string]*RoleMessage, len(PredefinedRoles))
	for _, role := range PredefinedRoles {
		m[role.ResourceID] = role
	}
	return m
}()

// GetPredefinedRole returns the predefined role by ID.
func GetPredefinedRole(roleID string) *RoleMessage {
	return predefinedRolesMap[roleID]
}

// IsPredefinedRole returns true if the role ID is a predefined role.
func IsPredefinedRole(roleID string) bool {
	_, ok := predefinedRolesMap[roleID]
	return ok
}
