package store

import "github.com/bytebase/bytebase/backend/common/permission"

// Predefined role IDs.
const (
	WorkspaceAdminRole     = "workspaceAdmin"
	WorkspaceDBARole       = "workspaceDBA"
	WorkspaceMemberRole    = "workspaceMember"
	ProjectOwnerRole       = "projectOwner"
	ProjectDeveloperRole   = "projectDeveloper"
	SQLEditorUserRole      = "sqlEditorUser"
	ProjectReleaserRole    = "projectReleaser"
	GitOpsServiceAgentRole = "gitopsServiceAgent"
	ProjectViewerRole      = "projectViewer"
)

func permissionSet(perms ...permission.Permission) map[permission.Permission]bool {
	m := make(map[permission.Permission]bool, len(perms))
	for _, p := range perms {
		m[p] = true
	}
	return m
}

// PredefinedRoles contains all predefined roles.
var PredefinedRoles = []*RoleMessage{
	{
		ResourceID: WorkspaceAdminRole,
		Name:       "Workspace admin",
		Predefined: true,
		Permissions: permissionSet(
			permission.AuditLogsExport,
			permission.AuditLogsSearch,
			permission.ChangelogsGet,
			permission.ChangelogsList,
			permission.DatabaseCatalogsGet,
			permission.DatabaseCatalogsUpdate,
			permission.DatabaseGroupsCreate,
			permission.DatabaseGroupsDelete,
			permission.DatabaseGroupsGet,
			permission.DatabaseGroupsList,
			permission.DatabaseGroupsUpdate,
			permission.DatabasesCheck,
			permission.DatabasesGet,
			permission.DatabasesGetSchema,
			permission.DatabasesList,
			permission.DatabasesSync,
			permission.DatabasesUpdate,
			permission.IdentityProvidersCreate,
			permission.IdentityProvidersDelete,
			permission.IdentityProvidersGet,
			permission.IdentityProvidersUpdate,
			permission.InstancesCreate,
			permission.InstancesDelete,
			permission.InstancesGet,
			permission.InstancesList,
			permission.InstancesSync,
			permission.InstancesUndelete,
			permission.InstancesUpdate,
			permission.InstanceRolesGet,
			permission.InstanceRolesList,
			permission.IssueCommentsCreate,
			permission.IssueCommentsList,
			permission.IssueCommentsUpdate,
			permission.IssuesCreate,
			permission.IssuesGet,
			permission.IssuesList,
			permission.IssuesUpdate,
			permission.PlanCheckRunsGet,
			permission.PlanCheckRunsRun,
			permission.PlansCreate,
			permission.PlansGet,
			permission.PlansList,
			permission.PlansUpdate,
			permission.PoliciesCreate,
			permission.PoliciesDelete,
			permission.PoliciesGet,
			permission.PoliciesList,
			permission.PoliciesUpdate,
			permission.PoliciesCreateMaskingExemptionPolicy,
			permission.PoliciesUpdateMaskingExemptionPolicy,
			permission.PoliciesDeleteMaskingExemptionPolicy,
			permission.PoliciesGetMaskingExemptionPolicy,
			permission.PoliciesCreateMaskingRulePolicy,
			permission.PoliciesUpdateMaskingRulePolicy,
			permission.PoliciesDeleteMaskingRulePolicy,
			permission.PoliciesGetMaskingRulePolicy,
			permission.ProjectsCreate,
			permission.ProjectsDelete,
			permission.ProjectsGet,
			permission.ProjectsGetIAMPolicy,
			permission.ProjectsList,
			permission.ProjectsSetIAMPolicy,
			permission.ProjectsUndelete,
			permission.ProjectsUpdate,
			permission.ReleasesCheck,
			permission.ReleasesCreate,
			permission.ReleasesDelete,
			permission.ReleasesGet,
			permission.ReleasesList,
			permission.ReleasesUndelete,
			permission.ReleasesUpdate,
			permission.ReviewConfigsCreate,
			permission.ReviewConfigsDelete,
			permission.ReviewConfigsGet,
			permission.ReviewConfigsList,
			permission.ReviewConfigsUpdate,
			permission.RevisionsCreate,
			permission.RevisionsDelete,
			permission.RevisionsGet,
			permission.RevisionsList,
			permission.RolesCreate,
			permission.RolesDelete,
			permission.RolesList,
			permission.RolesGet,
			permission.RolesUpdate,
			permission.RolloutsCreate,
			permission.RolloutsGet,
			permission.RolloutsList,
			permission.SettingsGet,
			permission.EnvironmentSettingsGet,
			permission.WorkspaceProfileSettingsGet,
			permission.SettingsList,
			permission.SettingsSet,
			permission.EnvironmentSettingsSet,
			permission.WorkspaceProfileSettingsSet,
			permission.SheetsCreate,
			permission.SheetsGet,
			permission.SheetsUpdate,
			permission.TaskRunsCreate,
			permission.TaskRunsList,
			permission.GroupsCreate,
			permission.GroupsDelete,
			permission.GroupsGet,
			permission.GroupsList,
			permission.GroupsUpdate,
			permission.SQLAdmin,
			permission.SQLDdl,
			permission.SQLDml,
			permission.SQLExplain,
			permission.SQLInfo,
			permission.SQLSelect,
			permission.UsersCreate,
			permission.UsersDelete,
			permission.UsersGet,
			permission.UsersList,
			permission.UsersUndelete,
			permission.UsersUpdate,
			permission.UsersUpdateEmail,
			permission.WorksheetsGet,
			permission.WorksheetsManage,
			permission.WorkspacesGetIamPolicy,
			permission.WorkspacesSetIamPolicy,
		),
	},
	{
		ResourceID: WorkspaceDBARole,
		Name:       "Workspace DBA",
		Predefined: true,
		Permissions: permissionSet(
			permission.AuditLogsExport,
			permission.AuditLogsSearch,
			permission.ChangelogsGet,
			permission.ChangelogsList,
			permission.DatabaseCatalogsGet,
			permission.DatabaseCatalogsUpdate,
			permission.DatabaseGroupsCreate,
			permission.DatabaseGroupsDelete,
			permission.DatabaseGroupsGet,
			permission.DatabaseGroupsList,
			permission.DatabaseGroupsUpdate,
			permission.DatabasesCheck,
			permission.DatabasesGet,
			permission.DatabasesGetSchema,
			permission.DatabasesList,
			permission.DatabasesSync,
			permission.DatabasesUpdate,
			permission.InstancesCreate,
			permission.InstancesDelete,
			permission.InstancesGet,
			permission.InstancesList,
			permission.InstancesSync,
			permission.InstancesUndelete,
			permission.InstancesUpdate,
			permission.InstanceRolesGet,
			permission.InstanceRolesList,
			permission.IssueCommentsCreate,
			permission.IssueCommentsList,
			permission.IssueCommentsUpdate,
			permission.IssuesCreate,
			permission.IssuesGet,
			permission.IssuesList,
			permission.IssuesUpdate,
			permission.PlanCheckRunsGet,
			permission.PlanCheckRunsRun,
			permission.PlansCreate,
			permission.PlansGet,
			permission.PlansList,
			permission.PlansUpdate,
			permission.PoliciesCreate,
			permission.PoliciesDelete,
			permission.PoliciesGet,
			permission.PoliciesList,
			permission.PoliciesUpdate,
			permission.PoliciesCreateMaskingExemptionPolicy,
			permission.PoliciesUpdateMaskingExemptionPolicy,
			permission.PoliciesDeleteMaskingExemptionPolicy,
			permission.PoliciesGetMaskingExemptionPolicy,
			permission.PoliciesCreateMaskingRulePolicy,
			permission.PoliciesUpdateMaskingRulePolicy,
			permission.PoliciesDeleteMaskingRulePolicy,
			permission.PoliciesGetMaskingRulePolicy,
			permission.ProjectsCreate,
			permission.ProjectsDelete,
			permission.ProjectsGet,
			permission.ProjectsGetIAMPolicy,
			permission.ProjectsList,
			permission.ProjectsSetIAMPolicy,
			permission.ProjectsUndelete,
			permission.ProjectsUpdate,
			permission.ReleasesCheck,
			permission.ReleasesCreate,
			permission.ReleasesDelete,
			permission.ReleasesGet,
			permission.ReleasesList,
			permission.ReleasesUndelete,
			permission.ReleasesUpdate,
			permission.ReviewConfigsCreate,
			permission.ReviewConfigsDelete,
			permission.ReviewConfigsGet,
			permission.ReviewConfigsList,
			permission.ReviewConfigsUpdate,
			permission.RevisionsCreate,
			permission.RevisionsDelete,
			permission.RevisionsGet,
			permission.RevisionsList,
			permission.RolesCreate,
			permission.RolesDelete,
			permission.RolesList,
			permission.RolesGet,
			permission.RolesUpdate,
			permission.RolloutsCreate,
			permission.RolloutsGet,
			permission.RolloutsList,
			permission.SettingsGet,
			permission.EnvironmentSettingsGet,
			permission.WorkspaceProfileSettingsGet,
			permission.SettingsList,
			permission.SettingsSet,
			permission.EnvironmentSettingsSet,
			permission.WorkspaceProfileSettingsSet,
			permission.SheetsCreate,
			permission.SheetsGet,
			permission.SheetsUpdate,
			permission.SQLAdmin,
			permission.SQLDdl,
			permission.SQLDml,
			permission.SQLExplain,
			permission.SQLInfo,
			permission.SQLSelect,
			permission.UsersGet,
			permission.UsersList,
			permission.TaskRunsCreate,
			permission.TaskRunsList,
			permission.GroupsGet,
			permission.GroupsList,
			permission.WorksheetsGet,
			permission.WorksheetsManage,
			permission.WorkspacesGetIamPolicy,
		),
	},
	{
		ResourceID: WorkspaceMemberRole,
		Name:       "Workspace member",
		Predefined: true,
		Permissions: permissionSet(
			permission.InstanceRolesGet,
			permission.InstanceRolesList,
			permission.PoliciesGet,
			permission.ReviewConfigsGet,
			permission.ReviewConfigsList,
			permission.RolesList,
			permission.RolesGet,
			permission.EnvironmentSettingsGet,
			permission.WorkspaceProfileSettingsGet,
			permission.GroupsCreate,
			permission.GroupsGet,
			permission.GroupsList,
			permission.UsersGet,
			permission.UsersList,
			permission.WorkspacesGetIamPolicy,
		),
	},
	{
		ResourceID: ProjectOwnerRole,
		Name:       "Project owner",
		Predefined: true,
		Permissions: permissionSet(
			permission.AuditLogsExport,
			permission.AuditLogsSearch,
			permission.ChangelogsGet,
			permission.ChangelogsList,
			permission.DatabaseCatalogsGet,
			permission.DatabaseCatalogsUpdate,
			permission.DatabaseGroupsCreate,
			permission.DatabaseGroupsDelete,
			permission.DatabaseGroupsGet,
			permission.DatabaseGroupsList,
			permission.DatabaseGroupsUpdate,
			permission.DatabasesCheck,
			permission.DatabasesGet,
			permission.DatabasesGetSchema,
			permission.DatabasesList,
			permission.DatabasesSync,
			permission.DatabasesUpdate,
			permission.IssueCommentsCreate,
			permission.IssueCommentsList,
			permission.IssueCommentsUpdate,
			permission.IssuesCreate,
			permission.IssuesGet,
			permission.IssuesList,
			permission.IssuesUpdate,
			permission.PlanCheckRunsGet,
			permission.PlanCheckRunsRun,
			permission.PlansCreate,
			permission.PlansGet,
			permission.PlansList,
			permission.PlansUpdate,
			permission.PoliciesCreate,
			permission.PoliciesDelete,
			permission.PoliciesGet,
			permission.PoliciesList,
			permission.PoliciesUpdate,
			permission.PoliciesCreateMaskingExemptionPolicy,
			permission.PoliciesUpdateMaskingExemptionPolicy,
			permission.PoliciesDeleteMaskingExemptionPolicy,
			permission.PoliciesGetMaskingExemptionPolicy,
			permission.PoliciesCreateMaskingRulePolicy,
			permission.PoliciesUpdateMaskingRulePolicy,
			permission.PoliciesDeleteMaskingRulePolicy,
			permission.PoliciesGetMaskingRulePolicy,
			permission.ProjectsGet,
			permission.ProjectsGetIAMPolicy,
			permission.ProjectsSetIAMPolicy,
			permission.ProjectsUpdate,
			permission.ReleasesCheck,
			permission.ReleasesCreate,
			permission.ReleasesDelete,
			permission.ReleasesGet,
			permission.ReleasesList,
			permission.ReleasesUndelete,
			permission.ReleasesUpdate,
			permission.RevisionsCreate,
			permission.RevisionsDelete,
			permission.RevisionsGet,
			permission.RevisionsList,
			permission.RolloutsCreate,
			permission.RolloutsGet,
			permission.RolloutsList,
			permission.SheetsCreate,
			permission.SheetsGet,
			permission.SheetsUpdate,
			permission.SQLDdl,
			permission.SQLDml,
			permission.SQLExplain,
			permission.SQLInfo,
			permission.SQLSelect,
			permission.UsersGet,
			permission.UsersList,
			permission.TaskRunsList,
			permission.WorksheetsGet,
		),
	},
	{
		ResourceID: ProjectDeveloperRole,
		Name:       "Project developer",
		Predefined: true,
		Permissions: permissionSet(
			permission.AuditLogsSearch,
			permission.ChangelogsGet,
			permission.ChangelogsList,
			permission.DatabaseCatalogsGet,
			permission.DatabaseGroupsGet,
			permission.DatabaseGroupsList,
			permission.DatabasesCheck,
			permission.DatabasesGet,
			permission.DatabasesGetSchema,
			permission.DatabasesList,
			permission.DatabasesSync,
			permission.IssueCommentsCreate,
			permission.IssueCommentsList,
			permission.IssueCommentsUpdate,
			permission.IssuesCreate,
			permission.IssuesGet,
			permission.IssuesList,
			permission.IssuesUpdate,
			permission.PlanCheckRunsGet,
			permission.PlanCheckRunsRun,
			permission.PlansCreate,
			permission.PlansGet,
			permission.PlansList,
			permission.ProjectsGet,
			permission.ProjectsGetIAMPolicy,
			permission.ReleasesCheck,
			permission.ReleasesGet,
			permission.ReleasesList,
			permission.RevisionsGet,
			permission.RevisionsList,
			permission.RolloutsCreate,
			permission.RolloutsGet,
			permission.RolloutsList,
			permission.SheetsCreate,
			permission.SheetsGet,
			permission.SheetsUpdate,
			permission.TaskRunsList,
		),
	},
	{
		ResourceID: SQLEditorUserRole,
		Name:       "SQL Editor User",
		Predefined: true,
		Permissions: permissionSet(
			permission.DatabaseCatalogsGet,
			permission.DatabaseGroupsGet,
			permission.DatabaseGroupsList,
			permission.DatabasesCheck,
			permission.DatabasesGet,
			permission.DatabasesGetSchema,
			permission.DatabasesList,
			permission.DatabasesSync,
			permission.ProjectsGet,
			permission.ProjectsGetIAMPolicy,
			permission.SQLDdl,
			permission.SQLDml,
			permission.SQLExplain,
			permission.SQLInfo,
			permission.SQLSelect,
			permission.WorksheetsGet,
		),
	},
	{
		ResourceID: ProjectReleaserRole,
		Name:       "Project releaser",
		Predefined: true,
		Permissions: permissionSet(
			permission.DatabaseCatalogsGet,
			permission.ChangelogsGet,
			permission.DatabaseGroupsGet,
			permission.DatabaseGroupsList,
			permission.DatabasesCheck,
			permission.DatabasesGet,
			permission.DatabasesGetSchema,
			permission.DatabasesList,
			permission.IssueCommentsCreate,
			permission.IssueCommentsList,
			permission.IssueCommentsUpdate,
			permission.IssuesGet,
			permission.IssuesList,
			permission.PlanCheckRunsGet,
			permission.PlanCheckRunsRun,
			permission.PlansGet,
			permission.PlansList,
			permission.ProjectsGet,
			permission.ProjectsGetIAMPolicy,
			permission.ReleasesGet,
			permission.ReleasesList,
			permission.RevisionsGet,
			permission.RevisionsList,
			permission.RolloutsCreate,
			permission.RolloutsGet,
			permission.RolloutsList,
			permission.SheetsGet,
			permission.TaskRunsCreate,
			permission.TaskRunsList,
		),
	},
	{
		ResourceID: GitOpsServiceAgentRole,
		Name:       "GitOps Service Agent",
		Predefined: true,
		Permissions: permissionSet(
			permission.PlansCreate,
			permission.PlansGet,
			permission.ReleasesCheck,
			permission.ReleasesCreate,
			permission.ReleasesGet,
			permission.RolloutsCreate,
			permission.RolloutsGet,
			permission.RolloutsList,
			permission.TaskRunsCreate,
			permission.TaskRunsList,
		),
	},
	{
		ResourceID: ProjectViewerRole,
		Name:       "Project viewer",
		Predefined: true,
		Permissions: permissionSet(
			permission.DatabaseCatalogsGet,
			permission.DatabaseGroupsGet,
			permission.DatabaseGroupsList,
			permission.DatabasesGet,
			permission.DatabasesGetSchema,
			permission.DatabasesList,
			permission.IssueCommentsCreate,
			permission.IssueCommentsList,
			permission.IssueCommentsUpdate,
			permission.IssuesCreate,
			permission.ProjectsGet,
			permission.ProjectsGetIAMPolicy,
			permission.IssuesGet,
		),
	},
}

var predefinedRolesMap = func() map[string]*RoleMessage {
	m := make(map[string]*RoleMessage, len(PredefinedRoles))
	for _, role := range PredefinedRoles {
		m[role.ResourceID] = role
	}
	return m
}()

// GetPredefinedRole returns the predefined role by ID.
func GetPredefinedRole(roleID string) *RoleMessage {
	return predefinedRolesMap[roleID]
}

// IsPredefinedRole returns true if the role ID is a predefined role.
func IsPredefinedRole(roleID string) bool {
	_, ok := predefinedRolesMap[roleID]
	return ok
}
