.PHONY: mysql
mysql: mysql-8.0.28-macos11-arm64.tar.gz mysql-8.0.28-linux-glibc2.17-x86_64-minimal.tar.xz

mysql-8.0.28-macos11-arm64.tar.gz:
	curl -O https://cdn.mysql.com//Downloads/MySQL-8.0/mysql-8.0.28-macos11-arm64.tar.gz

mysql-8.0.28-linux-glibc2.17-x86_64-minimal.tar.xz:
	curl -O https://cdn.mysql.com//Downloads/MySQL-8.0/mysql-8.0.28-linux-glibc2.17-x86_64-minimal.tar.xz
