// Code generated by protoc-gen-equal-go. DO NOT EDIT.
// source: store/common.proto

package store

func (x *PageToken) Equal(y *PageToken) bool {
	if x == y {
		return true
	}
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if x.Limit != y.Limit {
		return false
	}
	if x.Offset != y.Offset {
		return false
	}
	return true
}

func (x *Position) Equal(y *Position) bool {
	if x == y {
		return true
	}
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if x.Line != y.Line {
		return false
	}
	if x.Column != y.Column {
		return false
	}
	return true
}

func (x *Range) Equal(y *Range) bool {
	if x == y {
		return true
	}
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if x.Start != y.Start {
		return false
	}
	if x.End != y.End {
		return false
	}
	return true
}
