// Code generated by protoc-gen-equal-go. DO NOT EDIT.
// source: store/worksheet.proto

package store

func (x *WorkSheetOrganizerPayload) Equal(y *WorkSheetOrganizerPayload) bool {
	if x == y {
		return true
	}
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if x.Starred != y.Starred {
		return false
	}
	if len(x.Folders) != len(y.Folders) {
		return false
	}
	for i := 0; i < len(x.Folders); i++ {
		if x.Folders[i] != y.Folders[i] {
			return false
		}
	}
	return true
}
