
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN SELECT id, payload FROM review_config
    LOOP
        UPDATE review_config
        SET payload = jsonb_set(
            r.payload,
            '{sqlReviewRules}',
            (
                SELECT jsonb_agg(
                    CASE (rule->>'type')
                WHEN 'naming.table' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_TABLE'::text))
                WHEN 'naming.column' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_COLUMN'::text))
                WHEN 'naming.index.pk' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_INDEX_PK'::text))
                WHEN 'naming.index.uk' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_INDEX_UK'::text))
                WHEN 'naming.index.fk' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_INDEX_FK'::text))
                WHEN 'naming.index.idx' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_INDEX_IDX'::text))
                WHEN 'naming.auto-increment-column' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_COLUMN_AUTO_INCREMENT'::text))
                WHEN 'naming.column.auto-increment' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_COLUMN_AUTO_INCREMENT'::text))
                WHEN 'naming.fully-qualified' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_FULLY_QUALIFIED'::text))
                WHEN 'naming.table-no-keyword' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_TABLE_NO_KEYWORD'::text))
                WHEN 'naming.table.no-keyword' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_TABLE_NO_KEYWORD'::text))
                WHEN 'naming.identifier-no-keyword' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_IDENTIFIER_NO_KEYWORD'::text))
                WHEN 'naming.identifier.no-keyword' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_IDENTIFIER_NO_KEYWORD'::text))
                WHEN 'naming.identifier-case' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_IDENTIFIER_CASE'::text))
                WHEN 'naming.identifier.case' THEN jsonb_set(rule, '{type}', to_jsonb('NAMING_IDENTIFIER_CASE'::text))
                WHEN 'statement.select.no-select-all' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_SELECT_NO_SELECT_ALL'::text))
                WHEN 'statement.where.require-select' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_WHERE_REQUIRE_SELECT'::text))
                WHEN 'statement.where.require.select' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_WHERE_REQUIRE_SELECT'::text))
                WHEN 'statement.where.require-update-delete' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_WHERE_REQUIRE_UPDATE_DELETE'::text))
                WHEN 'statement.where.require.update-delete' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_WHERE_REQUIRE_UPDATE_DELETE'::text))
                WHEN 'statement.where.no-leading-wildcard-like' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_WHERE_NO_LEADING_WILDCARD_LIKE'::text))
                WHEN 'statement.disallow-on-del-cascade' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_DISALLOW_ON_DEL_CASCADE'::text))
                WHEN 'statement.disallow-rm-tbl-cascade' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_DISALLOW_RM_TBL_CASCADE'::text))
                WHEN 'statement.disallow-commit' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_DISALLOW_COMMIT'::text))
                WHEN 'statement.disallow-limit' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_DISALLOW_LIMIT'::text))
                WHEN 'statement.disallow-order-by' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_DISALLOW_ORDER_BY'::text))
                WHEN 'statement.merge-alter-table' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_MERGE_ALTER_TABLE'::text))
                WHEN 'statement.insert.row-limit' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_INSERT_ROW_LIMIT'::text))
                WHEN 'statement.insert.must-specify-column' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_INSERT_MUST_SPECIFY_COLUMN'::text))
                WHEN 'statement.insert.disallow-order-by-rand' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_INSERT_DISALLOW_ORDER_BY_RAND'::text))
                WHEN 'statement.affected-row-limit' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_AFFECTED_ROW_LIMIT'::text))
                WHEN 'statement.dml-dry-run' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_DML_DRY_RUN'::text))
                WHEN 'statement.disallow-add-column-with-default' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_DISALLOW_ADD_COLUMN_WITH_DEFAULT'::text))
                WHEN 'statement.add-check-not-valid' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_ADD_CHECK_NOT_VALID'::text))
                WHEN 'statement.add-foreign-key-not-valid' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_ADD_FOREIGN_KEY_NOT_VALID'::text))
                WHEN 'statement.disallow-add-not-null' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_DISALLOW_ADD_NOT_NULL'::text))
                WHEN 'statement.select-full-table-scan' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_SELECT_FULL_TABLE_SCAN'::text))
                WHEN 'statement.create-specify-schema' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_CREATE_SPECIFY_SCHEMA'::text))
                WHEN 'statement.check-set-role-variable' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_CHECK_SET_ROLE_VARIABLE'::text))
                WHEN 'statement.disallow-using-filesort' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_DISALLOW_USING_FILESORT'::text))
                WHEN 'statement.disallow-using-temporary' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_DISALLOW_USING_TEMPORARY'::text))
                WHEN 'statement.where-no-equal-null' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_WHERE_NO_EQUAL_NULL'::text))
                WHEN 'statement.where.no-equal-null' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_WHERE_NO_EQUAL_NULL'::text))
                WHEN 'statement.where-disallow-functions-and-calculations' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_WHERE_DISALLOW_FUNCTIONS_AND_CALCULATIONS'::text))
                WHEN 'statement.where.disallow-functions-and-calculations' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_WHERE_DISALLOW_FUNCTIONS_AND_CALCULATIONS'::text))
                WHEN 'statement.query-minimum-plan-level' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_QUERY_MINIMUM_PLAN_LEVEL'::text))
                WHEN 'statement.query.minimum-plan-level' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_QUERY_MINIMUM_PLAN_LEVEL'::text))
                WHEN 'statement.where-maximum-logical-operator-count' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_WHERE_MAXIMUM_LOGICAL_OPERATOR_COUNT'::text))
                WHEN 'statement.where.maximum-logical-operator-count' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_WHERE_MAXIMUM_LOGICAL_OPERATOR_COUNT'::text))
                WHEN 'statement.maximum-limit-value' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_MAXIMUM_LIMIT_VALUE'::text))
                WHEN 'statement.maximum-join-table-count' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_MAXIMUM_JOIN_TABLE_COUNT'::text))
                WHEN 'statement.maximum-statements-in-transaction' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_MAXIMUM_STATEMENTS_IN_TRANSACTION'::text))
                WHEN 'statement.join-strict-column-attrs' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_JOIN_STRICT_COLUMN_ATTRS'::text))
                WHEN 'statement.non-transactional' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_NON_TRANSACTIONAL'::text))
                WHEN 'statement.add-column-without-position' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_ADD_COLUMN_WITHOUT_POSITION'::text))
                WHEN 'statement.disallow-offline-ddl' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_DISALLOW_OFFLINE_DDL'::text))
                WHEN 'statement.disallow-cross-db-queries' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_DISALLOW_CROSS_DB_QUERIES'::text))
                WHEN 'statement.max-execution-time' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_MAX_EXECUTION_TIME'::text))
                WHEN 'statement.require-algorithm-option' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_REQUIRE_ALGORITHM_OPTION'::text))
                WHEN 'statement.require-lock-option' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_REQUIRE_LOCK_OPTION'::text))
                WHEN 'statement.object-owner-check' THEN jsonb_set(rule, '{type}', to_jsonb('STATEMENT_OBJECT_OWNER_CHECK'::text))
                WHEN 'table.require-pk' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_REQUIRE_PK'::text))
                WHEN 'table.no-fk' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_NO_FOREIGN_KEY'::text))
                WHEN 'table.no-foreign-key' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_NO_FOREIGN_KEY'::text))
                WHEN 'table.drop-naming-convention' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_DROP_NAMING_CONVENTION'::text))
                WHEN 'table.comment' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_COMMENT'::text))
                WHEN 'table.disallow-partition' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_DISALLOW_PARTITION'::text))
                WHEN 'table.disallow-trigger' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_DISALLOW_TRIGGER'::text))
                WHEN 'table.no-duplicate-index' THEN jsonb_set(rule, '{type}', to_jsonb('INDEX_NO_DUPLICATE_COLUMN'::text))
                WHEN 'table.text-fields-total-length' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_TEXT_FIELDS_TOTAL_LENGTH'::text))
                WHEN 'table.disallow-set-charset' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_DISALLOW_SET_CHARSET'::text))
                WHEN 'table.disallow-ddl' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_DISALLOW_DDL'::text))
                WHEN 'table.disallow-dml' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_DISALLOW_DML'::text))
                WHEN 'table.limit-size' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_LIMIT_SIZE'::text))
                WHEN 'table.require-charset' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_REQUIRE_CHARSET'::text))
                WHEN 'table.require-collation' THEN jsonb_set(rule, '{type}', to_jsonb('TABLE_REQUIRE_COLLATION'::text))
                WHEN 'column.required' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_REQUIRED'::text))
                WHEN 'column.no-null' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_NO_NULL'::text))
                WHEN 'column.disallow-change-type' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_DISALLOW_CHANGE_TYPE'::text))
                WHEN 'column.set-default-for-not-null' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_SET_DEFAULT_FOR_NOT_NULL'::text))
                WHEN 'column.disallow-change' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_DISALLOW_CHANGE'::text))
                WHEN 'column.disallow-changing-order' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_DISALLOW_CHANGING_ORDER'::text))
                WHEN 'column.disallow-drop' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_DISALLOW_DROP'::text))
                WHEN 'column.disallow-drop-in-index' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_DISALLOW_DROP_IN_INDEX'::text))
                WHEN 'column.comment' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_COMMENT'::text))
                WHEN 'column.auto-increment-must-integer' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_AUTO_INCREMENT_MUST_INTEGER'::text))
                WHEN 'column.type-disallow-list' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_TYPE_DISALLOW_LIST'::text))
                WHEN 'column.disallow-set-charset' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_DISALLOW_SET_CHARSET'::text))
                WHEN 'column.maximum-character-length' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_MAXIMUM_CHARACTER_LENGTH'::text))
                WHEN 'column.maximum-varchar-length' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_MAXIMUM_VARCHAR_LENGTH'::text))
                WHEN 'column.auto-increment-initial-value' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_AUTO_INCREMENT_INITIAL_VALUE'::text))
                WHEN 'column.auto-increment-must-unsigned' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_AUTO_INCREMENT_MUST_UNSIGNED'::text))
                WHEN 'column.current-time-column-count-limit' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_CURRENT_TIME_COUNT_LIMIT'::text))
                WHEN 'column.current-time-count-limit' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_CURRENT_TIME_COUNT_LIMIT'::text))
                WHEN 'column.require-default' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_REQUIRE_DEFAULT'::text))
                WHEN 'column.default-disallow-volatile' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_DEFAULT_DISALLOW_VOLATILE'::text))
                WHEN 'column.add-not-null-require-default' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_ADD_NOT_NULL_REQUIRE_DEFAULT'::text))
                WHEN 'column.require-charset' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_REQUIRE_CHARSET'::text))
                WHEN 'column.require-collation' THEN jsonb_set(rule, '{type}', to_jsonb('COLUMN_REQUIRE_COLLATION'::text))
                WHEN 'schema.backward-compatibility' THEN jsonb_set(rule, '{type}', to_jsonb('SCHEMA_BACKWARD_COMPATIBILITY'::text))
                WHEN 'database.drop-empty-database' THEN jsonb_set(rule, '{type}', to_jsonb('DATABASE_DROP_EMPTY_DATABASE'::text))
                WHEN 'index.no-duplicate-column' THEN jsonb_set(rule, '{type}', to_jsonb('INDEX_NO_DUPLICATE_COLUMN'::text))
                WHEN 'index.key-number-limit' THEN jsonb_set(rule, '{type}', to_jsonb('INDEX_KEY_NUMBER_LIMIT'::text))
                WHEN 'index.pk-type-limit' THEN jsonb_set(rule, '{type}', to_jsonb('INDEX_PK_TYPE_LIMIT'::text))
                WHEN 'index.type-no-blob' THEN jsonb_set(rule, '{type}', to_jsonb('INDEX_TYPE_NO_BLOB'::text))
                WHEN 'index.total-number-limit' THEN jsonb_set(rule, '{type}', to_jsonb('INDEX_TOTAL_NUMBER_LIMIT'::text))
                WHEN 'index.primary-key-type-allowlist' THEN jsonb_set(rule, '{type}', to_jsonb('INDEX_PRIMARY_KEY_TYPE_ALLOWLIST'::text))
                WHEN 'index.create-concurrently' THEN jsonb_set(rule, '{type}', to_jsonb('INDEX_CREATE_CONCURRENTLY'::text))
                WHEN 'index.type-allow-list' THEN jsonb_set(rule, '{type}', to_jsonb('INDEX_TYPE_ALLOW_LIST'::text))
                WHEN 'index.not-redundant' THEN jsonb_set(rule, '{type}', to_jsonb('INDEX_NOT_REDUNDANT'::text))
                WHEN 'system.charset-allowlist' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_CHARSET_ALLOWLIST'::text))
                WHEN 'system.charset.allowlist' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_CHARSET_ALLOWLIST'::text))
                WHEN 'system.collation-allowlist' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_COLLATION_ALLOWLIST'::text))
                WHEN 'system.collation.allowlist' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_COLLATION_ALLOWLIST'::text))
                WHEN 'system.comment-length' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_COMMENT_LENGTH'::text))
                WHEN 'system.comment.length' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_COMMENT_LENGTH'::text))
                WHEN 'system.procedure-disallow-create' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_PROCEDURE_DISALLOW_CREATE'::text))
                WHEN 'system.procedure.disallow-create' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_PROCEDURE_DISALLOW_CREATE'::text))
                WHEN 'system.event-disallow-create' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_EVENT_DISALLOW_CREATE'::text))
                WHEN 'system.event.disallow-create' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_EVENT_DISALLOW_CREATE'::text))
                WHEN 'system.view-disallow-create' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_VIEW_DISALLOW_CREATE'::text))
                WHEN 'system.view.disallow-create' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_VIEW_DISALLOW_CREATE'::text))
                WHEN 'system.function-disallow-create' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_FUNCTION_DISALLOW_CREATE'::text))
                WHEN 'system.function.disallow-create' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_FUNCTION_DISALLOW_CREATE'::text))
                WHEN 'system.function-disallowed-list' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_FUNCTION_DISALLOWED_LIST'::text))
                WHEN 'system.function.disallowed-list' THEN jsonb_set(rule, '{type}', to_jsonb('SYSTEM_FUNCTION_DISALLOWED_LIST'::text))
                WHEN 'advice.online-migration' THEN jsonb_set(rule, '{type}', to_jsonb('ADVICE_ONLINE_MIGRATION'::text))
                WHEN 'engine.mysql.use-innodb' THEN jsonb_set(rule, '{type}', to_jsonb('ENGINE_MYSQL_USE_INNODB'::text))
                        ELSE rule
                    END
                )
                FROM jsonb_array_elements(r.payload->'sqlReviewRules') AS rules(rule)
            )
        )
        WHERE id = r.id and r.payload ->> 'sqlReviewRules' IS NOT NULL;
    END LOOP;
END $$;
