-- Column for database 7002 testdb_dev, table 7101 tbl1 
INSERT INTO
    col (
        id,
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        7201,
        101,
        101,
        7002,
        7101,
        'OK',
        1625075289,
        'col1',
        1,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        'I am a comment'
    );

-- Column for database 7006 testdb_integration, table 7102 tbl1 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7006,
        7102,
        'OK',
        1625075289,
        'col1',
        1,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        'I am a comment'
    );

-- Column for database 7010 testdb_staging, table 7103 tbl1 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7010,
        7103,
        'OK',
        1625075289,
        'col1',
        1,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        'I am a comment'
    );

-- Column for database 7014 testdb_prod, table 7104 tbl1 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7014,
        7104,
        'OK',
        1625075289,
        'col1',
        1,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        'I am a comment'
    );

-- Column for database 7003 shop, table 7105 product 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7003,
        7105,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7003,
        7105,
        'OK',
        1625075289,
        'name',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7003,
        7105,
        'OK',
        1625075289,
        'description',
        3,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

-- Column for database 7007 shop, table 7106 product 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7007,
        7106,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7007,
        7106,
        'OK',
        1625075289,
        'name',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7007,
        7106,
        'OK',
        1625075289,
        'description',
        3,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

-- Column for database 7004 blog, table 7107 user 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7004,
        7107,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7004,
        7107,
        'OK',
        1625075289,
        'name',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7004,
        7107,
        'OK',
        1625075289,
        'email',
        3,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

-- Column for database 7004 blog, table 7108 post 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7004,
        7108,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7004,
        7108,
        'OK',
        1625075289,
        'name',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7004,
        7108,
        'OK',
        1625075289,
        'content',
        3,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7004,
        7108,
        'OK',
        1625075289,
        'author_id',
        4,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

-- Column for database 7004 blog, table 7109 comment 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7004,
        7109,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7004,
        7109,
        'OK',
        1625075289,
        'content',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7004,
        7109,
        'OK',
        1625075289,
        'post_id',
        3,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7004,
        7109,
        'OK',
        1625075289,
        'author_id',
        4,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

-- Column for database 7008 blog, table 7110 user 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7008,
        7110,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7008,
        7110,
        'OK',
        1625075289,
        'name',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7008,
        7110,
        'OK',
        1625075289,
        'email',
        3,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

-- Column for database 7008 blog, table 7111 post 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7008,
        7111,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7008,
        7111,
        'OK',
        1625075289,
        'name',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7008,
        7111,
        'OK',
        1625075289,
        'content',
        3,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7008,
        7111,
        'OK',
        1625075289,
        'author_id',
        4,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

-- Column for database 7008 blog, table 7112 comment 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7008,
        7112,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7008,
        7112,
        'OK',
        1625075289,
        'content',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7008,
        7112,
        'OK',
        1625075289,
        'post_id',
        3,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7008,
        7112,
        'OK',
        1625075289,
        'author_id',
        4,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

-- Column for database 7012 blog, table 7113 user 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7012,
        7113,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7012,
        7113,
        'OK',
        1625075289,
        'name',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7012,
        7113,
        'OK',
        1625075289,
        'email',
        3,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

-- Column for database 7012 blog, table 7114 post 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7012,
        7114,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7012,
        7114,
        'OK',
        1625075289,
        'name',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7012,
        7114,
        'OK',
        1625075289,
        'content',
        3,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7012,
        7114,
        'OK',
        1625075289,
        'author_id',
        4,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

-- Column for database 7012 blog, table 7115 comment 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7012,
        7115,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7012,
        7115,
        'OK',
        1625075289,
        'content',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7012,
        7115,
        'OK',
        1625075289,
        'post_id',
        3,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7012,
        7115,
        'OK',
        1625075289,
        'author_id',
        4,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

-- Column for database 7016 blog, table 7116 user 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7016,
        7116,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7016,
        7116,
        'OK',
        1625075289,
        'name',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7016,
        7116,
        'OK',
        1625075289,
        'email',
        3,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

-- Column for database 7008 blog, table 7117 post 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7016,
        7117,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7016,
        7117,
        'OK',
        1625075289,
        'name',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7016,
        7117,
        'OK',
        1625075289,
        'content',
        3,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7016,
        7117,
        'OK',
        1625075289,
        'author_id',
        4,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

-- Column for database 7016 blog, table 7118 comment 
INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7016,
        7118,
        'OK',
        1625075289,
        'id',
        1,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7016,
        7118,
        'OK',
        1625075289,
        'content',
        2,
        NULL,
        0,
        'text',
        'utf8mb4',
        'utf8mb4_0900_ai_ci',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7016,
        7118,
        'OK',
        1625075289,
        'post_id',
        3,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );

INSERT INTO
    col (
        creator_id,
        updater_id,
        database_id,
        table_id,
        sync_status,
        last_successful_sync_ts,
        name,
        position,
        `default`,
        `nullable`,
        `type`,
        character_set,
        `collation`,
        `comment`
    )
VALUES
    (
        101,
        101,
        7016,
        7118,
        'OK',
        1625075289,
        'author_id',
        4,
        NULL,
        0,
        'int',
        '',
        '',
        ''
    );