root = "."
tmp_dir = ".air"

[build]
  bin = "./.air/sql-review --port 8081"
  cmd = """
  go build -gcflags=all=\"-N -l\" \
  -ldflags " \
  -X 'github.com/bytebase/bytebase/bin/sql-review/cmd.version=development' \
  -X 'github.com/bytebase/bytebase/bin/sql-review/cmd.goversion=$(go version)' \
  -X 'github.com/bytebase/bytebase/bin/sql-review/cmd.gitcommit=$(git rev-parse HEAD)' \
  -X 'github.com/bytebase/bytebase/bin/sql-review/cmd.buildtime=$(date -u +"%Y-%m-%dT%H:%M:%SZ")' \
  -X 'github.com/bytebase/bytebase/bin/sql-review/cmd.builduser=$(id -u -n)' \
  " \
  -o ./.air/sql-review ./bin/sql-review/main.go"""
  delay = 1000
  exclude_dir = [".air", "vendor", "frontend", "docs"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  send_interrupt = true
  kill_delay = 1000
  full_bin = ""
