root = "."
tmp_dir = ".air"

[build]
  bin = "./.air/sql-service --port 8081"
  cmd = """
  go build \
  -o ./.air/sql-service ./backend/bin/sql-service/main.go"""
  delay = 1000
  exclude_dir = [".air", "vendor", "frontend", "docs"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  send_interrupt = true
  kill_delay = 1000
  full_bin = ""
