# Using `git update-index --assume-unchanged scripts/.air.toml` to let git untrack it.
root = "."
tmp_dir = ".air"

[build]
  bin = './.air/bytebase --port 8080 --data . --debug --disable-sample'
  ## Use --tags "store.db" to enable SQL query logging against our metadata db.
  ## Use --tags "release" to enable ultimate driver package such as Oracle, MSSQL. The default drivers only include MySQL, PostgreSQL, SQLite.
  cmd = """
  go build \
  --tags "" \
  -o ./.air/bytebase ./backend/bin/server/main.go"""
  delay = 500
  exclude_dir = [".air", "bytebase-build", "docs", "frontend", "helm-charts", "proto", "quickstart", "scripts",  "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  send_interrupt = true
  kill_delay = 1000
