builds:
  - id: server
    main: ./backend/bin/server
    binary: bytebase
    ldflags:
      - -w -s
      - -X github.com/bytebase/bytebase/backend/bin/server/cmd.version={{.Version}}
      - -X github.com/bytebase/bytebase/backend/bin/server/cmd.goversion=${GO_VERSION}
      - -X github.com/bytebase/bytebase/backend/bin/server/cmd.gitcommit={{.Commit}}
      - -X github.com/bytebase/bytebase/backend/bin/server/cmd.buildtime={{.Timestamp}}
      - -X github.com/bytebase/bytebase/backend/bin/server/cmd.builduser=goreleaser
    tags:
      - release
      - embed_frontend
    env:
      - VERSION="development"
      - GO_VERSION="1.21.6"
      - CGO_ENABLED=1
      - GIT_COMMIT="unknown"
      - BUILD_TIME="unknown"
      - BUILD_USER="unknown"
    goos:
      - darwin
    goarch:
      - arm64

archives:
- format: tar.gz
  id: bytebase
  builds: [server]
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - LICENSE*

checksum:
  disable: true

snapshot:
  name_template: "{{ incpatch .Version }}-next"
