builds:
  - skip: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  draft: true
  mode: append
  name_template: "Release {{.Tag}}"
  header: |
    # What's Changed

    ## 🚀 Features

    ## 🎄 Enhancements

    ## 🎠 Community

    ## New Contributors

    ## Code Diff
