before:
  hooks:
    - go mod tidy
builds:
  - id: server
    main: ./backend/bin/server
    binary: bytebase
    ldflags:
      - -w -s
      - -X github.com/bytebase/bytebase/backend/bin/server/cmd.version={{.Version}}
      - -X github.com/bytebase/bytebase/backend/bin/server/cmd.goversion=${GO_VERSION}
      - -X github.com/bytebase/bytebase/backend/bin/server/cmd.gitcommit={{.Commit}}
      - -X github.com/bytebase/bytebase/backend/bin/server/cmd.buildtime={{.Timestamp}}
      - -X github.com/bytebase/bytebase/backend/bin/server/cmd.builduser=goreleaser
    tags:
      - release
      - embed_frontend
    env:
      - VERSION="development"
      - GO_VERSION="1.21.3"
      - CGO_ENABLED=1
      - GIT_COMMIT="unknown"
      - BUILD_TIME="unknown"
      - BUILD_USER="unknown"
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: cli
    main: ./backend/bin/bb
    binary: bb
    ldflags:
      - -w -s
      - -X github.com/bytebase/bytebase/backend/bin/bb/cmd.version={{.Version}}
      - -X github.com/bytebase/bytebase/backend/bin/bb/cmd.goversion=${GO_VERSION}
      - -X github.com/bytebase/bytebase/backend/bin/bb/cmd.gitcommit={{.Commit}}
      - -X github.com/bytebase/bytebase/backend/bin/bb/cmd.buildtime={{.Timestamp}}
      - -X github.com/bytebase/bytebase/backend/bin/bb/cmd.builduser=goreleaser
    tags:
      - release
    env:
      - VERSION="development"
      - GO_VERSION="1.21.3"
      - CGO_ENABLED=1
      - GIT_COMMIT="unknown"
      - BUILD_TIME="unknown"
      - BUILD_USER="unknown"
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
snapshot:
  name_template: "{{ incpatch .Version }}-next"
