FROM golang:1.24.2-alpine3.21 AS builder
WORKDIR /action-build
COPY action/ action/
COPY . .
RUN go build -o bytebase-action action/*.go

FROM alpine:3.21
WORKDIR /
COPY --from=builder /action-build/bytebase-action /usr/local/bin/bytebase-action
COPY --from=builder /etc/ssl/certs /etc/ssl/certs
CMD ["bytebase-action"]