ALTER TABLE db DROP COLUMN IF EXISTS sync_at;
ALTER TABLE db DROP COLUMN IF EXISTS schema_version;
ALTER TABLE db DROP COLUMN IF EXISTS secrets;
ALTER TABLE db DROP COLUMN IF EXISTS datashare;
ALTER TABLE db DROP COLUMN IF EXISTS service_name;

