#!/bin/sh
# https://github.com/typicode/husky/issues/390#issuecomment-792619315
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
. "$(dirname "$0")/_/husky.sh"

npx --no -- commitlint --edit "$1"
