name: Build Test Image

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DDOCKERHUB_USERNAME }}
          password: ${{ secrets.DDOCKERHUB_TOKEN }}
      - uses: depot/setup-action@v1
      - name: Build and push
        id: docker_build
        uses: depot/build-push-action@v1
        with:
          context: .
          project: ${{ secrets.DEPOT_PROJECT}}
          token: ${{ secrets.DEPOT_TOKEN }}
          file: scripts/Dockerfile.render-demo
          platforms: linux/amd64
          push: true
          tags: dbytebase/chatgpt:release-ci
      - name: Image digest
        run: echo "Successfully pushed bytebase/bytebase:release-ci " ${{ steps.docker_build.outputs.digest }}
