name: codenotify
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  codenotify:
    permissions:
      actions: read
      checks: write
      contents: read
      pull-requests: write
      statuses: write
    runs-on: ubuntu-latest
    name: Codenotify
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: sourcegraph/codenotify@v0.6.2
        with:
          filename: 'CODENOTIFY'
          subscriber-threshold: '5'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
