name: Frontend linter

on:
  push:
    branches:
      - main
      - "release/*.*.*"
  pull_request:

jobs:
  frontend-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.10.0
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: pnpm
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
        working-directory: frontend
      - run: pnpm release
        working-directory: frontend
      - name: Run lint
        run: pnpm lint
