# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: golangci-lint

on:
  pull_request:
    branches:
      - main
      - "release/*.*.*"
    paths-ignore:
      - "backend/**"
      - "go.mod"

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required"'
