name: golangci-lint

on:
  pull_request:
    branches:
      - main
      - "release/*.*.*"
    paths-ignore:
      - "backend/**"
      - "go.mod"

jobs:
  golangci-lint-tests:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required"'
