name: Change dependency needs admin approval

on:
  pull_request_target:
    paths:
      - "frontend/package.json"
      - "go.mod"

env:
  REVIEWERS: tianzhou,d-bytebase

jobs:
  request-dependency-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr edit $PR_NUMBER --add-reviewer $REVIEWERS
