# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: Proto linter

on:
  pull_request:
    branches:
      - main
      - "release/*.*.*"
    paths-ignore:
      - "proto/**"

jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required"'
