name: Release Test Link

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "frontend/**"

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required"'
